CREATE TABLE CIA_CARTA_SERVICO (
    ID_CARTA_SERVICO INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    DESC_CONTEUDO TEXT NOT NULL,
    INFO_METADADO TEXT NOT NULL,
    INFO_EMBEDDING TEXT,

    CONSTRAINT PK_CIA_CARTA_SERVICO PRIMARY KEY (ID_CARTA_SERVICO)
)
;

CREATE INDEX IDX_CIA_CARTA_SERVICO_EMBED ON CIA_CARTA_SERVICO (ID_CARTA_SERVICO);
;

COMMENT ON TABLE CIA_CARTA_SERVICO IS
'Tabela responsável pelo armazenamento das cartas de serviço utilizadas pela plataforma, incluindo conteúdo textual, metadados e informações vetoriais para pesquisa semântica.';

COMMENT ON COLUMN CIA_CARTA_SERVICO.ID_CARTA_SERVICO IS
'Identificador único da carta de serviço cadastrada na plataforma.';

COMMENT ON COLUMN CIA_CARTA_SERVICO.DESC_CONTEUDO IS
'Conteúdo textual completo da carta de serviço.';

COMMENT ON COLUMN CIA_CARTA_SERVICO.INFO_METADADO IS
'Metadados estruturados relacionados à carta de serviço armazenados em formato JSON.';

COMMENT ON COLUMN CIA_CARTA_SERVICO.INFO_EMBEDDING IS
'Informações vetoriais utilizadas em mecanismos de busca semântica e inteligência artificial.';
