CREATE TABLE CIA_REACAO_COMENTARIO_IDEIA (
    ID_COMENTARIO_IDEIA INTEGER NOT NULL,
    ID_USUARIO INTEGER NOT NULL,
    TIPO_REACAO VARCHAR(40) NOT NULL,
    DATA_CRIACAO TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_CIA_REACAO_COMENTARIO_IDEA
        PRIMARY KEY (ID_COMENTARIO_IDEIA, ID_USUARIO),

    CONSTRAINT FK_CIA_REACAO_COM_IDEA FOREIGN KEY (ID_COMENTARIO_IDEIA)
        REFERENCES CIA_COMENTARIO_IDEIA (ID_COMENTARIO_IDEIA) ON DELETE CASCADE,

    CONSTRAINT FK_CIA_REACAO_COM_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES CIA_USUARIO (ID_USUARIO) ON DELETE CASCADE,

    CONSTRAINT CK_CIA_REACAO_TIPO
        CHECK (
            TIPO_REACAO IN (
                'thumbs_up',
                'heart',
                'rocket',
                'eyes',
                'idea'
            )
        )
)
;

CREATE INDEX IDX_CIA_REACAO_COM_USUARIO
    ON CIA_REACAO_COMENTARIO_IDEIA (ID_USUARIO, DATA_CRIACAO)
;

COMMENT ON TABLE CIA_REACAO_COMENTARIO_IDEIA IS
'Tabela responsável pelo armazenamento das reações realizadas pelos usuários nos comentários de ideias da plataforma.';

COMMENT ON COLUMN CIA_REACAO_COMENTARIO_IDEIA.ID_COMENTARIO_IDEIA IS
'Identificador do comentário de ideia associado à reação registrada.';

COMMENT ON COLUMN CIA_REACAO_COMENTARIO_IDEIA.ID_USUARIO IS
'Identificador do usuário responsável pela reação registrada.';

COMMENT ON COLUMN CIA_REACAO_COMENTARIO_IDEIA.TIPO_REACAO IS
'Tipo de reação aplicada ao comentário da ideia.';

COMMENT ON COLUMN CIA_REACAO_COMENTARIO_IDEIA.DATA_CRIACAO IS
'Data e hora de criação do registro da reação.';
