-- TIPO_CLIENTE: {
--     CLD: 'Claude Desktop',
--     VSC: 'VS Code',
--     CUR: 'Cursor',
--     TER: 'Terminal',
--     CUS: 'Customizado'
-- }

CREATE TABLE CIA_CONFIGURACAO_MCP (
    ID_CONFIGURACAO_MCP INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ID_SERVIDOR_MCP INTEGER NOT NULL,
    TIPO_CLIENTE VARCHAR(20) NOT NULL,
    NOME_CONFIGURACAO VARCHAR(100) NOT NULL,
    INFO_CONFIGURACAO TEXT NOT NULL,
    DESC_OBSERVACAO TEXT,
    NUMR_ORDEM INTEGER DEFAULT 0 NOT NULL,

    CONSTRAINT PK_CIA_CONFIGURACAO_MCP
        PRIMARY KEY (ID_CONFIGURACAO_MCP),

    CONSTRAINT FK_CIA_CONFIG_MCP_SERV
        FOREIGN KEY (ID_SERVIDOR_MCP)
        REFERENCES CIA_SERVIDOR_MCP (ID_SERVIDOR_MCP)
        ON DELETE CASCADE,

    CONSTRAINT CK_CIA_CONFIG_MCP_CLIENTE
        CHECK (
            TIPO_CLIENTE IN (
                'CLD',
                'VSC',
                'CUR',
                'TER',
                'CUS'
            )
        )
)
;

CREATE INDEX IDX_CIA_CONFIG_MCP_SERV
    ON CIA_CONFIGURACAO_MCP (ID_SERVIDOR_MCP)
;

COMMENT ON TABLE CIA_CONFIGURACAO_MCP IS
'Tabela responsável pelo armazenamento das configurações de integração MCP disponíveis para diferentes tipos de clientes da plataforma.';

COMMENT ON COLUMN CIA_CONFIGURACAO_MCP.ID_CONFIGURACAO_MCP IS
'Identificador único da configuração MCP cadastrada.';

COMMENT ON COLUMN CIA_CONFIGURACAO_MCP.ID_SERVIDOR_MCP IS
'Identificador do servidor MCP associado à configuração.';

COMMENT ON COLUMN CIA_CONFIGURACAO_MCP.TIPO_CLIENTE IS
'Tipo de cliente compatível com a configuração MCP.';

COMMENT ON COLUMN CIA_CONFIGURACAO_MCP.NOME_CONFIGURACAO IS
'Nome identificador da configuração MCP disponibilizada ao cliente.';

COMMENT ON COLUMN CIA_CONFIGURACAO_MCP.INFO_CONFIGURACAO IS
'Conteúdo estruturado da configuração MCP em formato JSON ou textual.';

COMMENT ON COLUMN CIA_CONFIGURACAO_MCP.DESC_OBSERVACAO IS
'Observações complementares relacionadas à configuração MCP.';

COMMENT ON COLUMN CIA_CONFIGURACAO_MCP.NUMR_ORDEM IS
'Ordem de exibição da configuração MCP nas interfaces da plataforma.';
