CREATE TABLE CIA_FAVORITO_MCP (
    ID_USUARIO INTEGER NOT NULL,
    ID_SERVIDOR_MCP INTEGER NOT NULL,
    DATA_CRIACAO TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_CIA_FAVORITO_MCP
        PRIMARY KEY (
            ID_USUARIO,
            ID_SERVIDOR_MCP
        ),

    CONSTRAINT FK_CIA_FAVORITO_USUARIO
        FOREIGN KEY (ID_USUARIO)
        REFERENCES CIA_USUARIO (ID_USUARIO)
        ON DELETE CASCADE,

    CONSTRAINT FK_CIA_FAVORITO_SERVIDOR
        FOREIGN KEY (ID_SERVIDOR_MCP)
        REFERENCES CIA_SERVIDOR_MCP (ID_SERVIDOR_MCP)
        ON DELETE CASCADE
)
;

CREATE INDEX IDX_CIA_FAVORITO_MCP_USUARIO
    ON CIA_FAVORITO_MCP (
        ID_USUARIO,
        DATA_CRIACAO
    )
;

COMMENT ON TABLE CIA_FAVORITO_MCP IS
'Tabela responsável pelo armazenamento dos servidores MCP marcados como favoritos pelos usuários da plataforma.';

COMMENT ON COLUMN CIA_FAVORITO_MCP.ID_USUARIO IS
'Identificador do usuário responsável pela marcação de favorito.';

COMMENT ON COLUMN CIA_FAVORITO_MCP.ID_SERVIDOR_MCP IS
'Identificador do servidor MCP marcado como favorito pelo usuário.';

COMMENT ON COLUMN CIA_FAVORITO_MCP.DATA_CRIACAO IS
'Data e hora de criação do registro de favorito.';
