-- TIPO_CLIENTE: {
--     CLD: 'Claude Desktop',
--     VSC: 'VS Code',
--     CUR: 'Cursor',
--     TER: 'Terminal',
--     CUS: 'Customizado'
-- }

CREATE TABLE CIA_INSTALACAO_MCP (
    ID_INSTALACAO_MCP INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ID_SERVIDOR_MCP INTEGER NOT NULL,
    ID_USUARIO INTEGER NOT NULL,

    TIPO_CLIENTE VARCHAR(3),

    DATA_INSTALACAO TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_CIA_INSTALACAO_MCP
        PRIMARY KEY (ID_INSTALACAO_MCP),

    CONSTRAINT UK_CIA_INSTALACAO_MCP
        UNIQUE (
            ID_SERVIDOR_MCP,
            ID_USUARIO
        ),

    CONSTRAINT FK_CIA_INSTALACAO_SERV
        FOREIGN KEY (ID_SERVIDOR_MCP)
        REFERENCES CIA_SERVIDOR_MCP (ID_SERVIDOR_MCP)
        ON DELETE CASCADE,

    CONSTRAINT FK_CIA_INSTALACAO_USUARIO
        FOREIGN KEY (ID_USUARIO)
        REFERENCES CIA_USUARIO (ID_USUARIO)
        ON DELETE CASCADE,

    CONSTRAINT CK_CIA_INSTALACAO_CLIENTE
        CHECK (
            TIPO_CLIENTE IN (
                'CLD',
                'VSC',
                'CUR',
                'TER',
                'CUS'
            )
            OR TIPO_CLIENTE IS NULL
        )
)
;

CREATE INDEX IDX_CIA_INSTALACAO_SERV
    ON CIA_INSTALACAO_MCP (ID_SERVIDOR_MCP)
;

CREATE INDEX IDX_CIA_INSTALACAO_USUARIO
    ON CIA_INSTALACAO_MCP (ID_USUARIO)
;

COMMENT ON TABLE CIA_INSTALACAO_MCP IS
'Tabela responsável pelo armazenamento das instalações de servidores MCP realizadas pelos usuários da plataforma.';

COMMENT ON COLUMN CIA_INSTALACAO_MCP.ID_INSTALACAO_MCP IS
'Identificador único da instalação MCP cadastrada.';

COMMENT ON COLUMN CIA_INSTALACAO_MCP.ID_SERVIDOR_MCP IS
'Identificador do servidor MCP instalado pelo usuário.';

COMMENT ON COLUMN CIA_INSTALACAO_MCP.ID_USUARIO IS
'Identificador do usuário responsável pela instalação do servidor MCP.';

COMMENT ON COLUMN CIA_INSTALACAO_MCP.TIPO_CLIENTE IS
'Tipo de cliente utilizado na instalação MCP. CLD = Claude Desktop, VSC = Visual Studio Code, CUR = Cursor, TER = Terminal, CUS = Customizado.';

COMMENT ON COLUMN CIA_INSTALACAO_MCP.DATA_INSTALACAO IS
'Data e hora de realização da instalação do servidor MCP.';
