CREATE TABLE CIA_METRICA (
    ID_METRICA INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    DESC_METRICA TEXT NOT NULL,
    TIPO_METRICA VARCHAR(200) NOT NULL,

    CONSTRAINT PK_CIA_METRICA PRIMARY KEY (ID_METRICA)
)
;

CREATE INDEX IDX_CIA_METRICA_TIPO
    ON CIA_METRICA (TIPO_METRICA)
;

COMMENT ON TABLE CIA_METRICA IS
'Tabela responsável pelo cadastro das métricas utilizadas para avaliação e monitoramento na plataforma.';

COMMENT ON COLUMN CIA_METRICA.ID_METRICA IS
'Identificador único da métrica cadastrada.';

COMMENT ON COLUMN CIA_METRICA.DESC_METRICA IS
'Descrição textual da métrica utilizada pela plataforma.';

COMMENT ON COLUMN CIA_METRICA.TIPO_METRICA IS
'Tipo ou categoria da métrica cadastrada.';
