-- CATEGORIA_NOTICIA:
--  AT: Atualização,
--  MN: Manutenção,
--  AV: Aviso,
--  NR: Novo Recurso,
--  SG: Segurança

CREATE TABLE CIA_NOTICIA (
    ID_NOTICIA INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,

    CATEGORIA_NOTICIA VARCHAR(2) DEFAULT 'AV' NOT NULL,

    TITULO_NOTICIA VARCHAR(300) NOT NULL,

    DESC_RESUMO TEXT NOT NULL,

    DESC_CONTEUDO TEXT DEFAULT '' NOT NULL,

    URL_LINK VARCHAR(500),

    QTDE_TEMPO_LEITURA INTEGER DEFAULT 3 NOT NULL,

    INDI_PUBLICADO VARCHAR(1) DEFAULT 'N' NOT NULL,

    DATA_PUBLICACAO TIMESTAMPTZ,

    DATA_CRIACAO TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,

    DATA_ATUALIZACAO TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_CIA_NOTICIA
        PRIMARY KEY (ID_NOTICIA),

    CONSTRAINT CK_CIA_NOTICIA_CATEGORIA
        CHECK (
            CATEGORIA_NOTICIA IN (
                'AT',
                'MN',
                'AV',
                'NR',
                'SG'
            )
        ),

    CONSTRAINT CK_CIA_NOTICIA_PUBLICADO
        CHECK (
            INDI_PUBLICADO IN ('S', 'N')
        )
)
;

CREATE INDEX IDX_CIA_NOTICIA_PUBLICADA
    ON CIA_NOTICIA (
        INDI_PUBLICADO,
        DATA_PUBLICACAO
    )
;

COMMENT ON TABLE CIA_NOTICIA IS
'Tabela responsável pelo cadastro e publicação de notícias, comunicados e atualizações da plataforma.';

COMMENT ON COLUMN CIA_NOTICIA.ID_NOTICIA IS
'Identificador único da notícia cadastrada.';

COMMENT ON COLUMN CIA_NOTICIA.CATEGORIA_NOTICIA IS
'Categoria da notícia publicada. AT = Atualização, MN = Manutenção, AV = Aviso, NR = Novo Recurso, SG = Segurança.';

COMMENT ON COLUMN CIA_NOTICIA.TITULO_NOTICIA IS
'Título principal da notícia publicada na plataforma.';

COMMENT ON COLUMN CIA_NOTICIA.DESC_RESUMO IS
'Resumo descritivo da notícia utilizada para visualização rápida.';

COMMENT ON COLUMN CIA_NOTICIA.DESC_CONTEUDO IS
'Conteúdo completo da notícia publicada.';

COMMENT ON COLUMN CIA_NOTICIA.URL_LINK IS
'Endereço complementar relacionado à notícia ou publicação.';

COMMENT ON COLUMN CIA_NOTICIA.QTDE_TEMPO_LEITURA IS
'Tempo estimado de leitura da notícia em minutos.';

COMMENT ON COLUMN CIA_NOTICIA.INDI_PUBLICADO IS
'Indica se a notícia está publicada para visualização. S = Sim, N = Não.';

COMMENT ON COLUMN CIA_NOTICIA.DATA_PUBLICACAO IS
'Data e hora da publicação oficial da notícia.';

COMMENT ON COLUMN CIA_NOTICIA.DATA_CRIACAO IS
'Data e hora de criação do registro da notícia.';

COMMENT ON COLUMN CIA_NOTICIA.DATA_ATUALIZACAO IS
'Data e hora da última atualização do registro da notícia.';

CREATE OR REPLACE FUNCTION trg_bu_cia_noticia_fn()
RETURNS TRIGGER AS $$
BEGIN
  NEW.data_atualizacao = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_bu_cia_noticia
  BEFORE UPDATE ON cia_noticia
  FOR EACH ROW EXECUTE FUNCTION trg_bu_cia_noticia_fn();
