CREATE TABLE CIA_CATEGORIA_PROMPT (
    ID_CATEGORIA_PROMPT INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NOME_CATEGORIA VARCHAR(100) NOT NULL,
    SLUG_CATEGORIA VARCHAR(100) NOT NULL,
    CODG_COR VARCHAR(20) DEFAULT '#1a5e38' NOT NULL,
    NUMR_ORDEM INTEGER DEFAULT 0 NOT NULL,
    NOME_ICONE VARCHAR(50) DEFAULT 'FileText' NOT NULL,
    DESC_CATEGORIA TEXT DEFAULT '' NOT NULL,
    INDI_ATIVO VARCHAR(1) DEFAULT 'S' NOT NULL,

    CONSTRAINT PK_CIA_CATEGORIA_PROMPT PRIMARY KEY (ID_CATEGORIA_PROMPT),

    CONSTRAINT UK_CIA_CATEGORIA_PROMPT_NOME UNIQUE (NOME_CATEGORIA),

    CONSTRAINT UK_CIA_CATEGORIA_PROMPT_SLUG UNIQUE (SLUG_CATEGORIA),

    CONSTRAINT CK_CIA_CATEGORIA_PROMPT_ATIVO
        CHECK (
            INDI_ATIVO IN ('S', 'N')
        )
)
;

CREATE INDEX IDX_CIA_CATEGORIA_PROMPT_ATIVO
    ON CIA_CATEGORIA_PROMPT (
        INDI_ATIVO,
        NUMR_ORDEM
    )
;

COMMENT ON TABLE CIA_CATEGORIA_PROMPT IS
'Tabela responsável pelo cadastro das categorias utilizadas para organização dos prompts da plataforma.';

COMMENT ON COLUMN CIA_CATEGORIA_PROMPT.ID_CATEGORIA_PROMPT IS
'Identificador único da categoria de prompt cadastrada.';

COMMENT ON COLUMN CIA_CATEGORIA_PROMPT.NOME_CATEGORIA IS
'Nome da categoria utilizada para classificação dos prompts.';

COMMENT ON COLUMN CIA_CATEGORIA_PROMPT.SLUG_CATEGORIA IS
'Identificador textual único utilizado em URLs e navegação das categorias de prompt.';

COMMENT ON COLUMN CIA_CATEGORIA_PROMPT.CODG_COR IS
'Código hexadecimal da cor utilizada para representação visual da categoria de prompt.';

COMMENT ON COLUMN CIA_CATEGORIA_PROMPT.NUMR_ORDEM IS
'Ordem de exibição da categoria de prompt nas interfaces da plataforma.';

COMMENT ON COLUMN CIA_CATEGORIA_PROMPT.NOME_ICONE IS
'Nome do ícone associado visualmente à categoria de prompt.';

COMMENT ON COLUMN CIA_CATEGORIA_PROMPT.DESC_CATEGORIA IS
'Descrição detalhada da categoria de prompt cadastrada.';

COMMENT ON COLUMN CIA_CATEGORIA_PROMPT.INDI_ATIVO IS
'Indica se a categoria de prompt está ativa na plataforma. S = Sim, N = Não.';
