-- STAT_PUBLICACAO:
--     'RS': Rascunho,
--     'PV': Privado,
--     'AG': Aguardando Aprovação,
--     'PB': Publicado,
--     'ER': Em Revisão,
--     'AR': Arquivado

-- NIVEL_DIFICULDADE:
--     'IN': Iniciante,
--     'IT': Intermediário,
--     'AV': Avançado

CREATE TABLE CIA_PROMPT (
    ID_PROMPT INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    TITULO_PROMPT VARCHAR(300) NOT NULL,
    DESC_PROMPT TEXT DEFAULT '' NOT NULL,
    DESC_CONTEUDO TEXT NOT NULL,
    ID_CATEGORIA_PROMPT INTEGER,
    ID_MODELO INTEGER,
    TAG TEXT DEFAULT '[]' NOT NULL,
    NIVEL_DIFICULDADE VARCHAR(2) DEFAULT 'IN' NOT NULL,
    QTDE_USO INTEGER DEFAULT 0 NOT NULL,
    INFO_VARIAVEL TEXT DEFAULT '[]' NOT NULL,
    ID_USUARIO_AUTOR INTEGER,
    INDI_PUBLICO VARCHAR(1) DEFAULT 'S' NOT NULL,
    INDI_ATIVO VARCHAR(1) DEFAULT 'S' NOT NULL,
    DATA_CRIACAO TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    VALR_MEDIA_AVALIACAO NUMERIC(3,2) DEFAULT 0 NOT NULL,
    QTDE_AVALIACAO INTEGER DEFAULT 0 NOT NULL,
    STAT_PUBLICACAO VARCHAR(2) DEFAULT 'PV' NOT NULL,
    TIPO_ORIGEM VARCHAR(2) DEFAULT 'OF' NOT NULL,
    DATA_SUBMISSAO TIMESTAMPTZ,
    ID_USUARIO_REVISAO INTEGER,
    DATA_REVISAO TIMESTAMPTZ,
    DESC_OBSERVACAO_REVISAO TEXT,
    NOME_AUTOR_ORIGINAL VARCHAR(200),
    QTDE_DENUNCIA INTEGER DEFAULT 0 NOT NULL,
    NUMR_VERSAO INTEGER DEFAULT 1 NOT NULL,
    DESC_OBSERVACAO_SUBMISSAO TEXT,

    CONSTRAINT PK_CIA_PROMPT PRIMARY KEY (ID_PROMPT),

    CONSTRAINT FK_CIA_PROMPT_AUTOR
        FOREIGN KEY (ID_USUARIO_AUTOR)
        REFERENCES CIA_USUARIO (ID_USUARIO)
        ON DELETE SET NULL,

    CONSTRAINT FK_CIA_PROMPT_CATEGORIA
        FOREIGN KEY (ID_CATEGORIA_PROMPT)
        REFERENCES CIA_CATEGORIA_PROMPT (ID_CATEGORIA_PROMPT)
        ON DELETE SET NULL,

    CONSTRAINT FK_CIA_PROMPT_MODELO
        FOREIGN KEY (ID_MODELO)
        REFERENCES CIA_MODELO (ID_MODELO)
        ON DELETE SET NULL,

    CONSTRAINT FK_CIA_PROMPT_REVISAO
        FOREIGN KEY (ID_USUARIO_REVISAO)
        REFERENCES CIA_USUARIO (ID_USUARIO)
        ON DELETE SET NULL,

    CONSTRAINT CK_CIA_PROMPT_DIFICULDADE
        CHECK (
            NIVEL_DIFICULDADE IN (
                'IN',
                'IT',
                'AV'
            )
        ),

    CONSTRAINT CK_CIA_PROMPT_PUBLICO
        CHECK (
            INDI_PUBLICO IN ('S', 'N')
        ),

    CONSTRAINT CK_CIA_PROMPT_ATIVO
        CHECK (
            INDI_ATIVO IN ('S', 'N')
        ),

    CONSTRAINT CK_CIA_PROMPT_PUBLICACAO
        CHECK (
            STAT_PUBLICACAO IN (
                'RS',
                'PV',
                'AG',
                'PB',
                'ER',
                'AR'
            )
        ),

    CONSTRAINT CK_CIA_PROMPT_ORIGEM
        CHECK (
            TIPO_ORIGEM IN (
                'OF',
                'US'
            )
        )
)
;

CREATE INDEX IDX_CIA_PROMPT_AUTOR_ORIGEM
    ON CIA_PROMPT (
        ID_USUARIO_AUTOR,
        TIPO_ORIGEM
    )
;

CREATE INDEX IDX_CIA_PROMPT_AGUARDANDO
    ON CIA_PROMPT (
        STAT_PUBLICACAO,
        DATA_SUBMISSAO
    )
;

CREATE INDEX IDX_CIA_PROMPT_CATEGORIA
    ON CIA_PROMPT (ID_CATEGORIA_PROMPT)
;

CREATE INDEX IDX_CIA_PROMPT_DIFICULDADE
    ON CIA_PROMPT (NIVEL_DIFICULDADE)
;

CREATE INDEX IDX_CIA_PROMPT_REVISAO
    ON CIA_PROMPT (
        STAT_PUBLICACAO,
        QTDE_DENUNCIA
    )
;

CREATE INDEX IDX_CIA_PROMPT_PUBLICACAO ON CIA_PROMPT (STAT_PUBLICACAO);
;

CREATE INDEX IDX_CIA_PROMPT_ORIGEM ON CIA_PROMPT (TIPO_ORIGEM);
;

COMMENT ON TABLE CIA_PROMPT IS
'Tabela responsável pelo cadastro e gerenciamento dos prompts disponibilizados na plataforma.';

COMMENT ON COLUMN CIA_PROMPT.ID_PROMPT IS
'Identificador único do prompt cadastrado.';

COMMENT ON COLUMN CIA_PROMPT.TITULO_PROMPT IS
'Título principal do prompt disponibilizado na plataforma.';

COMMENT ON COLUMN CIA_PROMPT.DESC_PROMPT IS
'Descrição resumida do prompt cadastrado.';

COMMENT ON COLUMN CIA_PROMPT.DESC_CONTEUDO IS
'Conteúdo completo do prompt utilizado pelos usuários.';

COMMENT ON COLUMN CIA_PROMPT.ID_CATEGORIA_PROMPT IS
'Identificador da categoria associada ao prompt.';

COMMENT ON COLUMN CIA_PROMPT.ID_MODELO IS
'Identificador do modelo de inteligência artificial recomendado para utilização do prompt.';

COMMENT ON COLUMN CIA_PROMPT.TAG IS
'Lista de etiquetas utilizadas para categorização e pesquisa do prompt armazenada em formato JSON.';

COMMENT ON COLUMN CIA_PROMPT.NIVEL_DIFICULDADE IS
'Nível de dificuldade do prompt. IN = Iniciante, IT = Intermediário, AV = Avançado.';

COMMENT ON COLUMN CIA_PROMPT.QTDE_USO IS
'Quantidade total de utilizações registradas para o prompt.';

COMMENT ON COLUMN CIA_PROMPT.INFO_VARIAVEL IS
'Lista estruturada das variáveis utilizadas no prompt armazenada em formato JSON.';

COMMENT ON COLUMN CIA_PROMPT.ID_USUARIO_AUTOR IS
'Identificador do usuário autor do prompt cadastrado.';

COMMENT ON COLUMN CIA_PROMPT.INDI_PUBLICO IS
'Indica se o prompt é público para visualização dos usuários. S = Sim, N = Não.';

COMMENT ON COLUMN CIA_PROMPT.INDI_ATIVO IS
'Indica se o prompt está ativo para utilização na plataforma. S = Sim, N = Não.';

COMMENT ON COLUMN CIA_PROMPT.DATA_CRIACAO IS
'Data e hora de criação do registro do prompt.';

COMMENT ON COLUMN CIA_PROMPT.DATA_ATUALIZACAO IS
'Data e hora da última atualização do registro do prompt.';

COMMENT ON COLUMN CIA_PROMPT.VALR_MEDIA_AVALIACAO IS
'Valor médio das avaliações recebidas pelo prompt.';

COMMENT ON COLUMN CIA_PROMPT.QTDE_AVALIACAO IS
'Quantidade total de avaliações registradas para o prompt.';

COMMENT ON COLUMN CIA_PROMPT.STAT_PUBLICACAO IS
'Situação de publicação do prompt. RS = Rascunho, PV = Privado, AG = Aguardando, PB = Público, ER = Em Revisão, AR = Arquivado.';

COMMENT ON COLUMN CIA_PROMPT.TIPO_ORIGEM IS
'Origem do prompt cadastrado. OF = Oficial, US = Usuário.';

COMMENT ON COLUMN CIA_PROMPT.DATA_SUBMISSAO IS
'Data e hora da submissão do prompt para publicação ou revisão.';

COMMENT ON COLUMN CIA_PROMPT.ID_USUARIO_REVISAO IS
'Identificador do usuário responsável pela revisão do prompt.';

COMMENT ON COLUMN CIA_PROMPT.DATA_REVISAO IS
'Data e hora da revisão realizada no prompt.';

COMMENT ON COLUMN CIA_PROMPT.DESC_OBSERVACAO_REVISAO IS
'Observações registradas durante o processo de revisão do prompt.';

COMMENT ON COLUMN CIA_PROMPT.NOME_AUTOR_ORIGINAL IS
'Nome do autor original do prompt, quando aplicável.';

COMMENT ON COLUMN CIA_PROMPT.QTDE_DENUNCIA IS
'Quantidade total de denúncias registradas para o prompt.';

COMMENT ON COLUMN CIA_PROMPT.NUMR_VERSAO IS
'Número atual da versão do prompt.';

COMMENT ON COLUMN CIA_PROMPT.DESC_OBSERVACAO_SUBMISSAO IS
'Observações informadas durante a submissão do prompt.';

CREATE OR REPLACE FUNCTION trg_bu_cia_prompt_fn()
RETURNS TRIGGER AS $$
BEGIN
  NEW.data_atualizacao = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_bu_cia_prompt
  BEFORE UPDATE ON cia_prompt
  FOR EACH ROW EXECUTE FUNCTION trg_bu_cia_prompt_fn();
