CREATE TABLE CIA_FORNECEDOR (
    ID_FORNECEDOR INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    NOME_FORNECEDOR VARCHAR(200) NOT NULL,

    CONSTRAINT PK_CIA_FORNECEDOR PRIMARY KEY (ID_FORNECEDOR),

    CONSTRAINT UK_CIA_FORNECEDOR_NOME  UNIQUE (NOME_FORNECEDOR)
)
;

COMMENT ON TABLE CIA_FORNECEDOR IS
'Tabela responsável pelo cadastro dos forcedores de modelos e serviços de inteligência artificial utilizados pela plataforma.';

COMMENT ON COLUMN CIA_FORNECEDOR.ID_FORNECEDOR IS
'Identificador único do forcedor cadastrado.';

COMMENT ON COLUMN CIA_FORNECEDOR.NOME_FORNECEDOR IS
'Nome do forcedor responsável pelos modelos ou serviços de inteligência artificial.';
