
    CREATE TABLE IF NOT EXISTS app_features (
      key        TEXT PRIMARY KEY,
      name       TEXT NOT NULL,
      description TEXT NULL,
      area       TEXT NOT NULL,
      menu_label TEXT NULL,
      menu_path  TEXT NULL,
      sort_order INTEGER NOT NULL DEFAULT 0,
      is_active  BOOLEAN NOT NULL DEFAULT TRUE,
      is_system  BOOLEAN NOT NULL DEFAULT TRUE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS role_feature_permissions (
      role        user_role NOT NULL,
      feature_key TEXT NOT NULL REFERENCES app_features(key) ON DELETE CASCADE,
      is_enabled  BOOLEAN NOT NULL DEFAULT FALSE,
      created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      PRIMARY KEY (role, feature_key)
    );

    CREATE INDEX IF NOT EXISTS idx_app_features_area_sort ON app_features(area, sort_order);
    CREATE INDEX IF NOT EXISTS idx_role_feature_permissions_feature ON role_feature_permissions(feature_key);

    INSERT INTO app_features (key, name, area, description, menu_label, menu_path, sort_order)
    VALUES
      ('app.home.view', 'Início', 'Geral', 'Início da aplicação', 'Início', '/', '10'),
      ('models.catalog.view', 'Catálogo de Modelos', 'Modelos', 'Catálogo público de modelos', 'Catálogo', '/modelos', '100'),
      ('models.my_access.view', 'Meus Acessos a Modelos', 'Modelos', 'Solicitações e credenciais de acesso a modelos', 'Meus Acessos', '/meus-acessos-modelos', '110'),
      ('prompts.library.view', 'Biblioteca de Prompts', 'Prompts', 'Biblioteca pública de prompts', 'Biblioteca', '/prompts', '200'),
      ('prompts.my.view', 'Meus Prompts', 'Prompts', 'Prompts criados pelo usuário', 'Meus Prompts', '/meus-prompts', '210'),
      ('mcp.catalog.view', 'Catálogo MCP', 'MCP', 'Catálogo público de servidores MCP', 'Catálogo MCP', '/mcp', '300'),
      ('docs.portal.view', 'Documentação', 'Documentação', 'Portal de documentação', 'Documentação', '/docs', '400'),
      ('news.portal.view', 'Notícias', 'Comunicação', 'Notícias publicadas', 'Notícias', '/noticias', '500'),
      ('admin.dashboard.view', 'Dashboard administrativo', 'Administração', 'Visão geral administrativa', 'Dashboard', '/admin', '1000'),
      ('admin.users.manage', 'Usuários', 'Administração', 'Gerenciamento de usuários', 'Usuários', '/admin/usuarios', '1010'),
      ('admin.models.manage', 'Modelos', 'Administração', 'Gerenciamento de modelos', 'Modelos', '/admin/modelos', '1020'),
      ('admin.model_access.manage', 'Acesso a Modelos', 'Administração', 'Curadoria de acessos a modelos', 'Acesso a Modelos', '/admin/acessos-modelos', '1030'),
      ('admin.prompts.manage', 'Prompts', 'Administração', 'Gerenciamento de prompts oficiais', 'Prompts', '/admin/prompts', '1040'),
      ('admin.prompt_curation.manage', 'Curadoria de Prompts', 'Administração', 'Curadoria de prompts da comunidade', 'Curadoria de Prompts', '/admin/curation', '1050'),
      ('admin.mcp.manage', 'Catálogo MCP', 'Administração', 'Gerenciamento do catálogo MCP', 'Catálogo MCP', '/admin/mcp', '1060'),
      ('admin.docs.manage', 'Documentação', 'Administração', 'Gerenciamento da documentação', 'Documentação', '/admin/docs', '1070'),
      ('admin.news.manage', 'Notícias', 'Administração', 'Gerenciamento de notícias', 'Notícias', '/admin/noticias', '1080'),
      ('admin.notifications.manage', 'Notificações', 'Administração', 'Gerenciamento de notificações', 'Notificações', '/admin/notificacoes', '1090'),
      ('admin.audit.view', 'Auditoria', 'Administração', 'Consulta de auditoria', 'Auditoria', '/admin/auditoria', '1100'),
      ('admin.permissions.manage', 'Permissões por Papel', 'Administração', 'Controle administrativo de funcionalidades por papel', 'Permissões por Papel', '/admin/permissoes', '1110')
    ON CONFLICT (key) DO UPDATE SET
      name = EXCLUDED.name,
      area = EXCLUDED.area,
      description = EXCLUDED.description,
      menu_label = EXCLUDED.menu_label,
      menu_path = EXCLUDED.menu_path,
      sort_order = EXCLUDED.sort_order,
      updated_at = NOW();

    INSERT INTO role_feature_permissions (role, feature_key, is_enabled)
    VALUES
      ('admin'::user_role, 'app.home.view', true),
      ('admin'::user_role, 'models.catalog.view', true),
      ('admin'::user_role, 'models.my_access.view', true),
      ('admin'::user_role, 'prompts.library.view', true),
      ('admin'::user_role, 'prompts.my.view', true),
      ('admin'::user_role, 'mcp.catalog.view', true),
      ('admin'::user_role, 'docs.portal.view', true),
      ('admin'::user_role, 'news.portal.view', true),
      ('admin'::user_role, 'admin.dashboard.view', true),
      ('admin'::user_role, 'admin.users.manage', true),
      ('admin'::user_role, 'admin.models.manage', true),
      ('admin'::user_role, 'admin.model_access.manage', true),
      ('admin'::user_role, 'admin.prompts.manage', true),
      ('admin'::user_role, 'admin.prompt_curation.manage', true),
      ('admin'::user_role, 'admin.mcp.manage', true),
      ('admin'::user_role, 'admin.docs.manage', true),
      ('admin'::user_role, 'admin.news.manage', true),
      ('admin'::user_role, 'admin.notifications.manage', true),
      ('admin'::user_role, 'admin.audit.view', true),
      ('admin'::user_role, 'admin.permissions.manage', true),
      ('gestor'::user_role, 'app.home.view', true),
      ('gestor'::user_role, 'models.catalog.view', true),
      ('gestor'::user_role, 'models.my_access.view', true),
      ('gestor'::user_role, 'prompts.library.view', true),
      ('gestor'::user_role, 'prompts.my.view', true),
      ('gestor'::user_role, 'mcp.catalog.view', true),
      ('gestor'::user_role, 'docs.portal.view', true),
      ('gestor'::user_role, 'news.portal.view', true),
      ('gestor'::user_role, 'admin.dashboard.view', true),
      ('gestor'::user_role, 'admin.users.manage', false),
      ('gestor'::user_role, 'admin.models.manage', true),
      ('gestor'::user_role, 'admin.model_access.manage', false),
      ('gestor'::user_role, 'admin.prompts.manage', true),
      ('gestor'::user_role, 'admin.prompt_curation.manage', true),
      ('gestor'::user_role, 'admin.mcp.manage', true),
      ('gestor'::user_role, 'admin.docs.manage', true),
      ('gestor'::user_role, 'admin.news.manage', true),
      ('gestor'::user_role, 'admin.notifications.manage', false),
      ('gestor'::user_role, 'admin.audit.view', false),
      ('gestor'::user_role, 'admin.permissions.manage', false),
      ('curador'::user_role, 'app.home.view', true),
      ('curador'::user_role, 'models.catalog.view', true),
      ('curador'::user_role, 'models.my_access.view', true),
      ('curador'::user_role, 'prompts.library.view', true),
      ('curador'::user_role, 'prompts.my.view', true),
      ('curador'::user_role, 'mcp.catalog.view', true),
      ('curador'::user_role, 'docs.portal.view', true),
      ('curador'::user_role, 'news.portal.view', true),
      ('curador'::user_role, 'admin.dashboard.view', false),
      ('curador'::user_role, 'admin.users.manage', false),
      ('curador'::user_role, 'admin.models.manage', false),
      ('curador'::user_role, 'admin.model_access.manage', false),
      ('curador'::user_role, 'admin.prompts.manage', false),
      ('curador'::user_role, 'admin.prompt_curation.manage', true),
      ('curador'::user_role, 'admin.mcp.manage', false),
      ('curador'::user_role, 'admin.docs.manage', false),
      ('curador'::user_role, 'admin.news.manage', false),
      ('curador'::user_role, 'admin.notifications.manage', false),
      ('curador'::user_role, 'admin.audit.view', false),
      ('curador'::user_role, 'admin.permissions.manage', false),
      ('curador_modelos'::user_role, 'app.home.view', true),
      ('curador_modelos'::user_role, 'models.catalog.view', true),
      ('curador_modelos'::user_role, 'models.my_access.view', true),
      ('curador_modelos'::user_role, 'prompts.library.view', true),
      ('curador_modelos'::user_role, 'prompts.my.view', true),
      ('curador_modelos'::user_role, 'mcp.catalog.view', true),
      ('curador_modelos'::user_role, 'docs.portal.view', true),
      ('curador_modelos'::user_role, 'news.portal.view', true),
      ('curador_modelos'::user_role, 'admin.dashboard.view', false),
      ('curador_modelos'::user_role, 'admin.users.manage', false),
      ('curador_modelos'::user_role, 'admin.models.manage', false),
      ('curador_modelos'::user_role, 'admin.model_access.manage', true),
      ('curador_modelos'::user_role, 'admin.prompts.manage', false),
      ('curador_modelos'::user_role, 'admin.prompt_curation.manage', false),
      ('curador_modelos'::user_role, 'admin.mcp.manage', false),
      ('curador_modelos'::user_role, 'admin.docs.manage', false),
      ('curador_modelos'::user_role, 'admin.news.manage', false),
      ('curador_modelos'::user_role, 'admin.notifications.manage', false),
      ('curador_modelos'::user_role, 'admin.audit.view', false),
      ('curador_modelos'::user_role, 'admin.permissions.manage', false),
      ('servidor'::user_role, 'app.home.view', true),
      ('servidor'::user_role, 'models.catalog.view', true),
      ('servidor'::user_role, 'models.my_access.view', true),
      ('servidor'::user_role, 'prompts.library.view', true),
      ('servidor'::user_role, 'prompts.my.view', true),
      ('servidor'::user_role, 'mcp.catalog.view', true),
      ('servidor'::user_role, 'docs.portal.view', true),
      ('servidor'::user_role, 'news.portal.view', true),
      ('servidor'::user_role, 'admin.dashboard.view', false),
      ('servidor'::user_role, 'admin.users.manage', false),
      ('servidor'::user_role, 'admin.models.manage', false),
      ('servidor'::user_role, 'admin.model_access.manage', false),
      ('servidor'::user_role, 'admin.prompts.manage', false),
      ('servidor'::user_role, 'admin.prompt_curation.manage', false),
      ('servidor'::user_role, 'admin.mcp.manage', false),
      ('servidor'::user_role, 'admin.docs.manage', false),
      ('servidor'::user_role, 'admin.news.manage', false),
      ('servidor'::user_role, 'admin.notifications.manage', false),
      ('servidor'::user_role, 'admin.audit.view', false),
      ('servidor'::user_role, 'admin.permissions.manage', false)
    ON CONFLICT (role, feature_key) DO UPDATE SET
      is_enabled = EXCLUDED.is_enabled,
      updated_at = NOW();
  