CREATE TABLE CIA_CATEGORIA_MODELO (
    ID_CATEGORIA_MODELO NUMBER(10) NOT NULL,
    NOME_CATEGORIA_MODELO VARCHAR2(100 CHAR) NOT NULL,

    CONSTRAINT PK_CIA_CATEGORIA_MODELO PRIMARY KEY (ID_CATEGORIA_MODELO)
)

COMMENT ON TABLE CIA_CATEGORIA_MODELO IS
'Tabela responsável pelo cadastro das categorias de modelos de inteligência artificial disponíveis na plataforma.'

COMMENT ON COLUMN CIA_CATEGORIA_MODELO.ID_CATEGORIA_MODELO IS
'Identificador único da categoria do modelo de inteligência artificial.'

COMMENT ON COLUMN CIA_CATEGORIA_MODELO.NOME_CATEGORIA_MODELO IS
'Nome da categoria utilizada para classificação dos modelos de inteligência artificial.'


CREATE SEQUENCE SEQ_CIA_CATEGORIA_MODELO  START WITH 1 INCREMENT BY 1  NOCACHE NOCYCLE

CREATE OR REPLACE TRIGGER TRG_BI_CIA_CATEGORIA_MODELO
BEFORE INSERT ON CIA_CATEGORIA_MODELO
FOR EACH ROW
BEGIN
    IF :NEW.ID_CATEGORIA_MODELO IS NULL THEN
        SELECT SEQ_CIA_CATEGORIA_MODELO.NEXTVAL
          INTO :NEW.ID_CATEGORIA_MODELO
          FROM DUAL
    END IF
END


INSERT INTO CIA_CATEGORIA_MODELO (NOME_CATEGORIA_MODELO) VALUES ('Texto')
INSERT INTO CIA_CATEGORIA_MODELO (NOME_CATEGORIA_MODELO) VALUES ('Codigo')
INSERT INTO CIA_CATEGORIA_MODELO (NOME_CATEGORIA_MODELO) VALUES ('Visao')
INSERT INTO CIA_CATEGORIA_MODELO (NOME_CATEGORIA_MODELO) VALUES ('Multimodal')
INSERT INTO CIA_CATEGORIA_MODELO (NOME_CATEGORIA_MODELO) VALUES ('Embeddings')
