CREATE TABLE CIA_LOG_AUDITORIA (
    ID_LOG_AUDITORIA NUMBER(10) NOT NULL,
    ID_USUARIO NUMBER(10),
    ACAO_AUDITORIA VARCHAR2(50 CHAR) NOT NULL,
    NOME_ENTIDADE VARCHAR2(100 CHAR) NOT NULL,
    ID_ENTIDADE NUMBER(10),
    INFO_METADADO CLOB,
    INFO_ENDERECO_IP VARCHAR2(45 CHAR),
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    INFO_USER_AGENT CLOB,

    CONSTRAINT PK_CIA_LOG_AUDITORIA PRIMARY KEY (ID_LOG_AUDITORIA),

    CONSTRAINT FK_CIA_LOG_AUDITORIA_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES CIA_USUARIO (ID_USUARIO) ON DELETE SET NULL
)


CREATE SEQUENCE SEQ_CIA_LOG_AUDITORIA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_LOG_AUDITORIA
BEFORE INSERT ON CIA_LOG_AUDITORIA
FOR EACH ROW
BEGIN
    IF :NEW.ID_LOG_AUDITORIA IS NULL THEN
        SELECT SEQ_CIA_LOG_AUDITORIA.NEXTVAL
          INTO :NEW.ID_LOG_AUDITORIA
          FROM DUAL
    END IF
END

CREATE INDEX IDX_CIA_LOG_AUD_ENTIDADE ON CIA_LOG_AUDITORIA (NOME_ENTIDADE, ID_ENTIDADE)

CREATE INDEX IDX_CIA_LOG_AUD_USUARIO ON CIA_LOG_AUDITORIA (ID_USUARIO, DATA_CRIACAO)

COMMENT ON TABLE CIA_LOG_AUDITORIA IS
'Tabela responsável pelo armazenamento dos registros de auditoria das operações realizadas na aplicação.'

COMMENT ON COLUMN CIA_LOG_AUDITORIA.ID_LOG_AUDITORIA IS
'Identificador único do registro de auditoria.'

COMMENT ON COLUMN CIA_LOG_AUDITORIA.ID_USUARIO IS
'Identificador do usuário responsável pela operação auditada.'

COMMENT ON COLUMN CIA_LOG_AUDITORIA.ACAO_AUDITORIA IS
'Ação executada pelo usuário na aplicação.'

COMMENT ON COLUMN CIA_LOG_AUDITORIA.NOME_ENTIDADE IS
'Nome da entidade ou recurso afetado pela operação auditada.'

COMMENT ON COLUMN CIA_LOG_AUDITORIA.ID_ENTIDADE IS
'Identificador do registro relacionado à operação auditada.'

COMMENT ON COLUMN CIA_LOG_AUDITORIA.INFO_METADADO IS
'Informações complementares e metadados relacionados ao evento de auditoria armazenados em formato JSON.'

COMMENT ON COLUMN CIA_LOG_AUDITORIA.INFO_ENDERECO_IP IS
'Endereço IP de origem da requisição realizada pelo usuário.'

COMMENT ON COLUMN CIA_LOG_AUDITORIA.DATA_CRIACAO IS
'Data e hora de criação do registro de auditoria.'

COMMENT ON COLUMN CIA_LOG_AUDITORIA.INFO_USER_AGENT IS
'Informações do agente de navegação utilizado pelo usuário durante a operação.'
