CREATE TABLE CIA_BANCO_QUESTAO (
    ID_BANCO_QUESTAO NUMBER(10) NOT NULL,
    ID_METRICA NUMBER(10),
    JSON_PERGUNTA CLOB NOT NULL,
    JSON_GABARITO CLOB NOT NULL,

    CONSTRAINT PK_CIA_BANCO_QUESTAO PRIMARY KEY (ID_BANCO_QUESTAO),

    CONSTRAINT FK_CIA_BANCO_QUESTAO_METRICA FOREIGN KEY (ID_METRICA)
        REFERENCES CIA_METRICA (ID_METRICA) ON DELETE SET NULL
)

CREATE SEQUENCE SEQ_CIA_BANCO_QUESTAO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_BANCO_QUESTAO
BEFORE INSERT ON CIA_BANCO_QUESTAO
FOR EACH ROW
BEGIN
    IF :NEW.ID_BANCO_QUESTAO IS NULL THEN
        SELECT SEQ_CIA_BANCO_QUESTAO.NEXTVAL
          INTO :NEW.ID_BANCO_QUESTAO
          FROM DUAL
    END IF
END


CREATE UNIQUE INDEX UK_CIA_BANCO_QUESTAO ON CIA_BANCO_QUESTAO (ID_BANCO_QUESTAO, ID_METRICA)


COMMENT ON TABLE CIA_BANCO_QUESTAO IS
'Tabela responsável pelo armazenamento das questões vinculadas às métricas de avaliação da plataforma.'

COMMENT ON COLUMN CIA_BANCO_QUESTAO.ID_BANCO_QUESTAO IS
'Identificador único da questão cadastrada no banco de questões.'

COMMENT ON COLUMN CIA_BANCO_QUESTAO.ID_METRICA IS
'Identificador da métrica associada à questão cadastrada.'

COMMENT ON COLUMN CIA_BANCO_QUESTAO.JSON_PERGUNTA IS
'Conteúdo estruturado da pergunta armazenado em formato JSON.'

COMMENT ON COLUMN CIA_BANCO_QUESTAO.JSON_GABARITO IS
'Conteúdo estruturado do gabarito da questão armazenado em formato JSON.'
