CREATE TABLE CIA_DOCUMENTACAO_ARTIGO (
    ID_DOCUMENTACAO_ARTIGO NUMBER(10) NOT NULL,
    ID_DOCUMENTACAO_SECAO NUMBER(10),
    NOME_ARTIGO VARCHAR2(300 CHAR) NOT NULL,
    NOME_CURTO VARCHAR2(300 CHAR) NOT NULL,
    DESC_CONTEUDO CLOB DEFAULT '' NOT NULL,
    QTDE_TEMPO_LEITURA NUMBER(10) DEFAULT 1 NOT NULL,
    NUMR_ORDEM NUMBER(10) DEFAULT 0 NOT NULL,
    CODG_USUARIO_AUTOR NUMBER(10),
    INDI_PUBLICADO VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
    INDI_ATIVO VARCHAR2(1 CHAR) DEFAULT 'S' NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_CIA_DOCUMENTACAO_ARTIGO PRIMARY KEY (ID_DOCUMENTACAO_ARTIGO),
    CONSTRAINT UK_CIA_ARTIGO_DOC_SLUG UNIQUE (NOME_CURTO),

    CONSTRAINT FK_CIA_ARTIGO_DOC_AUTOR
        FOREIGN KEY (CODG_USUARIO_AUTOR)
        REFERENCES USUARIO_SISTEMA (ID_USUARIO)
        ON DELETE SET NULL,

    CONSTRAINT FK_CIA_ARTIGO_DOC_SECAO
        FOREIGN KEY (ID_DOCUMENTACAO_SECAO)
        REFERENCES CIA_DOCUMENTACAO_SECAO (ID_DOCUMENTACAO_SECAO)
        ON DELETE CASCADE,

    CONSTRAINT CK_CIA_ARTIGO_DOC_PUBLIC CHECK (INDI_PUBLICADO IN ('S', 'N')),

    CONSTRAINT CK_CIA_ARTIGO_DOC_ATIVO CHECK (INDI_ATIVO IN ('S', 'N'))
)


CREATE SEQUENCE SEQ_CIA_DOCUMENTACAO_ARTIGO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_ARTIGO_DOC
BEFORE INSERT ON CIA_DOCUMENTACAO_ARTIGO
FOR EACH ROW
BEGIN
    IF :NEW.ID_DOCUMENTACAO_ARTIGO IS NULL THEN
        SELECT SEQ_CIA_DOCUMENTACAO_ARTIGO.NEXTVAL
          INTO :NEW.ID_DOCUMENTACAO_ARTIGO
          FROM DUAL
    END IF
END


CREATE OR REPLACE TRIGGER TRG_BU_CIA_ARTIGO_DOC
BEFORE UPDATE ON CIA_DOCUMENTACAO_ARTIGO
FOR EACH ROW
BEGIN
    :NEW.DATA_ATUALIZACAO := CURRENT_TIMESTAMP
END


CREATE INDEX IDX_CIA_ARTIGO_DOC_SECAO  ON CIA_DOCUMENTACAO_ARTIGO (ID_DOCUMENTACAO_SECAO)

CREATE INDEX IDX_CIA_ARTIGO_DOC_SLUG ON CIA_DOCUMENTACAO_ARTIGO (NOME_CURTO)


COMMENT ON TABLE CIA_DOCUMENTACAO_ARTIGO IS
'Tabela responsável pelo armazenamento dos artigos de documentação disponíveis na plataforma.'

COMMENT ON COLUMN CIA_DOCUMENTACAO_ARTIGO.ID_DOCUMENTACAO_ARTIGO IS
'Identificador único do artigo de documentação.'

COMMENT ON COLUMN CIA_DOCUMENTACAO_ARTIGO.ID_DOCUMENTACAO_SECAO IS
'Identificador da seção de documentação associada ao artigo.'

COMMENT ON COLUMN CIA_DOCUMENTACAO_ARTIGO.NOME_ARTIGO IS
'Título do artigo de documentação.'

COMMENT ON COLUMN CIA_DOCUMENTACAO_ARTIGO.NOME_CURTO IS
'Identificador textual único utilizado em URLs e navegação da documentação.'

COMMENT ON COLUMN CIA_DOCUMENTACAO_ARTIGO.DESC_CONTEUDO IS
'Conteúdo textual completo do artigo de documentação.'

COMMENT ON COLUMN CIA_DOCUMENTACAO_ARTIGO.QTDE_TEMPO_LEITURA IS
'Quantidade estimada de minutos necessários para leitura do artigo.'

COMMENT ON COLUMN CIA_DOCUMENTACAO_ARTIGO.NUMR_ORDEM IS
'Ordem de exibição do artigo dentro da seção de documentação.'

COMMENT ON COLUMN CIA_DOCUMENTACAO_ARTIGO.CODG_USUARIO_AUTOR IS
'Identificador do usuário responsável pela autoria do artigo.'

COMMENT ON COLUMN CIA_DOCUMENTACAO_ARTIGO.INDI_PUBLICADO IS
'Indica se o artigo está publicado para visualização. S = Sim, N = Não.'

COMMENT ON COLUMN CIA_DOCUMENTACAO_ARTIGO.INDI_ATIVO IS
'Indica se o artigo está ativo na plataforma. S = Sim, N = Não.'

COMMENT ON COLUMN CIA_DOCUMENTACAO_ARTIGO.DATA_CRIACAO IS
'Data e hora de criação do registro do artigo.'

COMMENT ON COLUMN CIA_DOCUMENTACAO_ARTIGO.DATA_ATUALIZACAO IS
'Data e hora da última atualização do registro do artigo.'
