CREATE TABLE CIA_ARTIGO_DOCUMENTACAO (
    ID_ARTIGO_DOCUMENTACAO NUMBER(10) NOT NULL,
    ID_SECAO_DOCUMENTACAO NUMBER(10),
    NOME_ARTIGO VARCHAR2(300 CHAR) NOT NULL,
    SLUG_ARTIGO VARCHAR2(300 CHAR) NOT NULL,
    DESC_CONTEUDO CLOB DEFAULT '' NOT NULL,
    QTDE_TEMPO_LEITURA NUMBER(10) DEFAULT 1 NOT NULL,
    NUMR_ORDEM NUMBER(10) DEFAULT 0 NOT NULL,
    ID_USUARIO_AUTOR NUMBER(10),
    INDI_PUBLICADO VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
    INDI_ATIVO VARCHAR2(1 CHAR) DEFAULT 'S' NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_CIA_ARTIGO_DOCUMENTACAO PRIMARY KEY (ID_ARTIGO_DOCUMENTACAO),
    CONSTRAINT UK_CIA_ARTIGO_DOC_SLUG UNIQUE (SLUG_ARTIGO),

    CONSTRAINT FK_CIA_ARTIGO_DOC_AUTOR
        FOREIGN KEY (ID_USUARIO_AUTOR)
        REFERENCES CIA_USUARIO (ID_USUARIO)
        ON DELETE SET NULL,

    CONSTRAINT FK_CIA_ARTIGO_DOC_SECAO
        FOREIGN KEY (ID_SECAO_DOCUMENTACAO)
        REFERENCES CIA_SECAO_DOCUMENTACAO (ID_SECAO_DOCUMENTACAO)
        ON DELETE CASCADE,

    CONSTRAINT CK_CIA_ARTIGO_DOC_PUBLIC CHECK (INDI_PUBLICADO IN ('S', 'N')),

    CONSTRAINT CK_CIA_ARTIGO_DOC_ATIVO CHECK (INDI_ATIVO IN ('S', 'N'))
)


CREATE SEQUENCE SEQ_CIA_ARTIGO_DOCUMENTACAO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_ARTIGO_DOC
BEFORE INSERT ON CIA_ARTIGO_DOCUMENTACAO
FOR EACH ROW
BEGIN
    IF :NEW.ID_ARTIGO_DOCUMENTACAO IS NULL THEN
        SELECT SEQ_CIA_ARTIGO_DOCUMENTACAO.NEXTVAL
          INTO :NEW.ID_ARTIGO_DOCUMENTACAO
          FROM DUAL
    END IF
END


CREATE OR REPLACE TRIGGER TRG_BU_CIA_ARTIGO_DOC
BEFORE UPDATE ON CIA_ARTIGO_DOCUMENTACAO
FOR EACH ROW
BEGIN
    :NEW.DATA_ATUALIZACAO := CURRENT_TIMESTAMP
END


CREATE INDEX IDX_CIA_ARTIGO_DOC_SECAO  ON CIA_ARTIGO_DOCUMENTACAO (ID_SECAO_DOCUMENTACAO)

CREATE INDEX IDX_CIA_ARTIGO_DOC_SLUG ON CIA_ARTIGO_DOCUMENTACAO (SLUG_ARTIGO)


COMMENT ON TABLE CIA_ARTIGO_DOCUMENTACAO IS
'Tabela responsável pelo armazenamento dos artigos de documentação disponíveis na plataforma.'

COMMENT ON COLUMN CIA_ARTIGO_DOCUMENTACAO.ID_ARTIGO_DOCUMENTACAO IS
'Identificador único do artigo de documentação.'

COMMENT ON COLUMN CIA_ARTIGO_DOCUMENTACAO.ID_SECAO_DOCUMENTACAO IS
'Identificador da seção de documentação associada ao artigo.'

COMMENT ON COLUMN CIA_ARTIGO_DOCUMENTACAO.NOME_ARTIGO IS
'Título do artigo de documentação.'

COMMENT ON COLUMN CIA_ARTIGO_DOCUMENTACAO.SLUG_ARTIGO IS
'Identificador textual único utilizado em URLs e navegação da documentação.'

COMMENT ON COLUMN CIA_ARTIGO_DOCUMENTACAO.DESC_CONTEUDO IS
'Conteúdo textual completo do artigo de documentação.'

COMMENT ON COLUMN CIA_ARTIGO_DOCUMENTACAO.QTDE_TEMPO_LEITURA IS
'Quantidade estimada de minutos necessários para leitura do artigo.'

COMMENT ON COLUMN CIA_ARTIGO_DOCUMENTACAO.NUMR_ORDEM IS
'Ordem de exibição do artigo dentro da seção de documentação.'

COMMENT ON COLUMN CIA_ARTIGO_DOCUMENTACAO.ID_USUARIO_AUTOR IS
'Identificador do usuário responsável pela autoria do artigo.'

COMMENT ON COLUMN CIA_ARTIGO_DOCUMENTACAO.INDI_PUBLICADO IS
'Indica se o artigo está publicado para visualização. S = Sim, N = Não.'

COMMENT ON COLUMN CIA_ARTIGO_DOCUMENTACAO.INDI_ATIVO IS
'Indica se o artigo está ativo na plataforma. S = Sim, N = Não.'

COMMENT ON COLUMN CIA_ARTIGO_DOCUMENTACAO.DATA_CRIACAO IS
'Data e hora de criação do registro do artigo.'

COMMENT ON COLUMN CIA_ARTIGO_DOCUMENTACAO.DATA_ATUALIZACAO IS
'Data e hora da última atualização do registro do artigo.'
