CREATE TABLE CIA_SECAO_DOCUMENTACAO (
    ID_SECAO_DOCUMENTACAO NUMBER(10) NOT NULL,
    NOME_SECAO VARCHAR2(200 CHAR) NOT NULL,
    SLUG_SECAO VARCHAR2(200 CHAR) NOT NULL,
    NUMR_ORDEM NUMBER(10) DEFAULT 0 NOT NULL,
    ID_SECAO_PAI NUMBER(10),
    INDI_ATIVO VARCHAR2(1 CHAR) DEFAULT 'S' NOT NULL,

    CONSTRAINT PK_CIA_SECAO_DOCUMENTACAO PRIMARY KEY (ID_SECAO_DOCUMENTACAO),

    CONSTRAINT UK_CIA_SECAO_DOC_SLUG UNIQUE (SLUG_SECAO),

    CONSTRAINT FK_CIA_SECAO_DOC_PAI FOREIGN KEY (ID_SECAO_PAI)
        REFERENCES CIA_SECAO_DOCUMENTACAO (ID_SECAO_DOCUMENTACAO) ON DELETE CASCADE,

    CONSTRAINT CK_CIA_SECAO_DOC_ATIVO CHECK (INDI_ATIVO IN ('S', 'N'))
)


CREATE SEQUENCE SEQ_CIA_SECAO_DOCUMENTACAO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_SECAO_DOC
BEFORE INSERT ON CIA_SECAO_DOCUMENTACAO
FOR EACH ROW
BEGIN
    IF :NEW.ID_SECAO_DOCUMENTACAO IS NULL THEN
        SELECT SEQ_CIA_SECAO_DOCUMENTACAO.NEXTVAL
          INTO :NEW.ID_SECAO_DOCUMENTACAO
          FROM DUAL
    END IF
END

CREATE INDEX IDX_CIA_SECAO_DOC_PAI  ON CIA_SECAO_DOCUMENTACAO (ID_SECAO_PAI)

COMMENT ON TABLE CIA_SECAO_DOCUMENTACAO IS
'Tabela responsável pelo cadastro das seções de documentação disponíveis na plataforma.'

COMMENT ON COLUMN CIA_SECAO_DOCUMENTACAO.ID_SECAO_DOCUMENTACAO IS
'Identificador único da seção de documentação.'

COMMENT ON COLUMN CIA_SECAO_DOCUMENTACAO.NOME_SECAO IS
'Nome da seção de documentação exibida na plataforma.'

COMMENT ON COLUMN CIA_SECAO_DOCUMENTACAO.SLUG_SECAO IS
'Identificador textual único utilizado em URLs e navegação das seções de documentação.'

COMMENT ON COLUMN CIA_SECAO_DOCUMENTACAO.NUMR_ORDEM IS
'Ordem de exibição da seção de documentação nas interfaces da plataforma.'

COMMENT ON COLUMN CIA_SECAO_DOCUMENTACAO.ID_SECAO_PAI IS
'Identificador da seção superior vinculada hierarquicamente à seção atual.'

COMMENT ON COLUMN CIA_SECAO_DOCUMENTACAO.INDI_ATIVO IS
'Indica se a seção de documentação está ativa na plataforma. S = Sim, N = Não.'
