CREATE TABLE CIA_DOCUMENTACAO_SECAO (
    ID_DOCUMENTACAO_SECAO NUMBER(10) NOT NULL,
    NOME_SECAO VARCHAR2(200 CHAR) NOT NULL,
    NOME_CURTO VARCHAR2(200 CHAR) NOT NULL,
    NUMR_ORDEM NUMBER(10) DEFAULT 0 NOT NULL,
    CODG_SECAO_PAI NUMBER(10),
    INDI_ATIVO VARCHAR2(1 CHAR) DEFAULT 'S' NOT NULL,

    CONSTRAINT PK_CIA_DOCUMENTACAO_SECAO PRIMARY KEY (ID_DOCUMENTACAO_SECAO),

    CONSTRAINT UK_CIA_SECAO_DOC_SLUG UNIQUE (NOME_CURTO),

    CONSTRAINT FK_CIA_SECAO_DOC_PAI FOREIGN KEY (CODG_SECAO_PAI)
        REFERENCES CIA_DOCUMENTACAO_SECAO (ID_DOCUMENTACAO_SECAO) ON DELETE CASCADE,

    CONSTRAINT CK_CIA_SECAO_DOC_ATIVO CHECK (INDI_ATIVO IN ('S', 'N'))
)


CREATE SEQUENCE SEQ_CIA_DOCUMENTACAO_SECAO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_SECAO_DOC
BEFORE INSERT ON CIA_DOCUMENTACAO_SECAO
FOR EACH ROW
BEGIN
    IF :NEW.ID_DOCUMENTACAO_SECAO IS NULL THEN
        SELECT SEQ_CIA_DOCUMENTACAO_SECAO.NEXTVAL
          INTO :NEW.ID_DOCUMENTACAO_SECAO
          FROM DUAL
    END IF
END

CREATE INDEX IDX_CIA_SECAO_DOC_PAI  ON CIA_DOCUMENTACAO_SECAO (CODG_SECAO_PAI)

COMMENT ON TABLE CIA_DOCUMENTACAO_SECAO IS
'Tabela responsável pelo cadastro das seções de documentação disponíveis na plataforma.'

COMMENT ON COLUMN CIA_DOCUMENTACAO_SECAO.ID_DOCUMENTACAO_SECAO IS
'Identificador único da seção de documentação.'

COMMENT ON COLUMN CIA_DOCUMENTACAO_SECAO.NOME_SECAO IS
'Nome da seção de documentação exibida na plataforma.'

COMMENT ON COLUMN CIA_DOCUMENTACAO_SECAO.NOME_CURTO IS
'Identificador textual único utilizado em URLs e navegação das seções de documentação.'

COMMENT ON COLUMN CIA_DOCUMENTACAO_SECAO.NUMR_ORDEM IS
'Ordem de exibição da seção de documentação nas interfaces da plataforma.'

COMMENT ON COLUMN CIA_DOCUMENTACAO_SECAO.CODG_SECAO_PAI IS
'Identificador da seção superior vinculada hierarquicamente à seção atual.'

COMMENT ON COLUMN CIA_DOCUMENTACAO_SECAO.INDI_ATIVO IS
'Indica se a seção de documentação está ativa na plataforma. S = Sim, N = Não.'
