CREATE TABLE CIA_REACAO_COMENTARIO_IDEIA (
    ID_COMENTARIO_IDEIA NUMBER(10) NOT NULL,
    CODG_USUARIO NUMBER(10) NOT NULL,
    DESC_REACAO VARCHAR2(50 CHAR) NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_CIA_REACAO_COMENTARIO_IDEA
        PRIMARY KEY (ID_COMENTARIO_IDEIA, CODG_USUARIO),

    CONSTRAINT FK_CIA_REACAO_COM_IDEA FOREIGN KEY (ID_COMENTARIO_IDEIA)
        REFERENCES CIA_COMENTARIO_IDEIA (ID_COMENTARIO_IDEIA) ON DELETE CASCADE,

    CONSTRAINT FK_CIA_REACAO_COM_USUARIO FOREIGN KEY (CODG_USUARIO)
        REFERENCES USUARIO_SISTEMA (CODG_USUARIO) ON DELETE CASCADE,

    CONSTRAINT CK_CIA_REACAO_TIPO
        CHECK (
            DESC_REACAO IN (
                'thumbs_up',
                'heart',
                'rocket',
                'eyes',
                'idea'
            )
        )
)


CREATE INDEX IDX_CIA_REACAO_COM_USUARIO
    ON CIA_REACAO_COMENTARIO_IDEIA (CODG_USUARIO, DATA_CRIACAO)


COMMENT ON TABLE CIA_REACAO_COMENTARIO_IDEIA IS
'Tabela responsável pelo armazenamento das reações realizadas pelos usuários nos comentários de ideias da plataforma.'

COMMENT ON COLUMN CIA_REACAO_COMENTARIO_IDEIA.ID_COMENTARIO_IDEIA IS
'Identificador do comentário de ideia associado à reação registrada.'

COMMENT ON COLUMN CIA_REACAO_COMENTARIO_IDEIA.CODG_USUARIO IS
'Identificador do usuário responsável pela reação registrada.'

COMMENT ON COLUMN CIA_REACAO_COMENTARIO_IDEIA.DESC_REACAO IS
'Descrição da reação aplicada ao comentário da ideia.'

COMMENT ON COLUMN CIA_REACAO_COMENTARIO_IDEIA.DATA_CRIACAO IS
'Data e hora de criação do registro da reação.'
