CREATE TABLE CIA_COMENTARIO_IDEIA (
    ID_COMENTARIO_IDEIA NUMBER(10) NOT NULL,
    ID_IDEIA NUMBER(10) NOT NULL,
    ID_COMENTARIO_PAI NUMBER(10),
    ID_USUARIO_AUTOR NUMBER(10) NOT NULL,
    DESC_CONTEUDO CLOB NOT NULL,
    STAT_MODERACAO VARCHAR2(2 CHAR) DEFAULT 'PB' NOT NULL,
    DESC_MOTIVO_MODERACAO CLOB,
    ID_USUARIO_MODERADOR NUMBER(10),
    DATA_MODERACAO TIMESTAMP,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_CIA_COMENTARIO_IDEIA PRIMARY KEY (ID_COMENTARIO_IDEIA),

    CONSTRAINT FK_CIA_COM_IDEA FOREIGN KEY (ID_IDEIA) REFERENCES CIA_IDEIA (ID_IDEIA) ON DELETE CASCADE,

    CONSTRAINT FK_CIA_COM_AUTOR FOREIGN KEY (ID_USUARIO_AUTOR) REFERENCES CIA_USUARIO (ID_USUARIO) ON DELETE RESTRICT,

    CONSTRAINT FK_CIA_COM_MODERADOR FOREIGN KEY (ID_USUARIO_MODERADOR) REFERENCES CIA_USUARIO (ID_USUARIO) ON DELETE SET NULL,

    CONSTRAINT FK_CIA_COM_PAI FOREIGN KEY (ID_COMENTARIO_PAI) REFERENCES CIA_COMENTARIO_IDEIA (ID_COMENTARIO_IDEIA) ON DELETE CASCADE,

    CONSTRAINT CK_CIA_COM_STAT_MOD
        CHECK (
            STAT_MODERACAO IN (
                'PB',
                'PE',
                'RP',
                'OC'
            )
        )
)


CREATE SEQUENCE SEQ_CIA_COMENTARIO_IDEIA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_COMENTARIO_IDEIA
BEFORE INSERT ON CIA_COMENTARIO_IDEIA
FOR EACH ROW
BEGIN
    IF :NEW.ID_COMENTARIO_IDEIA IS NULL THEN
        SELECT SEQ_CIA_COMENTARIO_IDEIA.NEXTVAL
          INTO :NEW.ID_COMENTARIO_IDEIA
          FROM DUAL
    END IF
END

CREATE OR REPLACE TRIGGER TRG_BU_CIA_COMENTARIO_IDEIA
BEFORE UPDATE ON CIA_COMENTARIO_IDEIA
FOR EACH ROW
BEGIN
    :NEW.DATA_ATUALIZACAO := CURRENT_TIMESTAMP
END


CREATE INDEX IDX_CIA_COM_IDEA_PAI
    ON CIA_COMENTARIO_IDEIA (
        ID_IDEIA,
        ID_COMENTARIO_PAI,
        DATA_CRIACAO
    )


COMMENT ON TABLE CIA_COMENTARIO_IDEIA IS
'Tabela responsável pelo armazenamento dos comentários realizados pelos usuários nas ideias cadastradas na plataforma.'

COMMENT ON COLUMN CIA_COMENTARIO_IDEIA.ID_COMENTARIO_IDEIA IS
'Identificador único do comentário da ideia.'

COMMENT ON COLUMN CIA_COMENTARIO_IDEIA.ID_IDEIA IS
'Identificador da ideia associada ao comentário.'

COMMENT ON COLUMN CIA_COMENTARIO_IDEIA.ID_COMENTARIO_PAI IS
'Identificador do comentário superior utilizado para composição de respostas encadeadas.'

COMMENT ON COLUMN CIA_COMENTARIO_IDEIA.ID_USUARIO_AUTOR IS
'Identificador do usuário responsável pela criação do comentário.'

COMMENT ON COLUMN CIA_COMENTARIO_IDEIA.DESC_CONTEUDO IS
'Conteúdo textual do comentário realizado na ideia.'

COMMENT ON COLUMN CIA_COMENTARIO_IDEIA.STAT_MODERACAO IS
'Situação atual do processo de moderação do comentário. PB = Publicado, PE = Pendente, RP = Reprovado, OC = Oculto.'

COMMENT ON COLUMN CIA_COMENTARIO_IDEIA.DESC_MOTIVO_MODERACAO IS
'Descrição do motivo aplicado na moderação do comentário.'

COMMENT ON COLUMN CIA_COMENTARIO_IDEIA.ID_USUARIO_MODERADOR IS
'Identificador do usuário responsável pela moderação do comentário.'

COMMENT ON COLUMN CIA_COMENTARIO_IDEIA.DATA_MODERACAO IS
'Data e hora da execução da moderação do comentário.'

COMMENT ON COLUMN CIA_COMENTARIO_IDEIA.DATA_CRIACAO IS
'Data e hora de criação do registro do comentário.'

COMMENT ON COLUMN CIA_COMENTARIO_IDEIA.DATA_ATUALIZACAO IS
'Data e hora da última atualização do registro do comentário.'
