CREATE TABLE CIA_VINCULO_IDEIA_TOPICO (
    ID_IDEIA NUMBER(10) NOT NULL,
    ID_TOPICO_IDEIA NUMBER(10) NOT NULL,

    CONSTRAINT PK_CIA_VINCULO_IDEA_TOPICO
        PRIMARY KEY (
            ID_IDEIA,
            ID_TOPICO_IDEIA
        ),

    CONSTRAINT FK_CIA_VINCULO_IDEA FOREIGN KEY (ID_IDEIA) REFERENCES CIA_IDEIA (ID_IDEIA) ON DELETE CASCADE,

    CONSTRAINT FK_CIA_VINCULO_TOPICO FOREIGN KEY (ID_TOPICO_IDEIA) REFERENCES CIA_TOPICO_IDEIA (ID_TOPICO_IDEIA) ON DELETE RESTRICT
)


CREATE INDEX IDX_CIA_VINCULO_TOPICO
    ON CIA_VINCULO_IDEIA_TOPICO (
        ID_TOPICO_IDEIA,
        ID_IDEIA
    )


COMMENT ON TABLE CIA_VINCULO_IDEIA_TOPICO IS
'Tabela responsável pelo relacionamento entre ideias e tópicos cadastrados na plataforma.'

COMMENT ON COLUMN CIA_VINCULO_IDEIA_TOPICO.ID_IDEIA IS
'Identificador da ideia vinculada ao tópico.'

COMMENT ON COLUMN CIA_VINCULO_IDEIA_TOPICO.ID_TOPICO_IDEIA IS
'Identificador do tópico associado à ideia.'
