CREATE TABLE CIA_IDEIA_TOPICO (
    ID_IDEIA_TOPICO NUMBER(10) NOT NULL,
    NOME_TOPICO VARCHAR2(120 CHAR) NOT NULL,
    NOME_CURTO_TOPICO VARCHAR2(140 CHAR) NOT NULL,
    CODG_COR_TOPICO VARCHAR2(20 CHAR) NOT NULL,
    NOME_ICONE VARCHAR2(80 CHAR),
    DESC_TOPICO VARCHAR2(3000 CHAR),
    NUMR_ORDEM NUMBER(10) DEFAULT 0 NOT NULL,
    INDI_ATIVO VARCHAR2(1 CHAR) DEFAULT 'S' NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_CIA_IDEIA_TOPICO PRIMARY KEY (ID_IDEIA_TOPICO),

    CONSTRAINT UK_CIA_TOPICO_IDEA_NOME UNIQUE (NOME_TOPICO),

    CONSTRAINT UK_CIA_TOPICO_IDEA_SLUG UNIQUE (NOME_CURTO_TOPICO),

    CONSTRAINT CK_CIA_TOPICO_IDEA_ATIVO CHECK (INDI_ATIVO IN ('S', 'N'))
)


CREATE SEQUENCE SEQ_CIA_IDEIA_TOPICO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_IDEIA_TOPICO
BEFORE INSERT ON CIA_IDEIA_TOPICO
FOR EACH ROW
BEGIN
    IF :NEW.ID_IDEIA_TOPICO IS NULL THEN
        SELECT SEQ_CIA_IDEIA_TOPICO.NEXTVAL
          INTO :NEW.ID_IDEIA_TOPICO
          FROM DUAL
    END IF
END

CREATE OR REPLACE TRIGGER TRG_BU_CIA_IDEIA_TOPICO
BEFORE UPDATE ON CIA_IDEIA_TOPICO
FOR EACH ROW
BEGIN
    :NEW.DATA_ATUALIZACAO := CURRENT_TIMESTAMP
END


CREATE INDEX IDX_CIA_TOPICO_IDEA_ATIVO
    ON CIA_IDEIA_TOPICO (
        INDI_ATIVO,
        NUMR_ORDEM,
        NOME_TOPICO
    )


COMMENT ON TABLE CIA_IDEIA_TOPICO IS
'Tabela responsável pelo cadastro dos tópicos utilizados para categorização das ideias da plataforma.'

COMMENT ON COLUMN CIA_IDEIA_TOPICO.ID_IDEIA_TOPICO IS
'Identificador único do tópico de ideia.'

COMMENT ON COLUMN CIA_IDEIA_TOPICO.NOME_TOPICO IS
'Nome do tópico utilizado para categorização das ideias.'

COMMENT ON COLUMN CIA_IDEIA_TOPICO.NOME_CURTO_TOPICO IS
'Nome abreviado e único do tópico, utilizado para identificação, composição de URLs amigáveis e navegação na aplicação.'

COMMENT ON COLUMN CIA_IDEIA_TOPICO.CODG_COR_TOPICO IS
'Código ou identificação visual da cor associada ao tópico.'

COMMENT ON COLUMN CIA_IDEIA_TOPICO.NOME_ICONE IS
'Nome do ícone associado visualmente ao tópico.'

COMMENT ON COLUMN CIA_IDEIA_TOPICO.DESC_TOPICO IS
'Descrição detalhada do tópico de ideia.'

COMMENT ON COLUMN CIA_IDEIA_TOPICO.NUMR_ORDEM IS
'Ordem de exibição do tópico nas interfaces da plataforma.'

COMMENT ON COLUMN CIA_IDEIA_TOPICO.INDI_ATIVO IS
'Indica se o tópico está ativo na plataforma. S = Sim, N = Não.'

COMMENT ON COLUMN CIA_IDEIA_TOPICO.DATA_CRIACAO IS
'Data e hora de criação do registro do tópico.'

COMMENT ON COLUMN CIA_IDEIA_TOPICO.DATA_ATUALIZACAO IS
'Data e hora da última atualização do registro do tópico.'
