CREATE TABLE CIA_VERSAO_IDEIA (
    ID_VERSAO_IDEIA NUMBER(10) NOT NULL,
    NOME_VERSAO VARCHAR2(120 CHAR) NOT NULL,
    DESC_VERSAO CLOB,
    INFO_PREVISAO VARCHAR2(80 CHAR),
    NUMR_ORDEM NUMBER(10) DEFAULT 0 NOT NULL,
    INDI_ATIVO VARCHAR2(1 CHAR) DEFAULT 'S' NOT NULL,
    ID_USUARIO_CRIACAO NUMBER(10),
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_CIA_VERSAO_IDEIA PRIMARY KEY (ID_VERSAO_IDEIA),

    CONSTRAINT UK_CIA_VERSAO_IDEA_NOME UNIQUE (NOME_VERSAO),

    CONSTRAINT FK_CIA_VERSAO_IDEA_USUARIO FOREIGN KEY (ID_USUARIO_CRIACAO)
        REFERENCES CIA_USUARIO (ID_USUARIO)  DELETE SET NULL,

    CONSTRAINT CK_CIA_VERSAO_IDEA_ATIVO CHECK (INDI_ATIVO IN ('S', 'N'))
)


CREATE SEQUENCE SEQ_CIA_VERSAO_IDEIA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_VERSAO_IDEIA
BEFORE INSERT ON CIA_VERSAO_IDEIA
FOR EACH ROW
BEGIN
    IF :NEW.ID_VERSAO_IDEIA IS NULL THEN
        SELECT SEQ_CIA_VERSAO_IDEIA.NEXTVAL
          INTO :NEW.ID_VERSAO_IDEIA
          FROM DUAL
    END IF
END

CREATE OR REPLACE TRIGGER TRG_BU_CIA_VERSAO_IDEIA
BEFORE UPDATE ON CIA_VERSAO_IDEIA
FOR EACH ROW
BEGIN
    :NEW.DATA_ATUALIZACAO := CURRENT_TIMESTAMP
END

CREATE INDEX IDX_CIA_VERSAO_IDEA_ATIVO
    ON CIA_VERSAO_IDEIA (
        INDI_ATIVO,
        NUMR_ORDEM,
        NOME_VERSAO
    )


COMMENT ON TABLE CIA_VERSAO_IDEIA IS
'Tabela responsável pelo cadastro das versões utilizadas para organização e planejamento das ideias da plataforma.'

COMMENT ON COLUMN CIA_VERSAO_IDEIA.ID_VERSAO_IDEIA IS
'Identificador único da versão da ideia.'

COMMENT ON COLUMN CIA_VERSAO_IDEIA.NOME_VERSAO IS
'Nome da versão utilizada para agrupamento das ideias.'

COMMENT ON COLUMN CIA_VERSAO_IDEIA.DESC_VERSAO IS
'Descrição detalhada da versão cadastrada.'

COMMENT ON COLUMN CIA_VERSAO_IDEIA.INFO_PREVISAO IS
'Informação de previsão ou período estimado relacionado à versão da ideia.'

COMMENT ON COLUMN CIA_VERSAO_IDEIA.NUMR_ORDEM IS
'Ordem de exibição da versão nas interfaces da plataforma.'

COMMENT ON COLUMN CIA_VERSAO_IDEIA.INDI_ATIVO IS
'Indica se a versão está ativa na plataforma. S = Sim, N = Não.'

COMMENT ON COLUMN CIA_VERSAO_IDEIA.ID_USUARIO_CRIACAO IS
'Identificador do usuário responsável pela criação da versão da ideia.'

COMMENT ON COLUMN CIA_VERSAO_IDEIA.DATA_CRIACAO IS
'Data e hora de criação do registro da versão.'

COMMENT ON COLUMN CIA_VERSAO_IDEIA.DATA_ATUALIZACAO IS
'Data e hora da última atualização do registro da versão.'
