CREATE TABLE CIA_AGENTE_MCP (
    ID_AGENTE_MCP NUMBER(10) NOT NULL,
    ID_SERVIDOR_MCP NUMBER(10) NOT NULL,
    NOME_AGENTE VARCHAR2(200 CHAR) NOT NULL,
    DESC_AGENTE CLOB DEFAULT '' NOT NULL,
    INFO_CAPACIDADE CLOB DEFAULT '[]' NOT NULL,
    NOME_MODELO_BASE VARCHAR2(200 CHAR),
    DESC_PROMPT_SISTEMA CLOB,
    NUMR_ORDEM NUMBER(10) DEFAULT 0 NOT NULL,

    CONSTRAINT PK_CIA_AGENTE_MCP PRIMARY KEY (ID_AGENTE_MCP),

    CONSTRAINT FK_CIA_AGENTE_MCP_SERVIDOR FOREIGN KEY (ID_SERVIDOR_MCP)
        REFERENCES CIA_SERVIDOR_MCP (ID_SERVIDOR_MCP) ON DELETE CASCADE
)

CREATE SEQUENCE SEQ_CIA_AGENTE_MCP START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_AGENTE_MCP
BEFORE INSERT ON CIA_AGENTE_MCP
FOR EACH ROW
BEGIN
    IF :NEW.ID_AGENTE_MCP IS NULL THEN
        SELECT SEQ_CIA_AGENTE_MCP.NEXTVAL
          INTO :NEW.ID_AGENTE_MCP
          FROM DUAL
    END IF
END

CREATE INDEX IDX_CIA_AGENTE_MCP_SERV
    ON CIA_AGENTE_MCP (ID_SERVIDOR_MCP)


COMMENT ON TABLE CIA_AGENTE_MCP IS
'Tabela responsável pelo cadastro dos agentes MCP vinculados aos servidores da plataforma.'

COMMENT ON COLUMN CIA_AGENTE_MCP.ID_AGENTE_MCP IS
'Identificador único do agente MCP cadastrado.'

COMMENT ON COLUMN CIA_AGENTE_MCP.ID_SERVIDOR_MCP IS
'Identificador do servidor MCP associado ao agente.'

COMMENT ON COLUMN CIA_AGENTE_MCP.NOME_AGENTE IS
'Nome de identificação do agente MCP.'

COMMENT ON COLUMN CIA_AGENTE_MCP.DESC_AGENTE IS
'Descrição detalhada do agente MCP e suas funcionalidades.'

COMMENT ON COLUMN CIA_AGENTE_MCP.INFO_CAPACIDADE IS
'Lista de capacidades e funcionalidades suportadas pelo agente MCP.'

COMMENT ON COLUMN CIA_AGENTE_MCP.NOME_MODELO_BASE IS
'Nome do modelo base utilizado pelo agente MCP.'

COMMENT ON COLUMN CIA_AGENTE_MCP.DESC_PROMPT_SISTEMA IS
'Prompt de sistema utilizado para configuração comportamental do agente MCP.'

COMMENT ON COLUMN CIA_AGENTE_MCP.NUMR_ORDEM IS
'Ordem de exibição do agente MCP nas interfaces da plataforma.'
