CREATE TABLE CIA_MCP_AGENTE (
    ID_MCP_AGENTE NUMBER(10) NOT NULL,
    ID_MCP_SERVIDOR NUMBER(10) NOT NULL,
    NOME_AGENTE VARCHAR2(200 CHAR) NOT NULL,
    DESC_AGENTE CLOB DEFAULT '' NOT NULL,
    INFO_CAPACIDADE CLOB DEFAULT '[]' NOT NULL,
    NOME_MODELO_BASE VARCHAR2(200 CHAR),
    DESC_PROMPT_SISTEMA CLOB,
    NUMR_ORDEM NUMBER(10) DEFAULT 0 NOT NULL,

    CONSTRAINT PK_CIA_MCP_AGENTE PRIMARY KEY (ID_MCP_AGENTE),

    CONSTRAINT FK_CIA_MCP_AGENTE_SERVIDOR FOREIGN KEY (ID_MCP_SERVIDOR)
        REFERENCES CIA_MCP_SERVIDOR (ID_MCP_SERVIDOR) ON DELETE CASCADE
)

CREATE SEQUENCE SEQ_CIA_MCP_AGENTE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_MCP_AGENTE
BEFORE INSERT ON CIA_MCP_AGENTE
FOR EACH ROW
BEGIN
    IF :NEW.ID_MCP_AGENTE IS NULL THEN
        SELECT SEQ_CIA_MCP_AGENTE.NEXTVAL
          INTO :NEW.ID_MCP_AGENTE
          FROM DUAL
    END IF
END

CREATE INDEX IDX_CIA_MCP_AGENTE_SERV
    ON CIA_MCP_AGENTE (ID_MCP_SERVIDOR)


COMMENT ON TABLE CIA_MCP_AGENTE IS
'Tabela responsável pelo cadastro dos agentes MCP vinculados aos servidores da plataforma.'

COMMENT ON COLUMN CIA_MCP_AGENTE.ID_MCP_AGENTE IS
'Identificador único do agente MCP cadastrado.'

COMMENT ON COLUMN CIA_MCP_AGENTE.ID_MCP_SERVIDOR IS
'Identificador do servidor MCP associado ao agente.'

COMMENT ON COLUMN CIA_MCP_AGENTE.NOME_AGENTE IS
'Nome de identificação do agente MCP.'

COMMENT ON COLUMN CIA_MCP_AGENTE.DESC_AGENTE IS
'Descrição detalhada do agente MCP e suas funcionalidades.'

COMMENT ON COLUMN CIA_MCP_AGENTE.INFO_CAPACIDADE IS
'Lista de capacidades e funcionalidades suportadas pelo agente MCP.'

COMMENT ON COLUMN CIA_MCP_AGENTE.NOME_MODELO_BASE IS
'Nome do modelo base utilizado pelo agente MCP.'

COMMENT ON COLUMN CIA_MCP_AGENTE.DESC_PROMPT_SISTEMA IS
'Prompt de sistema utilizado para configuração comportamental do agente MCP.'

COMMENT ON COLUMN CIA_MCP_AGENTE.NUMR_ORDEM IS
'Ordem de exibição do agente MCP nas interfaces da plataforma.'
