CREATE TABLE CIA_MCP_CATEGORIA (
    ID_MCP_CATEGORIA NUMBER(10) NOT NULL,
    NOME_CATEGORIA VARCHAR2(100 CHAR) NOT NULL,
    SLUG_CATEGORIA VARCHAR2(100 CHAR) NOT NULL,
    DESC_CATEGORIA CLOB DEFAULT '' NOT NULL,
    NOME_ICONE VARCHAR2(50 CHAR) DEFAULT 'Plug' NOT NULL,
    CODG_COR VARCHAR2(20 CHAR) DEFAULT '#1a5e38' NOT NULL,
    NUMR_ORDEM NUMBER(10) DEFAULT 0 NOT NULL,
    INDI_ATIVO VARCHAR2(1 CHAR) DEFAULT 'S' NOT NULL,

    CONSTRAINT PK_CIA_MCP_CATEGORIA  PRIMARY KEY (ID_MCP_CATEGORIA),

    CONSTRAINT UK_CIA_MCP_CATEGORIA_NOME UNIQUE (NOME_CATEGORIA),

    CONSTRAINT UK_CIA_MCP_CATEGORIA_SLUG UNIQUE (SLUG_CATEGORIA),

    CONSTRAINT CK_CIA_MCP_CATEGORIA_ATIVO CHECK (INDI_ATIVO IN ('S', 'N'))
)


CREATE SEQUENCE SEQ_CIA_MCP_CATEGORIA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_MCP_CATEGORIA
BEFORE INSERT ON CIA_MCP_CATEGORIA
FOR EACH ROW
BEGIN
    IF :NEW.ID_MCP_CATEGORIA IS NULL THEN
        SELECT SEQ_CIA_MCP_CATEGORIA.NEXTVAL
          INTO :NEW.ID_MCP_CATEGORIA
          FROM DUAL
    END IF
END


CREATE INDEX IDX_CIA_MCP_CATEGORIA_ATIVO
    ON CIA_MCP_CATEGORIA (
        INDI_ATIVO,
        NUMR_ORDEM
    )


COMMENT ON TABLE CIA_MCP_CATEGORIA IS
'Tabela responsável pelo cadastro das categorias utilizadas para organização dos servidores e agentes MCP da plataforma.'

COMMENT ON COLUMN CIA_MCP_CATEGORIA.ID_MCP_CATEGORIA IS
'Identificador único da categoria MCP cadastrada.'

COMMENT ON COLUMN CIA_MCP_CATEGORIA.NOME_CATEGORIA IS
'Nome da categoria utilizada para classificação dos recursos MCP.'

COMMENT ON COLUMN CIA_MCP_CATEGORIA.SLUG_CATEGORIA IS
'Identificador textual único utilizado em URLs e navegação das categorias MCP.'

COMMENT ON COLUMN CIA_MCP_CATEGORIA.DESC_CATEGORIA IS
'Descrição detalhada da categoria MCP cadastrada.'

COMMENT ON COLUMN CIA_MCP_CATEGORIA.NOME_ICONE IS
'Nome do ícone associado visualmente à categoria MCP.'

COMMENT ON COLUMN CIA_MCP_CATEGORIA.CODG_COR IS
'Código hexadecimal da cor utilizada para representação visual da categoria MCP.'

COMMENT ON COLUMN CIA_MCP_CATEGORIA.NUMR_ORDEM IS
'Ordem de exibição da categoria MCP nas interfaces da plataforma.'

COMMENT ON COLUMN CIA_MCP_CATEGORIA.INDI_ATIVO IS
'Indica se a categoria MCP está ativa na plataforma. S = Sim, N = Não.'
