CREATE TABLE CIA_CATEGORIA_MCP (
    ID_CATEGORIA_MCP NUMBER(10) NOT NULL,
    NOME_CATEGORIA VARCHAR2(100 CHAR) NOT NULL,
    SLUG_CATEGORIA VARCHAR2(100 CHAR) NOT NULL,
    DESC_CATEGORIA CLOB DEFAULT '' NOT NULL,
    NOME_ICONE VARCHAR2(50 CHAR) DEFAULT 'Plug' NOT NULL,
    CODG_COR VARCHAR2(20 CHAR) DEFAULT '#1a5e38' NOT NULL,
    NUMR_ORDEM NUMBER(10) DEFAULT 0 NOT NULL,
    INDI_ATIVO VARCHAR2(1 CHAR) DEFAULT 'S' NOT NULL,

    CONSTRAINT PK_CIA_CATEGORIA_MCP  PRIMARY KEY (ID_CATEGORIA_MCP),

    CONSTRAINT UK_CIA_CATEGORIA_MCP_NOME UNIQUE (NOME_CATEGORIA),

    CONSTRAINT UK_CIA_CATEGORIA_MCP_SLUG UNIQUE (SLUG_CATEGORIA),

    CONSTRAINT CK_CIA_CATEGORIA_MCP_ATIVO CHECK (INDI_ATIVO IN ('S', 'N'))
)


CREATE SEQUENCE SEQ_CIA_CATEGORIA_MCP START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_CATEGORIA_MCP
BEFORE INSERT ON CIA_CATEGORIA_MCP
FOR EACH ROW
BEGIN
    IF :NEW.ID_CATEGORIA_MCP IS NULL THEN
        SELECT SEQ_CIA_CATEGORIA_MCP.NEXTVAL
          INTO :NEW.ID_CATEGORIA_MCP
          FROM DUAL
    END IF
END


CREATE INDEX IDX_CIA_CATEGORIA_MCP_ATIVO
    ON CIA_CATEGORIA_MCP (
        INDI_ATIVO,
        NUMR_ORDEM
    )


COMMENT ON TABLE CIA_CATEGORIA_MCP IS
'Tabela responsável pelo cadastro das categorias utilizadas para organização dos servidores e agentes MCP da plataforma.'

COMMENT ON COLUMN CIA_CATEGORIA_MCP.ID_CATEGORIA_MCP IS
'Identificador único da categoria MCP cadastrada.'

COMMENT ON COLUMN CIA_CATEGORIA_MCP.NOME_CATEGORIA IS
'Nome da categoria utilizada para classificação dos recursos MCP.'

COMMENT ON COLUMN CIA_CATEGORIA_MCP.SLUG_CATEGORIA IS
'Identificador textual único utilizado em URLs e navegação das categorias MCP.'

COMMENT ON COLUMN CIA_CATEGORIA_MCP.DESC_CATEGORIA IS
'Descrição detalhada da categoria MCP cadastrada.'

COMMENT ON COLUMN CIA_CATEGORIA_MCP.NOME_ICONE IS
'Nome do ícone associado visualmente à categoria MCP.'

COMMENT ON COLUMN CIA_CATEGORIA_MCP.CODG_COR IS
'Código hexadecimal da cor utilizada para representação visual da categoria MCP.'

COMMENT ON COLUMN CIA_CATEGORIA_MCP.NUMR_ORDEM IS
'Ordem de exibição da categoria MCP nas interfaces da plataforma.'

COMMENT ON COLUMN CIA_CATEGORIA_MCP.INDI_ATIVO IS
'Indica se a categoria MCP está ativa na plataforma. S = Sim, N = Não.'
