TIPO_CLIENTE: {
    CD: 'Claude Desktop',
    VC: 'VS Code',
    CR: 'Cursor',
    TR: 'Terminal',
    CU: 'Customizado'
}

CREATE TABLE CIA_MCP_CONFIGURACAO (
    ID_MCP_CONFIGURACAO NUMBER(10) NOT NULL,
    ID_MCP_SERVIDOR NUMBER(10) NOT NULL,
    TIPO_CLIENTE VARCHAR2(20 CHAR) NOT NULL,
    NOME_CONFIGURACAO VARCHAR2(100 CHAR) NOT NULL,
    JSON_CONFIGURACAO CLOB NOT NULL,
    DESC_OBSERVACAO CLOB,
    NUMR_ORDEM NUMBER(10) DEFAULT 0 NOT NULL,

    CONSTRAINT PK_CIA_MCP_CONFIGURACAO
        PRIMARY KEY (ID_MCP_CONFIGURACAO),

    CONSTRAINT FK_CIA_CONFIG_MCP_SERV
        FOREIGN KEY (ID_MCP_SERVIDOR)
        REFERENCES CIA_MCP_SERVIDOR (ID_MCP_SERVIDOR)
        ON DELETE CASCADE,

    CONSTRAINT CK_CIA_CONFIG_MCP_CLIENTE
        CHECK (
            TIPO_CLIENTE IN (
                'CD',
                'VC',
                'CR',
                'TR',
                'CU'
            )
        )
)


CREATE SEQUENCE SEQ_CIA_MCP_CONFIGURACAO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_CONFIG_MCP
BEFORE INSERT ON CIA_MCP_CONFIGURACAO
FOR EACH ROW
BEGIN
    IF :NEW.ID_MCP_CONFIGURACAO IS NULL THEN
        SELECT SEQ_CIA_MCP_CONFIGURACAO.NEXTVAL
          INTO :NEW.ID_MCP_CONFIGURACAO
          FROM DUAL
    END IF
END

CREATE INDEX IDX_CIA_CONFIG_MCP_SERV
    ON CIA_MCP_CONFIGURACAO (ID_MCP_SERVIDOR)


COMMENT ON TABLE CIA_MCP_CONFIGURACAO IS
'Tabela responsável pelo armazenamento das configurações de integração MCP disponíveis para diferentes tipos de clientes da plataforma.'

COMMENT ON COLUMN CIA_MCP_CONFIGURACAO.ID_MCP_CONFIGURACAO IS
'Identificador único da configuração MCP cadastrada.'

COMMENT ON COLUMN CIA_MCP_CONFIGURACAO.ID_MCP_SERVIDOR IS
'Identificador do servidor MCP associado à configuração.'

COMMENT ON COLUMN CIA_MCP_CONFIGURACAO.TIPO_CLIENTE IS
'Tipo de cliente compatível com a configuração MCP.'

COMMENT ON COLUMN CIA_MCP_CONFIGURACAO.NOME_CONFIGURACAO IS
'Nome identificador da configuração MCP disponibilizada ao cliente.'

COMMENT ON COLUMN CIA_MCP_CONFIGURACAO.JSON_CONFIGURACAO IS
'Conteúdo estruturado da configuração MCP em formato JSON ou textual.'

COMMENT ON COLUMN CIA_MCP_CONFIGURACAO.DESC_OBSERVACAO IS
'Observações complementares relacionadas à configuração MCP (tipo do arquivo .md).'

COMMENT ON COLUMN CIA_MCP_CONFIGURACAO.NUMR_ORDEM IS
'Ordem de exibição da configuração MCP nas interfaces da plataforma.'
