CREATE TABLE CIA_MCP_FAVORITO (
    CODG_USUARIO NUMBER(10) NOT NULL,
    ID_MCP_SERVIDOR NUMBER(10) NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_CIA_MCP_FAVORITO
        PRIMARY KEY (
            CODG_USUARIO,
            ID_MCP_SERVIDOR
        ),

    CONSTRAINT FK_CIA_FAVORITO_USUARIO
        FOREIGN KEY (CODG_USUARIO)
        REFERENCES USUARIO_SISTEMA (CODG_USUARIO)
        ON DELETE CASCADE,

    CONSTRAINT FK_CIA_FAVORITO_SERVIDOR
        FOREIGN KEY (ID_MCP_SERVIDOR)
        REFERENCES CIA_MCP_SERVIDOR (ID_MCP_SERVIDOR)
        ON DELETE CASCADE
)


CREATE INDEX IDX_CIA_MCP_FAVORITO_USUARIO
    ON CIA_MCP_FAVORITO (
        CODG_USUARIO,
        DATA_CRIACAO
    )


COMMENT ON TABLE CIA_MCP_FAVORITO IS
'Tabela responsável pelo armazenamento dos servidores MCP marcados como favoritos pelos usuários da plataforma.'

COMMENT ON COLUMN CIA_MCP_FAVORITO.CODG_USUARIO IS
'Identificador do usuário responsável pela marcação de favorito.'

COMMENT ON COLUMN CIA_MCP_FAVORITO.ID_MCP_SERVIDOR IS
'Identificador do servidor MCP marcado como favorito pelo usuário.'

COMMENT ON COLUMN CIA_MCP_FAVORITO.DATA_CRIACAO IS
'Data e hora de criação do registro de favorito.'
