TIPO_CLIENTE: {
    CLD: 'Claude Desktop',
    VSC: 'VS Code',
    CUR: 'Cursor',
    TER: 'Terminal',
    CUS: 'Customizado'
}

CREATE TABLE CIA_MCP_INSTALACAO (
    ID_MCP_INSTALACAO NUMBER(10) NOT NULL,
    ID_MCP_SERVIDOR NUMBER(10) NOT NULL,
    CODG_USUARIO NUMBER(10) NOT NULL,
    TIPO_CLIENTE VARCHAR2(3 CHAR),
    DATA_INSTALACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_CIA_MCP_INSTALACAO PRIMARY KEY (ID_MCP_INSTALACAO),

    CONSTRAINT UK_CIA_MCP_INSTALACAO
        UNIQUE (
            ID_MCP_SERVIDOR,
            CODG_USUARIO
        ),

    CONSTRAINT FK_CIA_INSTALACAO_SERV
        FOREIGN KEY (ID_MCP_SERVIDOR)
        REFERENCES CIA_MCP_SERVIDOR (ID_MCP_SERVIDOR)
        ON DELETE CASCADE,

    CONSTRAINT FK_CIA_INSTALACAO_USUARIO
        FOREIGN KEY (CODG_USUARIO)
        REFERENCES USUARIO_SISTEMA (CODG_USUARIO)
        ON DELETE CASCADE,

    CONSTRAINT CK_CIA_INSTALACAO_CLIENTE
        CHECK (
            TIPO_CLIENTE IN (
                'CLD',
                'VSC',
                'CUR',
                'TER',
                'CUS'
            )
            OR TIPO_CLIENTE IS NULL
        )
)


CREATE SEQUENCE SEQ_CIA_MCP_INSTALACAO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_MCP_INSTALACAO
BEFORE INSERT ON CIA_MCP_INSTALACAO
FOR EACH ROW
BEGIN
    IF :NEW.ID_MCP_INSTALACAO IS NULL THEN
        SELECT SEQ_CIA_MCP_INSTALACAO.NEXTVAL
          INTO :NEW.ID_MCP_INSTALACAO
          FROM DUAL
    END IF
END

CREATE INDEX IDX_CIA_INSTALACAO_SERV
    ON CIA_MCP_INSTALACAO (ID_MCP_SERVIDOR)

CREATE INDEX IDX_CIA_INSTALACAO_USUARIO
    ON CIA_MCP_INSTALACAO (CODG_USUARIO)


COMMENT ON TABLE CIA_MCP_INSTALACAO IS
'Tabela responsável pelo armazenamento das instalações de servidores MCP realizadas pelos usuários da plataforma.'

COMMENT ON COLUMN CIA_MCP_INSTALACAO.ID_MCP_INSTALACAO IS
'Identificador único da instalação MCP cadastrada.'

COMMENT ON COLUMN CIA_MCP_INSTALACAO.ID_MCP_SERVIDOR IS
'Identificador do servidor MCP instalado pelo usuário.'

COMMENT ON COLUMN CIA_MCP_INSTALACAO.CODG_USUARIO IS
'Identificador do usuário responsável pela instalação do servidor MCP.'

COMMENT ON COLUMN CIA_MCP_INSTALACAO.TIPO_CLIENTE IS
'Tipo de cliente utilizado na instalação MCP. CLD = Claude Desktop, VSC = Visual Studio Code, CUR = Cursor, TER = Terminal, CUS = Customizado.'

COMMENT ON COLUMN CIA_MCP_INSTALACAO.DATA_INSTALACAO IS
'Data e hora de realização da instalação do servidor MCP.'
