CREATE TABLE CIA_MCP_RECURSO (
    ID_MCP_RECURSO NUMBER(10) NOT NULL,
    ID_MCP_SERVIDOR NUMBER(10) NOT NULL,

    NOME_RECURSO VARCHAR2(200 CHAR) NOT NULL,
    URI_TEMPLATE VARCHAR2(500 CHAR) NOT NULL,
    DESC_RECURSO CLOB DEFAULT '' NOT NULL,

    TIPO_MIME VARCHAR2(100 CHAR),

    NUMR_ORDEM NUMBER(10) DEFAULT 0 NOT NULL,

    CONSTRAINT PK_CIA_MCP_RECURSO
        PRIMARY KEY (ID_MCP_RECURSO),

    CONSTRAINT FK_CIA_MCP_RECURSO_SERV
        FOREIGN KEY (ID_MCP_SERVIDOR)
        REFERENCES CIA_MCP_SERVIDOR (ID_MCP_SERVIDOR)
        ON DELETE CASCADE
)


CREATE SEQUENCE SEQ_CIA_MCP_RECURSO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_MCP_RECURSO
BEFORE INSERT ON CIA_MCP_RECURSO
FOR EACH ROW
BEGIN
    IF :NEW.ID_MCP_RECURSO IS NULL THEN
        SELECT SEQ_CIA_MCP_RECURSO.NEXTVAL
          INTO :NEW.ID_MCP_RECURSO
          FROM DUAL
    END IF
END

CREATE INDEX IDX_CIA_MCP_RECURSO_SERV
    ON CIA_MCP_RECURSO (ID_MCP_SERVIDOR)


COMMENT ON TABLE CIA_MCP_RECURSO IS
'Tabela responsável pelo cadastro dos recursos disponibilizados pelos servidores MCP da plataforma.'

COMMENT ON COLUMN CIA_MCP_RECURSO.ID_MCP_RECURSO IS
'Identificador único do recurso MCP cadastrado.'

COMMENT ON COLUMN CIA_MCP_RECURSO.ID_MCP_SERVIDOR IS
'Identificador do servidor MCP associado ao recurso.'

COMMENT ON COLUMN CIA_MCP_RECURSO.NOME_RECURSO IS
'Nome de identificação do recurso disponibilizado pelo servidor MCP.'

COMMENT ON COLUMN CIA_MCP_RECURSO.URI_TEMPLATE IS
'Modelo de URI utilizado para acesso dinâmico ao recurso MCP.'

COMMENT ON COLUMN CIA_MCP_RECURSO.DESC_RECURSO IS
'Descrição detalhada do recurso disponibilizado pelo servidor MCP.'

COMMENT ON COLUMN CIA_MCP_RECURSO.TIPO_MIME IS
'Tipo MIME associado ao conteúdo retornado pelo recurso MCP.'

COMMENT ON COLUMN CIA_MCP_RECURSO.NUMR_ORDEM IS
'Ordem de exibição do recurso MCP nas interfaces da plataforma.'
