CREATE TABLE CIA_RECURSO_MCP (
    ID_RECURSO_MCP NUMBER(10) NOT NULL,
    ID_SERVIDOR_MCP NUMBER(10) NOT NULL,

    NOME_RECURSO VARCHAR2(200 CHAR) NOT NULL,
    URI_TEMPLATE VARCHAR2(500 CHAR) NOT NULL,
    DESC_RECURSO CLOB DEFAULT '' NOT NULL,

    TIPO_MIME VARCHAR2(100 CHAR),

    NUMR_ORDEM NUMBER(10) DEFAULT 0 NOT NULL,

    CONSTRAINT PK_CIA_RECURSO_MCP
        PRIMARY KEY (ID_RECURSO_MCP),

    CONSTRAINT FK_CIA_RECURSO_MCP_SERV
        FOREIGN KEY (ID_SERVIDOR_MCP)
        REFERENCES CIA_SERVIDOR_MCP (ID_SERVIDOR_MCP)
        ON DELETE CASCADE
)


CREATE SEQUENCE SEQ_CIA_RECURSO_MCP
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_RECURSO_MCP
BEFORE INSERT ON CIA_RECURSO_MCP
FOR EACH ROW
BEGIN
    IF :NEW.ID_RECURSO_MCP IS NULL THEN
        SELECT SEQ_CIA_RECURSO_MCP.NEXTVAL
          INTO :NEW.ID_RECURSO_MCP
          FROM DUAL
    END IF
END

CREATE INDEX IDX_CIA_RECURSO_MCP_SERV
    ON CIA_RECURSO_MCP (ID_SERVIDOR_MCP)


COMMENT ON TABLE CIA_RECURSO_MCP IS
'Tabela responsável pelo cadastro dos recursos disponibilizados pelos servidores MCP da plataforma.'

COMMENT ON COLUMN CIA_RECURSO_MCP.ID_RECURSO_MCP IS
'Identificador único do recurso MCP cadastrado.'

COMMENT ON COLUMN CIA_RECURSO_MCP.ID_SERVIDOR_MCP IS
'Identificador do servidor MCP associado ao recurso.'

COMMENT ON COLUMN CIA_RECURSO_MCP.NOME_RECURSO IS
'Nome de identificação do recurso disponibilizado pelo servidor MCP.'

COMMENT ON COLUMN CIA_RECURSO_MCP.URI_TEMPLATE IS
'Modelo de URI utilizado para acesso dinâmico ao recurso MCP.'

COMMENT ON COLUMN CIA_RECURSO_MCP.DESC_RECURSO IS
'Descrição detalhada do recurso disponibilizado pelo servidor MCP.'

COMMENT ON COLUMN CIA_RECURSO_MCP.TIPO_MIME IS
'Tipo MIME associado ao conteúdo retornado pelo recurso MCP.'

COMMENT ON COLUMN CIA_RECURSO_MCP.NUMR_ORDEM IS
'Ordem de exibição do recurso MCP nas interfaces da plataforma.'
