CREATE TABLE CIA_MCP_AVALIACAO (
    ID_MCP_AVALIACAO NUMBER(10) NOT NULL,
    ID_MCP_SERVIDOR NUMBER(10) NOT NULL,
    CODG_USUARIO NUMBER(10) NOT NULL,

    NUMR_AVALIACAO NUMBER(1) NOT NULL,
    DESC_COMENTARIO CLOB,

    INDI_APROVADO VARCHAR2(1 CHAR) DEFAULT 'S' NOT NULL,

    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_CIA_MCP_AVALIACAO
        PRIMARY KEY (ID_MCP_AVALIACAO),

    CONSTRAINT UK_CIA_MCP_AVALIACAO
        UNIQUE (
            ID_MCP_SERVIDOR,
            CODG_USUARIO
        ),

    CONSTRAINT FK_CIA_AVALIACAO_SERV
        FOREIGN KEY (ID_MCP_SERVIDOR)
        REFERENCES CIA_MCP_SERVIDOR (ID_MCP_SERVIDOR)
        ON DELETE CASCADE,

    CONSTRAINT FK_CIA_AVALIACAO_USUARIO
        FOREIGN KEY (CODG_USUARIO)
        REFERENCES USUARIO_SISTEMA (CODG_USUARIO)
        ON DELETE CASCADE,

    CONSTRAINT CK_CIA_AVALIACAO_NOTA
        CHECK (
            NUMR_AVALIACAO BETWEEN 1 AND 5
        ),

    CONSTRAINT CK_CIA_AVALIACAO_APROVADO
        CHECK (
            INDI_APROVADO IN ('S', 'N')
        )
)


CREATE SEQUENCE SEQ_CIA_MCP_AVALIACAO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_MCP_AVALIACAO
BEFORE INSERT ON CIA_MCP_AVALIACAO
FOR EACH ROW
BEGIN
    IF :NEW.ID_MCP_AVALIACAO IS NULL THEN
        SELECT SEQ_CIA_MCP_AVALIACAO.NEXTVAL
          INTO :NEW.ID_MCP_AVALIACAO
          FROM DUAL
    END IF
END

CREATE INDEX IDX_CIA_MCP_AVALIACAO_SERV
    ON CIA_MCP_AVALIACAO (ID_MCP_SERVIDOR)


COMMENT ON TABLE CIA_MCP_AVALIACAO IS
'Tabela responsável pelo armazenamento das avaliações realizadas pelos usuários nos servidores MCP da plataforma.'

COMMENT ON COLUMN CIA_MCP_AVALIACAO.ID_MCP_AVALIACAO IS
'Identificador único da avaliação MCP cadastrada.'

COMMENT ON COLUMN CIA_MCP_AVALIACAO.ID_MCP_SERVIDOR IS
'Identificador do servidor MCP avaliado pelo usuário.'

COMMENT ON COLUMN CIA_MCP_AVALIACAO.CODG_USUARIO IS
'Identificador do usuário responsável pela avaliação registrada.'

COMMENT ON COLUMN CIA_MCP_AVALIACAO.NUMR_AVALIACAO IS
'Nota atribuída ao servidor MCP pelo usuário, variando de 1 a 5.'

COMMENT ON COLUMN CIA_MCP_AVALIACAO.DESC_COMENTARIO IS
'Comentário textual informado pelo usuário na avaliação do servidor MCP.'

COMMENT ON COLUMN CIA_MCP_AVALIACAO.INDI_APROVADO IS
'Indica se a avaliação foi aprovada para exibição na plataforma. S = Sim, N = Não.'

COMMENT ON COLUMN CIA_MCP_AVALIACAO.DATA_CRIACAO IS
'Data e hora de criação do registro da avaliação MCP.'
