CREATE TABLE CIA_AVALIACAO_MCP (
    ID_AVALIACAO_MCP NUMBER(10) NOT NULL,
    ID_SERVIDOR_MCP NUMBER(10) NOT NULL,
    ID_USUARIO NUMBER(10) NOT NULL,

    NUMR_AVALIACAO NUMBER(1) NOT NULL,
    DESC_COMENTARIO CLOB,

    INDI_APROVADO VARCHAR2(1 CHAR) DEFAULT 'S' NOT NULL,

    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_CIA_AVALIACAO_MCP
        PRIMARY KEY (ID_AVALIACAO_MCP),

    CONSTRAINT UK_CIA_AVALIACAO_MCP
        UNIQUE (
            ID_SERVIDOR_MCP,
            ID_USUARIO
        ),

    CONSTRAINT FK_CIA_AVALIACAO_SERV
        FOREIGN KEY (ID_SERVIDOR_MCP)
        REFERENCES CIA_SERVIDOR_MCP (ID_SERVIDOR_MCP)
        ON DELETE CASCADE,

    CONSTRAINT FK_CIA_AVALIACAO_USUARIO
        FOREIGN KEY (ID_USUARIO)
        REFERENCES CIA_USUARIO (ID_USUARIO)
        ON DELETE CASCADE,

    CONSTRAINT CK_CIA_AVALIACAO_NOTA
        CHECK (
            NUMR_AVALIACAO BETWEEN 1 AND 5
        ),

    CONSTRAINT CK_CIA_AVALIACAO_APROVADO
        CHECK (
            INDI_APROVADO IN ('S', 'N')
        )
)


CREATE SEQUENCE SEQ_CIA_AVALIACAO_MCP
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_AVALIACAO_MCP
BEFORE INSERT ON CIA_AVALIACAO_MCP
FOR EACH ROW
BEGIN
    IF :NEW.ID_AVALIACAO_MCP IS NULL THEN
        SELECT SEQ_CIA_AVALIACAO_MCP.NEXTVAL
          INTO :NEW.ID_AVALIACAO_MCP
          FROM DUAL
    END IF
END

CREATE INDEX IDX_CIA_AVALIACAO_MCP_SERV
    ON CIA_AVALIACAO_MCP (ID_SERVIDOR_MCP)


COMMENT ON TABLE CIA_AVALIACAO_MCP IS
'Tabela responsável pelo armazenamento das avaliações realizadas pelos usuários nos servidores MCP da plataforma.'

COMMENT ON COLUMN CIA_AVALIACAO_MCP.ID_AVALIACAO_MCP IS
'Identificador único da avaliação MCP cadastrada.'

COMMENT ON COLUMN CIA_AVALIACAO_MCP.ID_SERVIDOR_MCP IS
'Identificador do servidor MCP avaliado pelo usuário.'

COMMENT ON COLUMN CIA_AVALIACAO_MCP.ID_USUARIO IS
'Identificador do usuário responsável pela avaliação registrada.'

COMMENT ON COLUMN CIA_AVALIACAO_MCP.NUMR_AVALIACAO IS
'Nota atribuída ao servidor MCP pelo usuário, variando de 1 a 5.'

COMMENT ON COLUMN CIA_AVALIACAO_MCP.DESC_COMENTARIO IS
'Comentário textual informado pelo usuário na avaliação do servidor MCP.'

COMMENT ON COLUMN CIA_AVALIACAO_MCP.INDI_APROVADO IS
'Indica se a avaliação foi aprovada para exibição na plataforma. S = Sim, N = Não.'

COMMENT ON COLUMN CIA_AVALIACAO_MCP.DATA_CRIACAO IS
'Data e hora de criação do registro da avaliação MCP.'
