STAT_SERVIDOR:
    DP = Disponível
    BT = Beta
    EX = Experimental
    DC = Descontinuado

CREATE TABLE CIA_SERVIDOR_MCP (
    ID_SERVIDOR_MCP NUMBER(10) NOT NULL,

    NOME_SERVIDOR VARCHAR2(200 CHAR) NOT NULL,
    SLUG_SERVIDOR VARCHAR2(200 CHAR) NOT NULL,

    DESC_RESUMIDA VARCHAR2(300 CHAR) DEFAULT '' NOT NULL,
    DESC_SERVIDOR CLOB DEFAULT '' NOT NULL,

    ID_CATEGORIA_MCP NUMBER(10),

    STAT_SERVIDOR VARCHAR2(2 CHAR) DEFAULT 'EX' NOT NULL,

    INDI_VERIFICADO VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
    INDI_DESTAQUE VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
    INDI_OFICIAL VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,

    URL_REPOSITORIO VARCHAR2(500 CHAR),
    URL_DOCUMENTACAO VARCHAR2(500 CHAR),
    URL_HOMEPAGE VARCHAR2(500 CHAR),

    NUMR_VERSAO VARCHAR2(50 CHAR),
    NOME_LICENCA VARCHAR2(100 CHAR),

    INFO_MODELOS_COMPATIVEIS CLOB DEFAULT '[]' NOT NULL,

    VALR_MEDIA_AVALIACAO NUMBER(3,2) DEFAULT 0 NOT NULL,
    QTDE_AVALIACAO NUMBER(10) DEFAULT 0 NOT NULL,
    QTDE_INSTALACAO NUMBER(10) DEFAULT 0 NOT NULL,

    NOME_AUTOR VARCHAR2(200 CHAR),
    NOME_ORGANIZACAO_AUTOR VARCHAR2(200 CHAR),

    ID_USUARIO_SUBMISSAO NUMBER(10),

    TAG CLOB DEFAULT '[]' NOT NULL,

    NUMR_ORDEM NUMBER(10) DEFAULT 0 NOT NULL,

    INDI_ATIVO VARCHAR2(1 CHAR) DEFAULT 'S' NOT NULL,

    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_CIA_SERVIDOR_MCP
        PRIMARY KEY (ID_SERVIDOR_MCP),

    CONSTRAINT UK_CIA_SERVIDOR_MCP_SLUG
        UNIQUE (SLUG_SERVIDOR),

    CONSTRAINT FK_CIA_SERVIDOR_MCP_CAT
        FOREIGN KEY (ID_CATEGORIA_MCP)
        REFERENCES CIA_CATEGORIA_MCP (ID_CATEGORIA_MCP)
        ON DELETE SET NULL,

    CONSTRAINT FK_CIA_SERVIDOR_MCP_USER
        FOREIGN KEY (ID_USUARIO_SUBMISSAO)
        REFERENCES CIA_USUARIO (ID_USUARIO)
        ON DELETE SET NULL,

    CONSTRAINT CK_CIA_SERVIDOR_STATUS
        CHECK (
            STAT_SERVIDOR IN (
                'DP',
                'BT',
                'EX',
                'DC'
            )
        ),

    CONSTRAINT CK_CIA_SERVIDOR_VERIFICADO
        CHECK (
            INDI_VERIFICADO IN ('S', 'N')
        ),

    CONSTRAINT CK_CIA_SERVIDOR_DESTAQUE
        CHECK (
            INDI_DESTAQUE IN ('S', 'N')
        ),

    CONSTRAINT CK_CIA_SERVIDOR_OFICIAL
        CHECK (
            INDI_OFICIAL IN ('S', 'N')
        ),

    CONSTRAINT CK_CIA_SERVIDOR_ATIVO
        CHECK (
            INDI_ATIVO IN ('S', 'N')
        )
)


CREATE SEQUENCE SEQ_CIA_SERVIDOR_MCP
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_SERVIDOR_MCP
BEFORE INSERT ON CIA_SERVIDOR_MCP
FOR EACH ROW
BEGIN
    IF :NEW.ID_SERVIDOR_MCP IS NULL THEN
        SELECT SEQ_CIA_SERVIDOR_MCP.NEXTVAL
          INTO :NEW.ID_SERVIDOR_MCP
          FROM DUAL
    END IF
END

CREATE OR REPLACE TRIGGER TRG_BU_CIA_SERVIDOR_MCP
BEFORE UPDATE ON CIA_SERVIDOR_MCP
FOR EACH ROW
BEGIN
    :NEW.DATA_ATUALIZACAO := CURRENT_TIMESTAMP
END

CREATE INDEX IDX_CIA_SERVIDOR_MCP_CAT ON CIA_SERVIDOR_MCP (ID_CATEGORIA_MCP)

CREATE INDEX IDX_CIA_SERVIDOR_MCP_DEST ON CIA_SERVIDOR_MCP (INDI_DESTAQUE)

CREATE INDEX IDX_CIA_SERVIDOR_MCP_SLUG ON CIA_SERVIDOR_MCP (SLUG_SERVIDOR)

CREATE INDEX IDX_CIA_SERVIDOR_MCP_STATUS  ON CIA_SERVIDOR_MCP (STAT_SERVIDOR)


COMMENT ON TABLE CIA_SERVIDOR_MCP IS
'Tabela responsável pelo cadastro dos servidores MCP disponíveis na plataforma.'

COMMENT ON COLUMN CIA_SERVIDOR_MCP.ID_SERVIDOR_MCP IS
'Identificador único do servidor MCP cadastrado.'

COMMENT ON COLUMN CIA_SERVIDOR_MCP.NOME_SERVIDOR IS
'Nome de exibição do servidor MCP.'

COMMENT ON COLUMN CIA_SERVIDOR_MCP.SLUG_SERVIDOR IS
'Identificador textual único utilizado em URLs e integrações do servidor MCP.'

COMMENT ON COLUMN CIA_SERVIDOR_MCP.DESC_RESUMIDA IS
'Descrição resumida utilizada para apresentação rápida do servidor MCP.'

COMMENT ON COLUMN CIA_SERVIDOR_MCP.DESC_SERVIDOR IS
'Descrição detalhada do servidor MCP e suas funcionalidades.'

COMMENT ON COLUMN CIA_SERVIDOR_MCP.ID_CATEGORIA_MCP IS
'Identificador da categoria associada ao servidor MCP.'

COMMENT ON COLUMN CIA_SERVIDOR_MCP.STAT_SERVIDOR IS
'Situação atual do servidor MCP. DP = Disponível, BT = Beta, EX = Experimental, DC = Descontinuado.'

COMMENT ON COLUMN CIA_SERVIDOR_MCP.INDI_VERIFICADO IS
'Indica se o servidor MCP foi verificado pela plataforma. S = Sim, N = Não.'

COMMENT ON COLUMN CIA_SERVIDOR_MCP.INDI_DESTAQUE IS
'Indica se o servidor MCP deve ser exibido em destaque. S = Sim, N = Não.'

COMMENT ON COLUMN CIA_SERVIDOR_MCP.INDI_OFICIAL IS
'Indica se o servidor MCP é oficial da plataforma. S = Sim, N = Não.'

COMMENT ON COLUMN CIA_SERVIDOR_MCP.URL_REPOSITORIO IS
'Endereço do repositório de código-fonte do servidor MCP.'

COMMENT ON COLUMN CIA_SERVIDOR_MCP.URL_DOCUMENTACAO IS
'Endereço da documentação oficial do servidor MCP.'

COMMENT ON COLUMN CIA_SERVIDOR_MCP.URL_HOMEPAGE IS
'Endereço principal de acesso ou apresentação do servidor MCP.'

COMMENT ON COLUMN CIA_SERVIDOR_MCP.NUMR_VERSAO IS
'Número da versão atual do servidor MCP.'

COMMENT ON COLUMN CIA_SERVIDOR_MCP.NOME_LICENCA IS
'Nome da licença de uso aplicada ao servidor MCP.'

COMMENT ON COLUMN CIA_SERVIDOR_MCP.INFO_MODELOS_COMPATIVEIS IS
'Lista de modelos compatíveis com o servidor MCP armazenada em formato JSON.'

COMMENT ON COLUMN CIA_SERVIDOR_MCP.VALR_MEDIA_AVALIACAO IS
'Valor médio das avaliações recebidas pelo servidor MCP.'

COMMENT ON COLUMN CIA_SERVIDOR_MCP.QTDE_AVALIACAO IS
'Quantidade total de avaliações registradas para o servidor MCP.'

COMMENT ON COLUMN CIA_SERVIDOR_MCP.QTDE_INSTALACAO IS
'Quantidade total de instalações realizadas do servidor MCP.'

COMMENT ON COLUMN CIA_SERVIDOR_MCP.NOME_AUTOR IS
'Nome do autor responsável pelo desenvolvimento do servidor MCP.'

COMMENT ON COLUMN CIA_SERVIDOR_MCP.NOME_ORGANIZACAO_AUTOR IS
'Nome da organização responsável pelo servidor MCP.'

COMMENT ON COLUMN CIA_SERVIDOR_MCP.ID_USUARIO_SUBMISSAO IS
'Identificador do usuário responsável pela submissão do servidor MCP na plataforma.'

COMMENT ON COLUMN CIA_SERVIDOR_MCP.TAG IS
'Lista de etiquetas utilizadas para categorização e pesquisa do servidor MCP.'

COMMENT ON COLUMN CIA_SERVIDOR_MCP.NUMR_ORDEM IS
'Ordem de exibição do servidor MCP nas interfaces da plataforma.'

COMMENT ON COLUMN CIA_SERVIDOR_MCP.INDI_ATIVO IS
'Indica se o servidor MCP está ativo na plataforma. S = Sim, N = Não.'

COMMENT ON COLUMN CIA_SERVIDOR_MCP.DATA_CRIACAO IS
'Data e hora de criação do registro do servidor MCP.'

COMMENT ON COLUMN CIA_SERVIDOR_MCP.DATA_ATUALIZACAO IS
'Data e hora da última atualização do registro do servidor MCP.'
