CREATE TABLE CIA_FERRAMENTA_MCP (
    ID_FERRAMENTA_MCP NUMBER(10) NOT NULL,

    ID_SERVIDOR_MCP NUMBER(10) NOT NULL,

    NOME_FERRAMENTA VARCHAR2(200 CHAR) NOT NULL,

    DESC_FERRAMENTA CLOB DEFAULT '' NOT NULL,

    INFO_PARAMETRO CLOB DEFAULT '[]' NOT NULL,

    TIPO_RETORNO VARCHAR2(100 CHAR),

    DESC_EXEMPLO_CHAMADA CLOB,

    NUMR_ORDEM NUMBER(10) DEFAULT 0 NOT NULL,

    CONSTRAINT PK_CIA_FERRAMENTA_MCP PRIMARY KEY (ID_FERRAMENTA_MCP),

    CONSTRAINT FK_CIA_FERRAMENTA_MCP_SERV FOREIGN KEY (ID_SERVIDOR_MCP) REFERENCES CIA_SERVIDOR_MCP (ID_SERVIDOR_MCP)
        ON DELETE CASCADE
)


CREATE SEQUENCE SEQ_CIA_FERRAMENTA_MCP
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_FERRAMENTA_MCP
BEFORE INSERT ON CIA_FERRAMENTA_MCP
FOR EACH ROW
BEGIN
    IF :NEW.ID_FERRAMENTA_MCP IS NULL THEN
        SELECT SEQ_CIA_FERRAMENTA_MCP.NEXTVAL
          INTO :NEW.ID_FERRAMENTA_MCP
          FROM DUAL
    END IF
END

CREATE INDEX IDX_CIA_FERRAMENTA_MCP_SERV
    ON CIA_FERRAMENTA_MCP (ID_SERVIDOR_MCP)


COMMENT ON TABLE CIA_FERRAMENTA_MCP IS
'Tabela responsável pelo cadastro das ferramentas disponibilizadas pelos servidores MCP da plataforma.'

COMMENT ON COLUMN CIA_FERRAMENTA_MCP.ID_FERRAMENTA_MCP IS
'Identificador único da ferramenta MCP cadastrada.'

COMMENT ON COLUMN CIA_FERRAMENTA_MCP.ID_SERVIDOR_MCP IS
'Identificador do servidor MCP associado à ferramenta.'

COMMENT ON COLUMN CIA_FERRAMENTA_MCP.NOME_FERRAMENTA IS
'Nome de identificação da ferramenta disponibilizada pelo servidor MCP.'

COMMENT ON COLUMN CIA_FERRAMENTA_MCP.DESC_FERRAMENTA IS
'Descrição detalhada da ferramenta MCP e suas funcionalidades.'

COMMENT ON COLUMN CIA_FERRAMENTA_MCP.INFO_PARAMETRO IS
'Lista estruturada de parâmetros aceitos pela ferramenta MCP armazenada em formato JSON.'

COMMENT ON COLUMN CIA_FERRAMENTA_MCP.TIPO_RETORNO IS
'Tipo de retorno esperado pela execução da ferramenta MCP.'

COMMENT ON COLUMN CIA_FERRAMENTA_MCP.DESC_EXEMPLO_CHAMADA IS
'Exemplo de chamada e utilização da ferramenta MCP.'

COMMENT ON COLUMN CIA_FERRAMENTA_MCP.NUMR_ORDEM IS
'Ordem de exibição da ferramenta MCP nas interfaces da plataforma.'
