CREATE TABLE CIA_MCP_FERRAMENTA (
    ID_MCP_FERRAMENTA NUMBER(10) NOT NULL,

    ID_MCP_SERVIDOR NUMBER(10) NOT NULL,

    NOME_FERRAMENTA VARCHAR2(200 CHAR) NOT NULL,

    DESC_FERRAMENTA CLOB DEFAULT '' NOT NULL,

    JSON_PARAMETRO CLOB DEFAULT '[]' NOT NULL,

    TIPO_RETORNO VARCHAR2(100 CHAR),

    DESC_EXEMPLO_CHAMADA CLOB,

    NUMR_ORDEM NUMBER(10) DEFAULT 0 NOT NULL,

    CONSTRAINT PK_CIA_MCP_FERRAMENTA PRIMARY KEY (ID_MCP_FERRAMENTA),

    CONSTRAINT FK_CIA_MCP_FERRAMENTA_SERV FOREIGN KEY (ID_MCP_SERVIDOR) REFERENCES CIA_MCP_SERVIDOR (ID_MCP_SERVIDOR)
        ON DELETE CASCADE
)


CREATE SEQUENCE SEQ_CIA_MCP_FERRAMENTA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_MCP_FERRAMENTA
BEFORE INSERT ON CIA_MCP_FERRAMENTA
FOR EACH ROW
BEGIN
    IF :NEW.ID_MCP_FERRAMENTA IS NULL THEN
        SELECT SEQ_CIA_MCP_FERRAMENTA.NEXTVAL
          INTO :NEW.ID_MCP_FERRAMENTA
          FROM DUAL
    END IF
END

CREATE INDEX IDX_CIA_MCP_FERRAMENTA_SERV
    ON CIA_MCP_FERRAMENTA (ID_MCP_SERVIDOR)


COMMENT ON TABLE CIA_MCP_FERRAMENTA IS
'Tabela responsável pelo cadastro das ferramentas disponibilizadas pelos servidores MCP da plataforma.'

COMMENT ON COLUMN CIA_MCP_FERRAMENTA.ID_MCP_FERRAMENTA IS
'Identificador único da ferramenta MCP cadastrada.'

COMMENT ON COLUMN CIA_MCP_FERRAMENTA.ID_MCP_SERVIDOR IS
'Identificador do servidor MCP associado à ferramenta.'

COMMENT ON COLUMN CIA_MCP_FERRAMENTA.NOME_FERRAMENTA IS
'Nome de identificação da ferramenta disponibilizada pelo servidor MCP.'

COMMENT ON COLUMN CIA_MCP_FERRAMENTA.DESC_FERRAMENTA IS
'Descrição detalhada da ferramenta MCP e suas funcionalidades.'

COMMENT ON COLUMN CIA_MCP_FERRAMENTA.JSON_PARAMETRO IS
'Lista estruturada de parâmetros aceitos pela ferramenta MCP armazenada em formato JSON.'

COMMENT ON COLUMN CIA_MCP_FERRAMENTA.TIPO_RETORNO IS
'Tipo de retorno esperado pela execução da ferramenta MCP.'

COMMENT ON COLUMN CIA_MCP_FERRAMENTA.DESC_EXEMPLO_CHAMADA IS
'Exemplo de chamada e utilização da ferramenta MCP.'

COMMENT ON COLUMN CIA_MCP_FERRAMENTA.NUMR_ORDEM IS
'Ordem de exibição da ferramenta MCP nas interfaces da plataforma.'
