CREATE TABLE CIA_CREDENCIAL_ACESSO_MODELO (
    ID_CREDENCIAL_ACESSO NUMBER(10) NOT NULL,
    ID_SOLICITACAO_ACESSO NUMBER(10) NOT NULL,
    URL_ENDPOINT_BASE VARCHAR2(500 CHAR) NOT NULL,
    CHAVE_ACESSO_CRIPTO CLOB NOT NULL,
    SEGREDO_ACESSO_CRIPTO CLOB NOT NULL,
    INFO_CABECALHO_PUBLICO CLOB DEFAULT '{}' NOT NULL,
    DESC_OBSERVACAO_USO CLOB DEFAULT '' NOT NULL,
    INDI_ATIVO VARCHAR2(1 CHAR) DEFAULT 'S' NOT NULL,
    ID_USUARIO_CRIACAO NUMBER(10) NOT NULL,
    ID_USUARIO_ATUALIZACAO NUMBER(10),
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_CIA_CREDENCIAL_ACESSO
        PRIMARY KEY (ID_CREDENCIAL_ACESSO),

    CONSTRAINT UK_CIA_CREDENCIAL_SOLIC
        UNIQUE (ID_SOLICITACAO_ACESSO),

    CONSTRAINT FK_CIA_CREDENCIAL_SOLIC
        FOREIGN KEY (ID_SOLICITACAO_ACESSO)
        REFERENCES CIA_SOLICITACAO_ACESSO_MODELO (ID_SOLICITACAO_ACESSO)
        ON DELETE CASCADE,

    CONSTRAINT FK_CIA_CREDENCIAL_USER_CRIACAO
        FOREIGN KEY (ID_USUARIO_CRIACAO)
        REFERENCES CIA_USUARIO (ID_USUARIO)
        ON DELETE RESTRICT,

    CONSTRAINT FK_CIA_CREDENCIAL_USER_ATUAL
        FOREIGN KEY (ID_USUARIO_ATUALIZACAO)
        REFERENCES CIA_USUARIO (ID_USUARIO)
        ON DELETE SET NULL,

    CONSTRAINT CK_CIA_CREDENCIAL_ATIVO
        CHECK (
            INDI_ATIVO IN ('S', 'N')
        )
)


CREATE SEQUENCE SEQ_CIA_CREDENCIAL_ACESSO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_CREDENCIAL
BEFORE INSERT ON CIA_CREDENCIAL_ACESSO_MODELO
FOR EACH ROW
BEGIN
    IF :NEW.ID_CREDENCIAL_ACESSO IS NULL THEN
        SELECT SEQ_CIA_CREDENCIAL_ACESSO.NEXTVAL
          INTO :NEW.ID_CREDENCIAL_ACESSO
          FROM DUAL
    END IF
END

CREATE OR REPLACE TRIGGER TRG_BU_CIA_CREDENCIAL
BEFORE UPDATE ON CIA_CREDENCIAL_ACESSO_MODELO
FOR EACH ROW
BEGIN
    :NEW.DATA_ATUALIZACAO := CURRENT_TIMESTAMP
END

CREATE INDEX IDX_CIA_CREDENCIAL_SOLIC
    ON CIA_CREDENCIAL_ACESSO_MODELO (ID_SOLICITACAO_ACESSO)

CREATE INDEX IDX_CIA_CREDENCIAL_USUARIO
    ON CIA_CREDENCIAL_ACESSO_MODELO (
        ID_USUARIO_CRIACAO,
        ID_USUARIO_ATUALIZACAO
    )


COMMENT ON TABLE CIA_CREDENCIAL_ACESSO_MODELO IS
'Tabela responsável pelo armazenamento das credenciais de acesso aos modelos de inteligência artificial da plataforma.'

COMMENT ON COLUMN CIA_CREDENCIAL_ACESSO_MODELO.ID_CREDENCIAL_ACESSO IS
'Identificador único da credencial de acesso cadastrada.'

COMMENT ON COLUMN CIA_CREDENCIAL_ACESSO_MODELO.ID_SOLICITACAO_ACESSO IS
'Identificador da solicitação de acesso associada à credencial.'

COMMENT ON COLUMN CIA_CREDENCIAL_ACESSO_MODELO.URL_ENDPOINT_BASE IS
'Endereço base utilizado para integração e acesso ao modelo de inteligência artificial.'

COMMENT ON COLUMN CIA_CREDENCIAL_ACESSO_MODELO.CHAVE_ACESSO_CRIPTO IS
'Chave de acesso criptografada utilizada para autenticação no modelo.'

COMMENT ON COLUMN CIA_CREDENCIAL_ACESSO_MODELO.SEGREDO_ACESSO_CRIPTO IS
'Segredo de acesso criptografado utilizado para autenticação segura no modelo.'

COMMENT ON COLUMN CIA_CREDENCIAL_ACESSO_MODELO.INFO_CABECALHO_PUBLICO IS
'Informações públicas de cabeçalho utilizadas na integração armazenadas em formato JSON.'

COMMENT ON COLUMN CIA_CREDENCIAL_ACESSO_MODELO.DESC_OBSERVACAO_USO IS
'Observações e instruções relacionadas ao uso da credencial de acesso.'

COMMENT ON COLUMN CIA_CREDENCIAL_ACESSO_MODELO.INDI_ATIVO IS
'Indica se a credencial de acesso está ativa para utilização. S = Sim, N = Não.'

COMMENT ON COLUMN CIA_CREDENCIAL_ACESSO_MODELO.ID_USUARIO_CRIACAO IS
'Identificador do usuário responsável pela criação da credencial de acesso.'

COMMENT ON COLUMN CIA_CREDENCIAL_ACESSO_MODELO.ID_USUARIO_ATUALIZACAO IS
'Identificador do usuário responsável pela última atualização da credencial de acesso.'

COMMENT ON COLUMN CIA_CREDENCIAL_ACESSO_MODELO.DATA_CRIACAO IS
'Data e hora de criação do registro da credencial de acesso.'

COMMENT ON COLUMN CIA_CREDENCIAL_ACESSO_MODELO.DATA_ATUALIZACAO IS
'Data e hora da última atualização do registro da credencial de acesso.'
