STAT_SOLICITACAO:
    PE = Pendente,
    AP = Aprovado,
    NG = Negado,
    RS = Revogação Solicitada,
    RV = Revogado,
    CA = Cancelado

CREATE TABLE CIA_SOLICITACAO_ACESSO_MODELO (
    ID_SOLICITACAO_ACESSO NUMBER(10) NOT NULL,

    ID_MODELO NUMBER(10) NOT NULL,
    CODG_USUARIO NUMBER(10) NOT NULL,

    NOME_APLICACAO VARCHAR2(200 CHAR) NOT NULL,

    STAT_SOLICITACAO VARCHAR2(2 CHAR) DEFAULT 'PE' NOT NULL,

    DESC_JUSTIFICATIVA CLOB NOT NULL,
    DESC_USO_PRETENDIDO CLOB,

    INFO_CONTEXTO_SOLICITACAO CLOB DEFAULT '{}' NOT NULL,

    CODG_USUARIO_REVISAO NUMBER(10),
    DATA_REVISAO TIMESTAMP,
    DESC_OBSERVACAO_REVISAO CLOB,

    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_CIA_SOLICITACAO_ACESSO
        PRIMARY KEY (ID_SOLICITACAO_ACESSO),

    CONSTRAINT FK_CIA_SOLIC_ACESSO_MODELO
        FOREIGN KEY (ID_MODELO)
        REFERENCES CIA_MODELO (ID_MODELO)
        ON DELETE CASCADE,

    CONSTRAINT FK_CIA_SOLIC_ACESSO_USUARIO
        FOREIGN KEY (CODG_USUARIO)
        REFERENCES USUARIO_SISTEMA (CODG_USUARIO)
        ON DELETE CASCADE,

    CONSTRAINT FK_CIA_SOLIC_ACESSO_REVISAO
        FOREIGN KEY (CODG_USUARIO_REVISAO)
        REFERENCES USUARIO_SISTEMA (CODG_USUARIO)
        ON DELETE SET NULL,

    CONSTRAINT CK_CIA_SOLIC_STATUS
        CHECK (
            STAT_SOLICITACAO IN (
                'PE',
                'AP',
                'NG',
                'RS',
                'RV',
                'CA'
            )
        )
)


CREATE SEQUENCE SEQ_CIA_SOLICITACAO_ACESSO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_SOLIC_ACESSO
BEFORE INSERT ON CIA_SOLICITACAO_ACESSO_MODELO
FOR EACH ROW
BEGIN
    IF :NEW.ID_SOLICITACAO_ACESSO IS NULL THEN
        SELECT SEQ_CIA_SOLICITACAO_ACESSO.NEXTVAL
          INTO :NEW.ID_SOLICITACAO_ACESSO
          FROM DUAL
    END IF
END

CREATE OR REPLACE TRIGGER TRG_BU_CIA_SOLIC_ACESSO
BEFORE UPDATE ON CIA_SOLICITACAO_ACESSO_MODELO
FOR EACH ROW
BEGIN
    :NEW.DATA_ATUALIZACAO := CURRENT_TIMESTAMP
END

CREATE INDEX IDX_CIA_SOLIC_ACESSO_APLIC
    ON CIA_SOLICITACAO_ACESSO_MODELO (NOME_APLICACAO)

CREATE INDEX IDX_CIA_SOLIC_ACESSO_MODELO
    ON CIA_SOLICITACAO_ACESSO_MODELO (ID_MODELO)

CREATE INDEX IDX_CIA_SOLIC_ACESSO_STATUS
    ON CIA_SOLICITACAO_ACESSO_MODELO (
        STAT_SOLICITACAO,
        DATA_CRIACAO
    )

CREATE INDEX IDX_CIA_SOLIC_ACESSO_USUARIO
    ON CIA_SOLICITACAO_ACESSO_MODELO (CODG_USUARIO)

CREATE UNIQUE INDEX UK_CIA_SOLIC_ACESSO_ATIVA
    ON CIA_SOLICITACAO_ACESSO_MODELO (
        ID_MODELO,
        CODG_USUARIO,
        LOWER(TRIM(NOME_APLICACAO))
    )


COMMENT ON TABLE CIA_SOLICITACAO_ACESSO_MODELO IS
'Tabela responsável pelo armazenamento das solicitações de acesso aos modelos de inteligência artificial da plataforma.'

COMMENT ON COLUMN CIA_SOLICITACAO_ACESSO_MODELO.ID_SOLICITACAO_ACESSO IS
'Identificador único da solicitação de acesso ao modelo.'

COMMENT ON COLUMN CIA_SOLICITACAO_ACESSO_MODELO.ID_MODELO IS
'Identificador do modelo de inteligência artificial solicitado.'

COMMENT ON COLUMN CIA_SOLICITACAO_ACESSO_MODELO.CODG_USUARIO IS
'Identificador do usuário responsável pela solicitação de acesso.'

COMMENT ON COLUMN CIA_SOLICITACAO_ACESSO_MODELO.NOME_APLICACAO IS
'Nome da aplicação ou sistema que utilizará o modelo solicitado.'

COMMENT ON COLUMN CIA_SOLICITACAO_ACESSO_MODELO.STAT_SOLICITACAO IS
'Situação atual da solicitação de acesso. PE = Pendente, AP = Aprovado, NG = Negado, RS = Revogação Solicitada, RV = Revogado, CA = Cancelado.'

COMMENT ON COLUMN CIA_SOLICITACAO_ACESSO_MODELO.DESC_JUSTIFICATIVA IS
'Justificativa apresentada pelo usuário para solicitação de acesso ao modelo.'

COMMENT ON COLUMN CIA_SOLICITACAO_ACESSO_MODELO.DESC_USO_PRETENDIDO IS
'Descrição do uso pretendido para o modelo solicitado.'

COMMENT ON COLUMN CIA_SOLICITACAO_ACESSO_MODELO.INFO_CONTEXTO_SOLICITACAO IS
'Informações complementares e contexto da solicitação armazenadas em formato JSON.'

COMMENT ON COLUMN CIA_SOLICITACAO_ACESSO_MODELO.CODG_USUARIO_REVISAO IS
'Identificador do usuário responsável pela revisão da solicitação de acesso.'

COMMENT ON COLUMN CIA_SOLICITACAO_ACESSO_MODELO.DATA_REVISAO IS
'Data e hora da revisão da solicitação de acesso.'

COMMENT ON COLUMN CIA_SOLICITACAO_ACESSO_MODELO.DESC_OBSERVACAO_REVISAO IS
'Observações registradas durante o processo de revisão da solicitação.'

COMMENT ON COLUMN CIA_SOLICITACAO_ACESSO_MODELO.DATA_CRIACAO IS
'Data e hora de criação do registro da solicitação de acesso.'

COMMENT ON COLUMN CIA_SOLICITACAO_ACESSO_MODELO.DATA_ATUALIZACAO IS
'Data e hora da última atualização do registro da solicitação de acesso.'
