CREATE TABLE CIA_NOTIFICACAO_LEITURA (
    CODG_USUARIO NUMBER(10) NOT NULL,
    ID_NOTIFICACAO NUMBER(10) NOT NULL,
    DATA_LEITURA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_CIA_NOTIFICACAO_LEITURA
        PRIMARY KEY (
            CODG_USUARIO,
            ID_NOTIFICACAO
        ),

    CONSTRAINT FK_CIA_LEITURA_NOTIF_USUARIO
        FOREIGN KEY (CODG_USUARIO)
        REFERENCES USUARIO_SISTEMA (CODG_USUARIO)
        ON DELETE CASCADE,

    CONSTRAINT FK_CIA_LEITURA_NOTIF
        FOREIGN KEY (ID_NOTIFICACAO)
        REFERENCES CIA_NOTIFICACAO (ID_NOTIFICACAO)
        ON DELETE CASCADE
)


CREATE INDEX IDX_CIA_LEITURA_NOTIF_USUARIO
    ON CIA_NOTIFICACAO_LEITURA (
        CODG_USUARIO,
        DATA_LEITURA
    )


COMMENT ON TABLE CIA_NOTIFICACAO_LEITURA IS
'Tabela responsável pelo armazenamento das leituras de notificações realizadas pelos usuários da plataforma.'

COMMENT ON COLUMN CIA_NOTIFICACAO_LEITURA.CODG_USUARIO IS
'Identificador do usuário responsável pela leitura da notificação.'

COMMENT ON COLUMN CIA_NOTIFICACAO_LEITURA.ID_NOTIFICACAO IS
'Identificador da notificação lida pelo usuário.'

COMMENT ON COLUMN CIA_NOTIFICACAO_LEITURA.DATA_LEITURA IS
'Data e hora em que a notificação foi marcada como lida pelo usuário.'
