CREATE TABLE CIA_LEITURA_NOTIFICACAO (
    CODG_USUARIO VARCHAR2(32) NOT NULL,
    ID_NOTIFICACAO NUMBER(10) NOT NULL,
    DATA_LEITURA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_CIA_LEITURA_NOTIFICACAO
        PRIMARY KEY (
            CODG_USUARIO,
            ID_NOTIFICACAO
        ),

    CONSTRAINT FK_CIA_LEITURA_NOTIF_USUARIO
        FOREIGN KEY (CODG_USUARIO)
        REFERENCES CIA_USUARIO (CODG_USUARIO)
        ON DELETE CASCADE,

    CONSTRAINT FK_CIA_LEITURA_NOTIF
        FOREIGN KEY (ID_NOTIFICACAO)
        REFERENCES CIA_NOTIFICACAO (ID_NOTIFICACAO)
        ON DELETE CASCADE
)


CREATE INDEX IDX_CIA_LEITURA_NOTIF_USUARIO
    ON CIA_LEITURA_NOTIFICACAO (
        CODG_USUARIO,
        DATA_LEITURA
    )


COMMENT ON TABLE CIA_LEITURA_NOTIFICACAO IS
'Tabela responsável pelo armazenamento das leituras de notificações realizadas pelos usuários da plataforma.'

COMMENT ON COLUMN CIA_LEITURA_NOTIFICACAO.CODG_USUARIO IS
'Identificador do usuário responsável pela leitura da notificação.'

COMMENT ON COLUMN CIA_LEITURA_NOTIFICACAO.ID_NOTIFICACAO IS
'Identificador da notificação lida pelo usuário.'

COMMENT ON COLUMN CIA_LEITURA_NOTIFICACAO.DATA_LEITURA IS
'Data e hora em que a notificação foi marcada como lida pelo usuário.'
