CREATE TABLE CIA_DESTINATARIO_NOTIFICACAO (
    ID_NOTIFICACAO NUMBER(10) NOT NULL,
    CODG_USUARIO NUMBER(10) NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_CIA_DEST_NOTIFICACAO
        PRIMARY KEY (
            ID_NOTIFICACAO,
            CODG_USUARIO
        ),

    CONSTRAINT FK_CIA_DEST_NOTIF
        FOREIGN KEY (ID_NOTIFICACAO)
        REFERENCES CIA_NOTIFICACAO (ID_NOTIFICACAO)
        ON DELETE CASCADE,

    CONSTRAINT FK_CIA_DEST_NOTIF_USUARIO
        FOREIGN KEY (CODG_USUARIO)
        REFERENCES CIA_USUARIO (CODG_USUARIO)
        ON DELETE CASCADE
)


CREATE INDEX IDX_CIA_DEST_NOTIF_USUARIO
    ON CIA_DESTINATARIO_NOTIFICACAO (
        CODG_USUARIO,
        ID_NOTIFICACAO
    )


COMMENT ON TABLE CIA_DESTINATARIO_NOTIFICACAO IS
'Tabela responsável pelo relacionamento entre notificações e os usuários destinatários da plataforma.'

COMMENT ON COLUMN CIA_DESTINATARIO_NOTIFICACAO.ID_NOTIFICACAO IS
'Identificador da notificação destinada ao usuário.'

COMMENT ON COLUMN CIA_DESTINATARIO_NOTIFICACAO.CODG_USUARIO IS
'Identificador do usuário destinatário da notificação.'

COMMENT ON COLUMN CIA_DESTINATARIO_NOTIFICACAO.DATA_CRIACAO IS
'Data e hora de criação do vínculo entre notificação e usuário destinatário.'
