CREATE TABLE CIA_PROMPT_CATEGORIA (
    ID_PROMPT_CATEGORIA NUMBER(10) NOT NULL,
    NOME_CATEGORIA VARCHAR2(100 CHAR) NOT NULL,
    NOME_CURTO_CATEGORIA VARCHAR2(100 CHAR) NOT NULL,
    CODG_COR VARCHAR2(20 CHAR) DEFAULT '#1a5e38' NOT NULL,
    NUMR_ORDEM NUMBER(10) DEFAULT 0 NOT NULL,
    NOME_ICONE VARCHAR2(50 CHAR) DEFAULT 'FileText' NOT NULL,
    DESC_CATEGORIA CLOB DEFAULT '' NOT NULL,
    INDI_ATIVO VARCHAR2(1 CHAR) DEFAULT 'S' NOT NULL,

    CONSTRAINT PK_CIA_PROMPT_CATEGORIA PRIMARY KEY (ID_PROMPT_CATEGORIA),

    CONSTRAINT UK_CIA_PROMPT_CATEGORIA_NOME UNIQUE (NOME_CATEGORIA),

    CONSTRAINT UK_CIA_PROMPT_CATEGORIA_SLUG UNIQUE (NOME_CURTO_CATEGORIA),

    CONSTRAINT CK_CIA_PROMPT_CATEGORIA_ATIVO
        CHECK (
            INDI_ATIVO IN ('S', 'N')
        )
)


CREATE SEQUENCE SEQ_CIA_PROMPT_CATEGORIA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_PROMPT_CATEGORIA
BEFORE INSERT ON CIA_PROMPT_CATEGORIA
FOR EACH ROW
BEGIN
    IF :NEW.ID_PROMPT_CATEGORIA IS NULL THEN
        SELECT SEQ_CIA_PROMPT_CATEGORIA.NEXTVAL
          INTO :NEW.ID_PROMPT_CATEGORIA
          FROM DUAL
    END IF
END


CREATE INDEX IDX_CIA_PROMPT_CATEGORIA_ATIVO
    ON CIA_PROMPT_CATEGORIA (
        INDI_ATIVO,
        NUMR_ORDEM
    )


COMMENT ON TABLE CIA_PROMPT_CATEGORIA IS
'Tabela responsável pelo cadastro das categorias utilizadas para organização dos prompts da plataforma.'

COMMENT ON COLUMN CIA_PROMPT_CATEGORIA.ID_PROMPT_CATEGORIA IS
'Identificador único da categoria de prompt cadastrada.'

COMMENT ON COLUMN CIA_PROMPT_CATEGORIA.NOME_CATEGORIA IS
'Nome da categoria utilizada para classificação dos prompts.'

COMMENT ON COLUMN CIA_PROMPT_CATEGORIA.NOME_CURTO_CATEGORIA IS
'Identificador textual único utilizado em URLs e navegação das categorias de prompt.'

COMMENT ON COLUMN CIA_PROMPT_CATEGORIA.CODG_COR IS
'Código hexadecimal da cor utilizada para representação visual da categoria de prompt.'

COMMENT ON COLUMN CIA_PROMPT_CATEGORIA.NUMR_ORDEM IS
'Ordem de exibição da categoria de prompt nas interfaces da plataforma.'

COMMENT ON COLUMN CIA_PROMPT_CATEGORIA.NOME_ICONE IS
'Nome do ícone associado visualmente à categoria de prompt.'

COMMENT ON COLUMN CIA_PROMPT_CATEGORIA.DESC_CATEGORIA IS
'Descrição detalhada da categoria de prompt cadastrada.'

COMMENT ON COLUMN CIA_PROMPT_CATEGORIA.INDI_ATIVO IS
'Indica se a categoria de prompt está ativa na plataforma. S = Sim, N = Não.'
