CREATE TABLE CIA_PROMPT_DERIVACAO (
    ID_PROMPT_DERIVACAO NUMBER(10) NOT NULL,
    ID_PROMPT_ORIGINAL NUMBER(10) NOT NULL,
    ID_PROMPT_FORK NUMBER(10) NOT NULL,
    DESC_MENSAGEM_DERIVADA CLOB,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_CIA_PROMPT_DERIVACAO
        PRIMARY KEY (ID_PROMPT_DERIVACAO),

    CONSTRAINT UK_CIA_PROMPT_DERIVACAO
        UNIQUE (
            ID_PROMPT_ORIGINAL,
            ID_PROMPT_FORK
        ),

    CONSTRAINT FK_CIA_PROMPT_DERIVACAO_ORIG
        FOREIGN KEY (ID_PROMPT_ORIGINAL)
        REFERENCES CIA_PROMPT (ID_PROMPT)
        ON DELETE CASCADE,

    CONSTRAINT FK_CIA_PROMPT_DERIVACAO_DEST
        FOREIGN KEY (ID_PROMPT_FORK)
        REFERENCES CIA_PROMPT (ID_PROMPT)
        ON DELETE CASCADE
)


CREATE SEQUENCE SEQ_CIA_PROMPT_DERIVACAO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE

CREATE OR REPLACE TRIGGER TRG_BI_CIA_PROMPT_DERIVACAO
BEFORE INSERT ON CIA_PROMPT_DERIVACAO
FOR EACH ROW
BEGIN
    IF :NEW.ID_PROMPT_DERIVACAO IS NULL THEN
        SELECT SEQ_CIA_PROMPT_DERIVACAO.NEXTVAL
          INTO :NEW.ID_PROMPT_DERIVACAO
          FROM DUAL
    END IF
END

CREATE INDEX IDX_CIA_PROMPT_DERIVACAO_DEST  ON CIA_PROMPT_DERIVACAO (ID_PROMPT_FORK)

CREATE INDEX IDX_CIA_PROMPT_DERIVACAO_ORIG ON CIA_PROMPT_DERIVACAO (ID_PROMPT_ORIGINAL)


COMMENT ON TABLE CIA_PROMPT_DERIVACAO IS
'Tabela responsável pelo armazenamento das derivações de prompts realizadas pelos usuários da plataforma.'

COMMENT ON COLUMN CIA_PROMPT_DERIVACAO.ID_PROMPT_DERIVACAO IS
'Identificador único do registro de fork do prompt.'

COMMENT ON COLUMN CIA_PROMPT_DERIVACAO.ID_PROMPT_ORIGINAL IS
'Identificador do prompt original utilizado como base para criação do fork.'

COMMENT ON COLUMN CIA_PROMPT_DERIVACAO.ID_PROMPT_FORK IS
'Identificador do novo prompt derivado a partir do prompt original.'

COMMENT ON COLUMN CIA_PROMPT_DERIVACAO.DESC_MENSAGEM_FORK IS
'Mensagem ou observação informada durante a criação do fork do prompt.'

COMMENT ON COLUMN CIA_PROMPT_DERIVACAO.DATA_CRIACAO IS
'Data e hora de criação do registro de fork do prompt.'
