CREATE TABLE CIA_FORK_PROMPT (
    ID_FORK_PROMPT NUMBER(10) NOT NULL,
    ID_PROMPT_ORIGINAL NUMBER(10) NOT NULL,
    ID_PROMPT_FORK NUMBER(10) NOT NULL,
    DESC_MENSAGEM_FORK CLOB,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_CIA_FORK_PROMPT
        PRIMARY KEY (ID_FORK_PROMPT),

    CONSTRAINT UK_CIA_FORK_PROMPT
        UNIQUE (
            ID_PROMPT_ORIGINAL,
            ID_PROMPT_FORK
        ),

    CONSTRAINT FK_CIA_FORK_PROMPT_ORIG
        FOREIGN KEY (ID_PROMPT_ORIGINAL)
        REFERENCES CIA_PROMPT (ID_PROMPT)
        ON DELETE CASCADE,

    CONSTRAINT FK_CIA_FORK_PROMPT_DEST
        FOREIGN KEY (ID_PROMPT_FORK)
        REFERENCES CIA_PROMPT (ID_PROMPT)
        ON DELETE CASCADE
)


CREATE SEQUENCE SEQ_CIA_FORK_PROMPT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE

CREATE OR REPLACE TRIGGER TRG_BI_CIA_FORK_PROMPT
BEFORE INSERT ON CIA_FORK_PROMPT
FOR EACH ROW
BEGIN
    IF :NEW.ID_FORK_PROMPT IS NULL THEN
        SELECT SEQ_CIA_FORK_PROMPT.NEXTVAL
          INTO :NEW.ID_FORK_PROMPT
          FROM DUAL
    END IF
END

CREATE INDEX IDX_CIA_FORK_PROMPT_DEST  ON CIA_FORK_PROMPT (ID_PROMPT_FORK)

CREATE INDEX IDX_CIA_FORK_PROMPT_ORIG ON CIA_FORK_PROMPT (ID_PROMPT_ORIGINAL)


COMMENT ON TABLE CIA_FORK_PROMPT IS
'Tabela responsável pelo armazenamento das derivações de prompts realizadas pelos usuários da plataforma.'

COMMENT ON COLUMN CIA_FORK_PROMPT.ID_FORK_PROMPT IS
'Identificador único do registro de fork do prompt.'

COMMENT ON COLUMN CIA_FORK_PROMPT.ID_PROMPT_ORIGINAL IS
'Identificador do prompt original utilizado como base para criação do fork.'

COMMENT ON COLUMN CIA_FORK_PROMPT.ID_PROMPT_FORK IS
'Identificador do novo prompt derivado a partir do prompt original.'

COMMENT ON COLUMN CIA_FORK_PROMPT.DESC_MENSAGEM_FORK IS
'Mensagem ou observação informada durante a criação do fork do prompt.'

COMMENT ON COLUMN CIA_FORK_PROMPT.DATA_CRIACAO IS
'Data e hora de criação do registro de fork do prompt.'
