CREATE TABLE CIA_PROMPT_AVALIACAO (
    ID_PROMPT_AVALIACAO NUMBER(10) NOT NULL,
    ID_PROMPT NUMBER(10) NOT NULL,
    CODG_USUARIO NUMBER(10) NOT NULL,
    NUMR_AVALIACAO NUMBER(1) NOT NULL,
    DESC_COMENTARIO CLOB,
    INDI_UTILIZADO_ANTES VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
    INDI_APROVADO VARCHAR2(1 CHAR) DEFAULT 'S' NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_CIA_PROMPT_AVALIACAO
        PRIMARY KEY (ID_PROMPT_AVALIACAO),

    CONSTRAINT UK_CIA_PROMPT_AVALIACAO
        UNIQUE (
            ID_PROMPT,
            CODG_USUARIO
        ),

    CONSTRAINT FK_CIA_PROMPT_AVALIACAO
        FOREIGN KEY (ID_PROMPT)
        REFERENCES CIA_PROMPT (ID_PROMPT)
        ON DELETE CASCADE,

    CONSTRAINT FK_CIA_PROMPT_AVALIACAO_USUARIO
        FOREIGN KEY (CODG_USUARIO)
        REFERENCES USUARIO_SISTEMA (CODG_USUARIO)
        ON DELETE CASCADE,

    CONSTRAINT CK_CIA_PROMPT_AVALIACAO_NOTA
        CHECK (
            NUMR_AVALIACAO BETWEEN 1 AND 5
        ),

    CONSTRAINT CK_CIA_PROMPT_AVALIACAO_UTIL
        CHECK (
            INDI_UTILIZADO_ANTES IN ('S', 'N')
        ),

    CONSTRAINT CK_CIA_PROMPT_AVALIACAO_APROV
        CHECK (
            INDI_APROVADO IN ('S', 'N')
        )
)


CREATE SEQUENCE SEQ_CIA_PROMPT_AVALIACAO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_PROMPT_AVALIACAO
BEFORE INSERT ON CIA_PROMPT_AVALIACAO
FOR EACH ROW
BEGIN
    IF :NEW.ID_PROMPT_AVALIACAO IS NULL THEN
        SELECT SEQ_CIA_PROMPT_AVALIACAO.NEXTVAL
          INTO :NEW.ID_PROMPT_AVALIACAO
          FROM DUAL
    END IF
END

CREATE OR REPLACE TRIGGER TRG_BU_CIA_PROMPT_AVALIACAO
BEFORE UPDATE ON CIA_PROMPT_AVALIACAO
FOR EACH ROW
BEGIN
    :NEW.DATA_ATUALIZACAO := CURRENT_TIMESTAMP
END

CREATE INDEX IDX_CIA_PROMPT_AVALIACAO_APROV
    ON CIA_PROMPT_AVALIACAO (
        ID_PROMPT,
        INDI_APROVADO
    )

CREATE INDEX IDX_CIA_PROMPT_AVALIACAO
    ON CIA_PROMPT_AVALIACAO (ID_PROMPT)

CREATE INDEX IDX_CIA_PROMPT_AVALIACAO_USUARIO
    ON CIA_PROMPT_AVALIACAO (CODG_USUARIO)


COMMENT ON TABLE CIA_PROMPT_AVALIACAO IS
'Tabela responsável pelo armazenamento das avaliações realizadas pelos usuários sobre prompts cadastrados na plataforma.'

COMMENT ON COLUMN CIA_PROMPT_AVALIACAO.ID_PROMPT_AVALIACAO IS
'Identificador único da avaliação de prompt cadastrada.'

COMMENT ON COLUMN CIA_PROMPT_AVALIACAO.ID_PROMPT IS
'Identificador do prompt avaliado pelo usuário.'

COMMENT ON COLUMN CIA_PROMPT_AVALIACAO.CODG_USUARIO IS
'Identificador do usuário responsável pela avaliação do prompt.'

COMMENT ON COLUMN CIA_PROMPT_AVALIACAO.NUMR_AVALIACAO IS
'Nota atribuída ao prompt pelo usuário, variando de 1 a 5.'

COMMENT ON COLUMN CIA_PROMPT_AVALIACAO.DESC_COMENTARIO IS
'Comentário textual informado pelo usuário na avaliação do prompt.'

COMMENT ON COLUMN CIA_PROMPT_AVALIACAO.INDI_UTILIZADO_ANTES IS
'Indica se o usuário já havia utilizado o prompt anteriormente. S = Sim, N = Não.'

COMMENT ON COLUMN CIA_PROMPT_AVALIACAO.INDI_APROVADO IS
'Indica se a avaliação foi aprovada para exibição na plataforma. S = Sim, N = Não.'

COMMENT ON COLUMN CIA_PROMPT_AVALIACAO.DATA_CRIACAO IS
'Data e hora de criação do registro da avaliação do prompt.'

COMMENT ON COLUMN CIA_PROMPT_AVALIACAO.DATA_ATUALIZACAO IS
'Data e hora da última atualização do registro da avaliação do prompt.'
