CREATE TABLE CIA_AVALIACAO_PROMPT (
    ID_AVALIACAO_PROMPT NUMBER(10) NOT NULL,

    ID_PROMPT NUMBER(10) NOT NULL,

    ID_USUARIO NUMBER(10) NOT NULL,

    NUMR_AVALIACAO NUMBER(1) NOT NULL,

    DESC_COMENTARIO CLOB,

    INDI_UTILIZADO_ANTES VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,

    INDI_APROVADO VARCHAR2(1 CHAR) DEFAULT 'S' NOT NULL,

    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_CIA_AVALIACAO_PROMPT
        PRIMARY KEY (ID_AVALIACAO_PROMPT),

    CONSTRAINT UK_CIA_AVALIACAO_PROMPT
        UNIQUE (
            ID_PROMPT,
            ID_USUARIO
        ),

    CONSTRAINT FK_CIA_AVALIACAO_PROMPT
        FOREIGN KEY (ID_PROMPT)
        REFERENCES CIA_PROMPT (ID_PROMPT)
        ON DELETE CASCADE,

    CONSTRAINT FK_CIA_AVALIACAO_PROMPT_USUARIO
        FOREIGN KEY (ID_USUARIO)
        REFERENCES CIA_USUARIO (ID_USUARIO)
        ON DELETE CASCADE,

    CONSTRAINT CK_CIA_AVALIACAO_PROMPT_NOTA
        CHECK (
            NUMR_AVALIACAO BETWEEN 1 AND 5
        ),

    CONSTRAINT CK_CIA_AVALIACAO_PROMPT_UTIL
        CHECK (
            INDI_UTILIZADO_ANTES IN ('S', 'N')
        ),

    CONSTRAINT CK_CIA_AVALIACAO_PROMPT_APROV
        CHECK (
            INDI_APROVADO IN ('S', 'N')
        )
)


CREATE SEQUENCE SEQ_CIA_AVALIACAO_PROMPT
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_AVALIACAO_PROMPT
BEFORE INSERT ON CIA_AVALIACAO_PROMPT
FOR EACH ROW
BEGIN
    IF :NEW.ID_AVALIACAO_PROMPT IS NULL THEN
        SELECT SEQ_CIA_AVALIACAO_PROMPT.NEXTVAL
          INTO :NEW.ID_AVALIACAO_PROMPT
          FROM DUAL
    END IF
END

CREATE OR REPLACE TRIGGER TRG_BU_CIA_AVALIACAO_PROMPT
BEFORE UPDATE ON CIA_AVALIACAO_PROMPT
FOR EACH ROW
BEGIN
    :NEW.DATA_ATUALIZACAO := CURRENT_TIMESTAMP
END

CREATE INDEX IDX_CIA_AVALIACAO_PROMPT_APROV
    ON CIA_AVALIACAO_PROMPT (
        ID_PROMPT,
        INDI_APROVADO
    )

CREATE INDEX IDX_CIA_AVALIACAO_PROMPT
    ON CIA_AVALIACAO_PROMPT (ID_PROMPT)

CREATE INDEX IDX_CIA_AVALIACAO_PROMPT_USUARIO
    ON CIA_AVALIACAO_PROMPT (ID_USUARIO)


COMMENT ON TABLE CIA_AVALIACAO_PROMPT IS
'Tabela responsável pelo armazenamento das avaliações realizadas pelos usuários sobre prompts cadastrados na plataforma.'

COMMENT ON COLUMN CIA_AVALIACAO_PROMPT.ID_AVALIACAO_PROMPT IS
'Identificador único da avaliação de prompt cadastrada.'

COMMENT ON COLUMN CIA_AVALIACAO_PROMPT.ID_PROMPT IS
'Identificador do prompt avaliado pelo usuário.'

COMMENT ON COLUMN CIA_AVALIACAO_PROMPT.ID_USUARIO IS
'Identificador do usuário responsável pela avaliação do prompt.'

COMMENT ON COLUMN CIA_AVALIACAO_PROMPT.NUMR_AVALIACAO IS
'Nota atribuída ao prompt pelo usuário, variando de 1 a 5.'

COMMENT ON COLUMN CIA_AVALIACAO_PROMPT.DESC_COMENTARIO IS
'Comentário textual informado pelo usuário na avaliação do prompt.'

COMMENT ON COLUMN CIA_AVALIACAO_PROMPT.INDI_UTILIZADO_ANTES IS
'Indica se o usuário já havia utilizado o prompt anteriormente. S = Sim, N = Não.'

COMMENT ON COLUMN CIA_AVALIACAO_PROMPT.INDI_APROVADO IS
'Indica se a avaliação foi aprovada para exibição na plataforma. S = Sim, N = Não.'

COMMENT ON COLUMN CIA_AVALIACAO_PROMPT.DATA_CRIACAO IS
'Data e hora de criação do registro da avaliação do prompt.'

COMMENT ON COLUMN CIA_AVALIACAO_PROMPT.DATA_ATUALIZACAO IS
'Data e hora da última atualização do registro da avaliação do prompt.'
