CREATE TABLE CIA_USO_PROMPT (
    ID_USO_PROMPT NUMBER(10) NOT NULL,

    ID_PROMPT NUMBER(10) NOT NULL,

    ID_USUARIO NUMBER(10) NOT NULL,

    DATA_UTILIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_CIA_USO_PROMPT
        PRIMARY KEY (ID_USO_PROMPT),

    CONSTRAINT FK_CIA_USO_PROMPT
        FOREIGN KEY (ID_PROMPT)
        REFERENCES CIA_PROMPT (ID_PROMPT)
        ON DELETE CASCADE,

    CONSTRAINT FK_CIA_USO_PROMPT_USUARIO
        FOREIGN KEY (ID_USUARIO)
        REFERENCES CIA_USUARIO (ID_USUARIO)
        ON DELETE CASCADE
)


CREATE SEQUENCE SEQ_CIA_USO_PROMPT
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_USO_PROMPT
BEFORE INSERT ON CIA_USO_PROMPT
FOR EACH ROW
BEGIN
    IF :NEW.ID_USO_PROMPT IS NULL THEN
        SELECT SEQ_CIA_USO_PROMPT.NEXTVAL
          INTO :NEW.ID_USO_PROMPT
          FROM DUAL
    END IF
END

CREATE INDEX IDX_CIA_USO_PROMPT
    ON CIA_USO_PROMPT (ID_PROMPT)

CREATE INDEX IDX_CIA_USO_PROMPT_USUARIO
    ON CIA_USO_PROMPT (ID_USUARIO)

CREATE INDEX IDX_CIA_USO_PROMPT_USER_PROMPT
    ON CIA_USO_PROMPT (
        ID_USUARIO,
        ID_PROMPT
    )


COMMENT ON TABLE CIA_USO_PROMPT IS
'Tabela responsável pelo armazenamento do histórico de utilização dos prompts pelos usuários da plataforma.'

COMMENT ON COLUMN CIA_USO_PROMPT.ID_USO_PROMPT IS
'Identificador único do registro de utilização do prompt.'

COMMENT ON COLUMN CIA_USO_PROMPT.ID_PROMPT IS
'Identificador do prompt utilizado pelo usuário.'

COMMENT ON COLUMN CIA_USO_PROMPT.ID_USUARIO IS
'Identificador do usuário responsável pela utilização do prompt.'

COMMENT ON COLUMN CIA_USO_PROMPT.DATA_UTILIZACAO IS
'Data e hora em que o prompt foi utilizado pelo usuário.'
