CREATE TABLE CIA_PROMPT_USO (
    ID_PROMPT_USO NUMBER(10) NOT NULL,

    ID_PROMPT NUMBER(10) NOT NULL,

    ID_USUARIO NUMBER(10) NOT NULL,

    DATA_UTILIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_CIA_PROMPT_USO
        PRIMARY KEY (ID_PROMPT_USO),

    CONSTRAINT FK_CIA_PROMPT_USO
        FOREIGN KEY (ID_PROMPT)
        REFERENCES CIA_PROMPT (ID_PROMPT)
        ON DELETE CASCADE,

    CONSTRAINT FK_CIA_PROMPT_USO_USUARIO
        FOREIGN KEY (ID_USUARIO)
        REFERENCES CIA_USUARIO (ID_USUARIO)
        ON DELETE CASCADE
)


CREATE SEQUENCE SEQ_CIA_PROMPT_USO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_PROMPT_USO
BEFORE INSERT ON CIA_PROMPT_USO
FOR EACH ROW
BEGIN
    IF :NEW.ID_PROMPT_USO IS NULL THEN
        SELECT SEQ_CIA_PROMPT_USO.NEXTVAL
          INTO :NEW.ID_PROMPT_USO
          FROM DUAL
    END IF
END

CREATE INDEX IDX_CIA_PROMPT_USO
    ON CIA_PROMPT_USO (ID_PROMPT)

CREATE INDEX IDX_CIA_PROMPT_USO_USUARIO
    ON CIA_PROMPT_USO (ID_USUARIO)

CREATE INDEX IDX_CIA_PROMPT_USO_USER_PROMPT
    ON CIA_PROMPT_USO (
        ID_USUARIO,
        ID_PROMPT
    )


COMMENT ON TABLE CIA_PROMPT_USO IS
'Tabela responsável pelo armazenamento do histórico de utilização dos prompts pelos usuários da plataforma.'

COMMENT ON COLUMN CIA_PROMPT_USO.ID_PROMPT_USO IS
'Identificador único do registro de utilização do prompt.'

COMMENT ON COLUMN CIA_PROMPT_USO.ID_PROMPT IS
'Identificador do prompt utilizado pelo usuário.'

COMMENT ON COLUMN CIA_PROMPT_USO.ID_USUARIO IS
'Identificador do usuário responsável pela utilização do prompt.'

COMMENT ON COLUMN CIA_PROMPT_USO.DATA_UTILIZACAO IS
'Data e hora em que o prompt foi utilizado pelo usuário.'
