CREATE TABLE CIA_VERSAO_PROMPT (
    ID_VERSAO_PROMPT NUMBER(10) NOT NULL,

    ID_PROMPT NUMBER(10) NOT NULL,

    NUMR_VERSAO NUMBER(10) NOT NULL,

    TITULO_PROMPT VARCHAR2(300 CHAR) NOT NULL,

    DESC_PROMPT CLOB DEFAULT '' NOT NULL,

    DESC_CONTEUDO CLOB NOT NULL,

    INFO_VARIAVEL CLOB DEFAULT '[]' NOT NULL,

    TAG CLOB DEFAULT '[]' NOT NULL,

    ID_USUARIO_APROVACAO NUMBER(10),

    DATA_APROVACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_CIA_VERSAO_PROMPT
        PRIMARY KEY (ID_VERSAO_PROMPT),

    CONSTRAINT UK_CIA_VERSAO_PROMPT
        UNIQUE (
            ID_PROMPT,
            NUMR_VERSAO
        ),

    CONSTRAINT FK_CIA_VERSAO_PROMPT
        FOREIGN KEY (ID_PROMPT)
        REFERENCES CIA_PROMPT (ID_PROMPT)
        ON DELETE CASCADE,

    CONSTRAINT FK_CIA_VERSAO_PROMPT_APROV
        FOREIGN KEY (ID_USUARIO_APROVACAO)
        REFERENCES CIA_USUARIO (ID_USUARIO)
        ON DELETE SET NULL
)


CREATE SEQUENCE SEQ_CIA_VERSAO_PROMPT
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_VERSAO_PROMPT
BEFORE INSERT ON CIA_VERSAO_PROMPT
FOR EACH ROW
BEGIN
    IF :NEW.ID_VERSAO_PROMPT IS NULL THEN
        SELECT SEQ_CIA_VERSAO_PROMPT.NEXTVAL
          INTO :NEW.ID_VERSAO_PROMPT
          FROM DUAL
    END IF
END


CREATE INDEX IDX_CIA_VERSAO_PROMPT
    ON CIA_VERSAO_PROMPT (
        ID_PROMPT,
        NUMR_VERSAO DESC
    )


COMMENT ON TABLE CIA_VERSAO_PROMPT IS
'Tabela responsável pelo armazenamento das versões dos prompts cadastrados na plataforma.'

COMMENT ON COLUMN CIA_VERSAO_PROMPT.ID_VERSAO_PROMPT IS
'Identificador único da versão do prompt cadastrada.'

COMMENT ON COLUMN CIA_VERSAO_PROMPT.ID_PROMPT IS
'Identificador do prompt associado à versão registrada.'

COMMENT ON COLUMN CIA_VERSAO_PROMPT.NUMR_VERSAO IS
'Número sequencial da versão do prompt.'

COMMENT ON COLUMN CIA_VERSAO_PROMPT.TITULO_PROMPT IS
'Título do prompt correspondente à versão registrada.'

COMMENT ON COLUMN CIA_VERSAO_PROMPT.DESC_PROMPT IS
'Descrição resumida do prompt na versão cadastrada.'

COMMENT ON COLUMN CIA_VERSAO_PROMPT.DESC_CONTEUDO IS
'Conteúdo completo do prompt na versão registrada.'

COMMENT ON COLUMN CIA_VERSAO_PROMPT.INFO_VARIAVEL IS
'Lista estruturada das variáveis utilizadas no prompt armazenada em formato JSON.'

COMMENT ON COLUMN CIA_VERSAO_PROMPT.TAG IS
'Lista de etiquetas associadas à versão do prompt armazenada em formato JSON.'

COMMENT ON COLUMN CIA_VERSAO_PROMPT.ID_USUARIO_APROVACAO IS
'Identificador do usuário responsável pela aprovação da versão do prompt.'

COMMENT ON COLUMN CIA_VERSAO_PROMPT.DATA_APROVACAO IS
'Data e hora da aprovação da versão do prompt.'
