CREATE TABLE CIA_PROMPT_VERSAO (
    ID_PROMPT_VERSAO NUMBER(10) NOT NULL,

    ID_PROMPT NUMBER(10) NOT NULL,

    NUMR_VERSAO NUMBER(10) NOT NULL,

    TITULO_PROMPT VARCHAR2(300 CHAR) NOT NULL,

    DESC_PROMPT CLOB DEFAULT '' NOT NULL,

    DESC_CONTEUDO CLOB NOT NULL,

    INFO_VARIAVEL CLOB DEFAULT '[]' NOT NULL,

    TAG CLOB DEFAULT '[]' NOT NULL,

    ID_USUARIO_APROVACAO NUMBER(10),

    DATA_APROVACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_CIA_PROMPT_VERSAO
        PRIMARY KEY (ID_PROMPT_VERSAO),

    CONSTRAINT UK_CIA_PROMPT_VERSAO
        UNIQUE (
            ID_PROMPT,
            NUMR_VERSAO
        ),

    CONSTRAINT FK_CIA_PROMPT_VERSAO
        FOREIGN KEY (ID_PROMPT)
        REFERENCES CIA_PROMPT (ID_PROMPT)
        ON DELETE CASCADE,

    CONSTRAINT FK_CIA_PROMPT_VERSAO_APROV
        FOREIGN KEY (ID_USUARIO_APROVACAO)
        REFERENCES CIA_USUARIO (ID_USUARIO)
        ON DELETE SET NULL
)


CREATE SEQUENCE SEQ_CIA_PROMPT_VERSAO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_PROMPT_VERSAO
BEFORE INSERT ON CIA_PROMPT_VERSAO
FOR EACH ROW
BEGIN
    IF :NEW.ID_PROMPT_VERSAO IS NULL THEN
        SELECT SEQ_CIA_PROMPT_VERSAO.NEXTVAL
          INTO :NEW.ID_PROMPT_VERSAO
          FROM DUAL
    END IF
END


CREATE INDEX IDX_CIA_PROMPT_VERSAO
    ON CIA_PROMPT_VERSAO (
        ID_PROMPT,
        NUMR_VERSAO DESC
    )


COMMENT ON TABLE CIA_PROMPT_VERSAO IS
'Tabela responsável pelo armazenamento das versões dos prompts cadastrados na plataforma.'

COMMENT ON COLUMN CIA_PROMPT_VERSAO.ID_PROMPT_VERSAO IS
'Identificador único da versão do prompt cadastrada.'

COMMENT ON COLUMN CIA_PROMPT_VERSAO.ID_PROMPT IS
'Identificador do prompt associado à versão registrada.'

COMMENT ON COLUMN CIA_PROMPT_VERSAO.NUMR_VERSAO IS
'Número sequencial da versão do prompt.'

COMMENT ON COLUMN CIA_PROMPT_VERSAO.TITULO_PROMPT IS
'Título do prompt correspondente à versão registrada.'

COMMENT ON COLUMN CIA_PROMPT_VERSAO.DESC_PROMPT IS
'Descrição resumida do prompt na versão cadastrada.'

COMMENT ON COLUMN CIA_PROMPT_VERSAO.DESC_CONTEUDO IS
'Conteúdo completo do prompt na versão registrada.'

COMMENT ON COLUMN CIA_PROMPT_VERSAO.INFO_VARIAVEL IS
'Lista estruturada das variáveis utilizadas no prompt armazenada em formato JSON.'

COMMENT ON COLUMN CIA_PROMPT_VERSAO.TAG IS
'Lista de etiquetas associadas à versão do prompt armazenada em formato JSON.'

COMMENT ON COLUMN CIA_PROMPT_VERSAO.ID_USUARIO_APROVACAO IS
'Identificador do usuário responsável pela aprovação da versão do prompt.'

COMMENT ON COLUMN CIA_PROMPT_VERSAO.DATA_APROVACAO IS
'Data e hora da aprovação da versão do prompt.'
