CREATE TABLE CIA_FORNECEDOR (
    ID_FORNECEDOR NUMBER(10) NOT NULL,
    NOME_FORNECEDOR VARCHAR2(200 CHAR) NOT NULL,

    CONSTRAINT PK_CIA_FORNECEDOR PRIMARY KEY (ID_FORNECEDOR),

    CONSTRAINT UK_CIA_FORNECEDOR_NOME  UNIQUE (NOME_FORNECEDOR)
)


CREATE SEQUENCE SEQ_CIA_FORNECEDOR
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_CIA_FORNECEDOR
BEFORE INSERT ON CIA_FORNECEDOR
FOR EACH ROW
BEGIN
    IF :NEW.ID_FORNECEDOR IS NULL THEN
    SELECT SEQ_CIA_FORNECEDOR.NEXTVAL
    INTO :NEW.ID_FORNECEDOR
          FROM DUAL
    END IF
END



COMMENT ON TABLE CIA_FORNECEDOR IS
'Tabela responsável pelo cadastro dos forcedores de modelos e serviços de inteligência artificial utilizados pela plataforma.'

COMMENT ON COLUMN CIA_FORNECEDOR.ID_FORNECEDOR IS
'Identificador único do forcedor cadastrado.'

COMMENT ON COLUMN CIA_FORNECEDOR.NOME_FORNECEDOR IS
'Nome do forcedor responsável pelos modelos ou serviços de inteligência artificial.'
