CREATE TABLE USUARIO_SISTEMA (
    CODG_USUARIO NUMBER(32) NOT NULL

    CONSTRAINT PK_USUARIO_SISTEMA PRIMARY KEY (CODG_USUARIO),
)


CREATE SEQUENCE SEQ_USUARIO_SISTEMA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_USUARIO_SISTEMA
BEFORE INSERT ON USUARIO_SISTEMA
FOR EACH ROW
BEGIN
    IF :NEW.CODG_USUARIO IS NULL THEN
        SELECT SEQ_USUARIO_SISTEMA.NEXTVAL
          INTO :NEW.CODG_USUARIO
          FROM DUAL
    END IF
END



CREATE OR REPLACE TRIGGER TRG_BU_USUARIO_SISTEMA
BEFORE UPDATE ON USUARIO_SISTEMA
FOR EACH ROW
BEGIN
    :NEW.DATA_ATUALIZACAO := CURRENT_TIMESTAMP
END

COMMENT ON TABLE USUARIO_SISTEMA IS
'Tabela responsável pelo cadastro e gerenciamento dos usuários da plataforma.'

COMMENT ON COLUMN USUARIO_SISTEMA.CODG_USUARIO IS
'Identificador único do usuário cadastrado.'

