CREATE TABLE USUARIO_SISTEMA (
    CODG_USUARIO NUMBER(32) NOT NULL,
    NOME_USUARIO VARCHAR2(200 CHAR) NOT NULL,
    DESC_EMAIL VARCHAR2(200 CHAR) NOT NULL,
    CODG_USUARIO VARCHAR2(32 CHAR),
    TIPO_PERFIL VARCHAR2(2 CHAR) DEFAULT 'SV' NOT NULL,
    NOME_ORGAO VARCHAR2(200 CHAR) DEFAULT '' NOT NULL,
    JSON_AVATAR BLOB,
    INDI_ATIVO VARCHAR2(1 CHAR) DEFAULT 'S' NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_USUARIO_SISTEMA PRIMARY KEY (CODG_USUARIO),
)


CREATE SEQUENCE SEQ_USUARIO_SISTEMA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE


CREATE OR REPLACE TRIGGER TRG_BI_USUARIO_SISTEMA
BEFORE INSERT ON USUARIO_SISTEMA
FOR EACH ROW
BEGIN
    IF :NEW.CODG_USUARIO IS NULL THEN
        SELECT SEQ_USUARIO_SISTEMA.NEXTVAL
          INTO :NEW.CODG_USUARIO
          FROM DUAL
    END IF
END



CREATE OR REPLACE TRIGGER TRG_BU_USUARIO_SISTEMA
BEFORE UPDATE ON USUARIO_SISTEMA
FOR EACH ROW
BEGIN
    :NEW.DATA_ATUALIZACAO := CURRENT_TIMESTAMP
END

COMMENT ON TABLE USUARIO_SISTEMA IS
'Tabela responsável pelo cadastro e gerenciamento dos usuários da plataforma.'

COMMENT ON COLUMN USUARIO_SISTEMA.CODG_USUARIO IS
'Identificador único do usuário cadastrado.'

COMMENT ON COLUMN USUARIO_SISTEMA.NOME_USUARIO IS
'Nome completo do usuário cadastrado na plataforma.'

COMMENT ON COLUMN USUARIO_SISTEMA.DESC_EMAIL IS
'Endereço de e-mail utilizado pelo usuário para autenticação e comunicação.'

COMMENT ON COLUMN USUARIO_SISTEMA.CODG_USUARIO IS
'Código identificador interno do usuário na plataforma ou organização.'

COMMENT ON COLUMN USUARIO_SISTEMA.TIPO_PERFIL IS
'Perfil de acesso do usuário na plataforma. AD = Administrador, GT = Gestor, SV = Servidor, CR = Curador, CM = Curador de Modelos, GP = Gestor de Produto.'

