#!/usr/bin/env python3
"""Converte migrações Oracle (docs/migrations_oracle) para PostgreSQL."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ORACLE_DIR = ROOT / "docs" / "migrations_oracle"
POSTGRES_DIR = ROOT / "docs" / "migrations_postgres"

BI_TRIGGER_RE = re.compile(
    r"CREATE OR REPLACE TRIGGER (?P<trigger>\w+)\s+"
    r"BEFORE INSERT ON (?P<table>\w+)\s+"
    r"FOR EACH ROW\s+"
    r"BEGIN\s+"
    r"IF :NEW\.(?P<column>\w+) IS NULL THEN\s+"
    r"SELECT (?P<sequence>\w+)\.NEXTVAL\s+"
    r"INTO :NEW\.\w+\s+"
    r"FROM DUAL\s+"
    r"END IF\s+"
    r"END",
    re.IGNORECASE | re.DOTALL,
)

BU_TRIGGER_RE = re.compile(
    r"CREATE OR REPLACE TRIGGER (?P<trigger>\w+)\s+"
    r"BEFORE UPDATE ON (?P<table>\w+)\s+"
    r"FOR EACH ROW\s+"
    r"BEGIN\s+"
    r":NEW\.(?P<column>\w+) := CURRENT_TIMESTAMP\s+"
    r"END",
    re.IGNORECASE | re.DOTALL,
)


def convert_doc_block(lines: list[str]) -> list[str]:
    result: list[str] = []
    for line in lines:
        stripped = line.strip()
        if not stripped:
            result.append("")
            continue
        if stripped.startswith("--"):
            result.append(line)
            continue
        result.append(f"-- {line.rstrip()}")
    return result


def convert_types(sql: str) -> str:
    sql = re.sub(
        r"VARCHAR2\s*\(\s*(\d+)\s+CHAR\s*\)",
        r"VARCHAR(\1)",
        sql,
        flags=re.IGNORECASE,
    )
    sql = re.sub(r"\bCLOB\b", "TEXT", sql, flags=re.IGNORECASE)
    sql = re.sub(
        r"NUMBER\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)",
        r"NUMERIC(\1,\2)",
        sql,
        flags=re.IGNORECASE,
    )
    sql = re.sub(r"NUMBER\s*\(\s*(\d+)\s*\)", r"INTEGER", sql, flags=re.IGNORECASE)
    sql = re.sub(r"\bNUMBER\b", "INTEGER", sql, flags=re.IGNORECASE)
    sql = re.sub(
        r"TIMESTAMP\s*\(\s*(\d+)\s*\)",
        r"TIMESTAMPTZ(\1)",
        sql,
        flags=re.IGNORECASE,
    )
    sql = re.sub(r"\bTIMESTAMP\b(?!\()", "TIMESTAMPTZ", sql, flags=re.IGNORECASE)
    return sql


def apply_identity_columns(sql: str, identity_columns: set[tuple[str, str]]) -> str:
    for _table, column in identity_columns:
        pattern = re.compile(
            rf"(\b{column}\s+)INTEGER(\s+NOT NULL)",
            re.IGNORECASE,
        )
        sql = pattern.sub(
            rf"\1INTEGER GENERATED BY DEFAULT AS IDENTITY\2",
            sql,
            count=1,
        )
    return sql


def remove_bi_triggers_and_sequences(sql: str, bi_triggers: list[re.Match[str]]) -> str:
    for match in bi_triggers:
        sql = sql.replace(match.group(0), "")

    for match in bi_triggers:
        sequence = match.group("sequence")
        sql = re.sub(
            rf"CREATE SEQUENCE {sequence}\s+.*?(?=\n\n|\nCREATE|\nCOMMENT|\nINSERT|\Z)",
            "",
            sql,
            flags=re.IGNORECASE | re.DOTALL,
        )
    return sql


def convert_bu_triggers(sql: str, bu_triggers: list[re.Match[str]]) -> tuple[str, list[str]]:
    extra: list[str] = []
    for match in bu_triggers:
        trigger_name = match.group("trigger").lower()
        table = match.group("table").lower()
        column = match.group("column").lower()
        function_name = f"{trigger_name}_fn"

        extra.extend(
            [
                f"CREATE OR REPLACE FUNCTION {function_name}()",
                "RETURNS TRIGGER AS $$",
                "BEGIN",
                f"  NEW.{column} = CURRENT_TIMESTAMP;",
                "  RETURN NEW;",
                "END;",
                "$$ LANGUAGE plpgsql;",
                "",
                f"CREATE TRIGGER {trigger_name}",
                f"  BEFORE UPDATE ON {table}",
                f"  FOR EACH ROW EXECUTE FUNCTION {function_name}();",
                "",
            ]
        )
        sql = sql.replace(match.group(0), "")

    return sql, extra


def add_semicolons(sql: str) -> str:
    sql = re.sub(
        r"(\)\s*\n)(\s*\n(?:CREATE |COMMENT |INSERT |CREATE OR))",
        r"\1;\n\2",
        sql,
        flags=re.IGNORECASE,
    )
    sql = re.sub(
        r"(CREATE INDEX [^\n]+\))(\s*\n)",
        r"\1;\2",
        sql,
        flags=re.IGNORECASE,
    )
    sql = re.sub(
        r"(COMMENT ON (?:TABLE|COLUMN) \S+ IS\s*\n'[^'\n]*'(?!\s*;))",
        r"\1;",
        sql,
        flags=re.IGNORECASE,
    )
    sql = re.sub(
        r"^(INSERT INTO .+?)(?<!\;)$",
        r"\1;",
        sql,
        flags=re.IGNORECASE | re.MULTILINE,
    )
    sql = re.sub(
        r"(EXECUTE FUNCTION \w+\(\))(\s*\n)",
        r"\1;\2",
        sql,
        flags=re.IGNORECASE,
    )
    return sql


def normalize_whitespace(sql: str) -> str:
    sql = re.sub(r"[ \t]+\n", "\n", sql)
    sql = re.sub(r"\n{3,}", "\n\n", sql)
    return sql.strip()


def split_doc_and_sql(content: str) -> tuple[list[str], str]:
    lines = content.splitlines()
    doc_lines: list[str] = []
    sql_start = 0

    for idx, line in enumerate(lines):
        stripped = line.strip()
        if not stripped:
            if doc_lines:
                doc_lines.append(line)
            continue

        upper = stripped.upper()
        if upper.startswith(("CREATE", "COMMENT", "INSERT", "ALTER", "DROP")):
            sql_start = idx
            break
        doc_lines.append(line)
    else:
        return convert_doc_block(doc_lines), content

    return convert_doc_block(doc_lines), "\n".join(lines[sql_start:])


def convert_file(content: str) -> str:
    doc_block, sql = split_doc_and_sql(content)

    bi_triggers = list(BI_TRIGGER_RE.finditer(sql))
    bu_triggers = list(BU_TRIGGER_RE.finditer(sql))

    identity_columns = {
        (match.group("table"), match.group("column")) for match in bi_triggers
    }

    sql = convert_types(sql)
    sql = apply_identity_columns(sql, identity_columns)
    sql = remove_bi_triggers_and_sequences(sql, bi_triggers)
    sql, bu_blocks = convert_bu_triggers(sql, bu_triggers)
    sql = normalize_whitespace(sql)
    sql = add_semicolons(sql)

    parts: list[str] = []
    if doc_block:
        parts.extend(line for line in doc_block if line is not None)
        if parts and parts[-1].strip():
            parts.append("")

    parts.append(sql)
    if bu_blocks:
        parts.append("")
        parts.extend(bu_blocks)

    result = "\n".join(parts).strip() + "\n"
    result = re.sub(r"\n{3,}", "\n\n", result)
    return result


def main() -> None:
    POSTGRES_DIR.mkdir(parents=True, exist_ok=True)

    oracle_files = sorted(ORACLE_DIR.glob("*.sql"))
    if not oracle_files:
        raise SystemExit(f"Nenhum arquivo encontrado em {ORACLE_DIR}")

    for oracle_path in oracle_files:
        content = oracle_path.read_text(encoding="utf-8")
        converted = convert_file(content)
        target = POSTGRES_DIR / oracle_path.name
        target.write_text(converted, encoding="utf-8")
        print(f"Convertido: {oracle_path.name}")

    print(f"\n{len(oracle_files)} migrações geradas em {POSTGRES_DIR}")


if __name__ == "__main__":
    main()
