-- Criar o schema do projeto

CREATE USER CIA_OWNER IDENTIFIED BY "SenhaForte123";

GRANT CONNECT TO CIA_OWNER;
GRANT RESOURCE TO CIA_OWNER;
GRANT UNLIMITED TABLESPACE TO CIA_OWNER;

CREATE SEQUENCE SEQ_SUA_TABELA_ID
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;


-- 👤 CIA_USUARIO
CREATE TABLE CIA_USUARIO (
  ID_USUARIO      NUMBER DEFAULT SEQ_SUA_TABELA_ID.NEXTVAL PRIMARY KEY,
  STAT_ATIVO      CHAR(1) DEFAULT 'S' CHECK (STAT_ATIVO IN ('S','N')),
  DATA_CRIACAO    TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 🤖 CIA_AGENTE_IA

CREATE TABLE CIA_AGENTE_IA (
  ID_AGENTE_IA            NUMBER DEFAULT SEQ_SUA_TABELA_ID.NEXTVAL PRIMARY KEY,
  NOME_AGENTE_IA          VARCHAR2(200) NOT NULL,
  DESC_AGENTE_IA          CLOB NOT NULL,
  DESC_RESUMO_AGENTE_IA   VARCHAR2(500),
  DESC_ICONE              VARCHAR2(100),
  TIPO_DESENVOLVEDOR      VARCHAR2(100),
  INFO_WEBHOOK_URL        VARCHAR2(500),
  INDI_DESTAQUE           CHAR(1) DEFAULT 'N' CHECK (INDI_DESTAQUE IN ('S','N')),
  INDI_ATIVO              CHAR(1) DEFAULT 'S' CHECK (INDI_ATIVO IN ('S','N')),
  QTDE_UTILIZACAO         NUMBER DEFAULT 0,
  DATA_CRIACAO            TIMESTAMP DEFAULT SYSTIMESTAMP,
  ID_CATEGORIA            NUMBER NOT NULL,

  CONSTRAINT FK_CIA_AGENTE_CATEGORIA  FOREIGN KEY (ID_CATEGORIA) REFERENCES CIA_CATEGORIA (ID_CATEGORIA)
);

-- ⭐ CIA_FAVORITO_AGENTE

CREATE TABLE CIA_FAVORITO_AGENTE (
  ID_FAVORITO_AGENTE  NUMBER DEFAULT SEQ_SUA_TABELA_ID.NEXTVAL PRIMARY KEY,
  ID_USUARIO          NUMBER NOT NULL,
  ID_AGENTE_IA        NUMBER NOT NULL,
  STAT_AGENTE         CHAR(1) DEFAULT 'S' CHECK (STAT_AGENTE IN ('S','N')),
  DATA_CRIACAO        TIMESTAMP DEFAULT SYSTIMESTAMP,

  CONSTRAINT FK_FAV_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES CIA_USUARIO (ID_USUARIO),
  CONSTRAINT FK_FAV_AGENTE FOREIGN KEY (ID_AGENTE_IA) REFERENCES CIA_AGENTE_IA (ID_AGENTE_IA),
  CONSTRAINT UK_FAVORITO UNIQUE (ID_USUARIO, ID_AGENTE_IA)
);

-- 🧠 CIA_MODELO_IA

CREATE TABLE CIA_MODELO_IA (
  ID_MODELO_IA                NUMBER DEFAULT SEQ_SUA_TABELA_ID.NEXTVAL PRIMARY KEY,
  NOME_MODELO_IA              VARCHAR2(200) NOT NULL,
  NOME_DESENVOLVEDOR          VARCHAR2(200),
  STAT_MODELO_IA              CHAR(1) DEFAULT 'S'
    CHECK (STAT_MODELO_IA IN ('S','N')),
  DESC_TIPO_MODELO            VARCHAR2(200),
  DESC_PARAMETRO              CLOB,
  DESC_FUNCIONAL_MODELO       CLOB,
  DESC_JANELA_CONTEXTO        VARCHAR2(100),
  DESC_MAXIMO_SAIDA           VARCHAR2(100),
  DESC_CUSTO_TOKEN_ENTRADA    VARCHAR2(100),
  DESC_CUSTO_TOKEN_SAIDA      VARCHAR2(100),
  DATA_CORTE_CONHECIMENTO     DATE,
  DATA_LANCAMENTO             DATE,
  INFO_FUNCDE                 VARCHAR2(200),
  INFO_WEBHOOK_URL            VARCHAR2(500),
  INFO_CONFIGURACAO_CHAT      CLOB,
  DATA_CRIACAO                TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 📚 CIA_INSTRUCAO

CREATE TABLE CIA_INSTRUCAO (
  ID_INSTRUCAO       NUMBER DEFAULT SEQ_SUA_TABELA_ID.NEXTVAL PRIMARY KEY,
  NOME_TITULO        VARCHAR2(300) NOT NULL,
  DESC_INSTRUCAO     CLOB NOT NULL,
  INDI_PUBLICO       CHAR(1) DEFAULT 'N'
    CHECK (INDI_PUBLICO IN ('S','N')),
  INDI_PUBLICADO     CHAR(1) DEFAULT 'N'
    CHECK (INDI_PUBLICADO IN ('S','N')),
  INDI_OFICIAL       CHAR(1) DEFAULT 'N'
    CHECK (INDI_OFICIAL IN ('S','N')),
  DATA_CRIACAO       TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 📝 CIA_INSTRUCAO_VERSAO

CREATE TABLE CIA_INSTRUCAO_VERSAO (
  ID_INSTRUCAO_VERSAO NUMBER DEFAULT SEQ_SUA_TABELA_ID.NEXTVAL PRIMARY KEY,
  ID_INSTRUCAO        NUMBER NOT NULL,
  NUMR_VERSAO         NUMBER NOT NULL,
  DESC_CONTEUDO       CLOB NOT NULL,
  DESC_ALTERACAO      VARCHAR2(500),
  DATA_CRIACAO        TIMESTAMP DEFAULT SYSTIMESTAMP,

  CONSTRAINT FK_INST_VERSAO
    FOREIGN KEY (ID_INSTRUCAO)
    REFERENCES CIA_INSTRUCAO (ID_INSTRUCAO)
);

-- 📂 CIA_DOCUMENTACAO_CATEGORIA

CREATE TABLE CIA_DOCUMENTACAO_CATEGORIA (
  ID_DOCUMENTACAO_CATEGORIA NUMBER DEFAULT SEQ_SUA_TABELA_ID.NEXTVAL PRIMARY KEY,
  NOME_CATEGORIA            VARCHAR2(200) NOT NULL,
  DESC_ICONE                VARCHAR2(100),
  DESC_CATEGORIA            VARCHAR2(500),
  NUMR_ORDEM_EXIBICAO       NUMBER NOT NULL
);

-- 📘 CIA_DOCUMENTACAO

CREATE TABLE CIA_DOCUMENTACAO (
  ID_DOCUMENTACAO            NUMBER DEFAULT SEQ_SUA_TABELA_ID.NEXTVAL PRIMARY KEY,
  ID_DOCUMENTACAO_CATEGORIA  NUMBER NOT NULL,
  NOME_TITULO                VARCHAR2(300) NOT NULL,
  DESC_DOCUMENTACAO          CLOB NOT NULL,
  DESC_ICONE                 VARCHAR2(100),
  DESC_CONTEUDO              CLOB,
  INDI_GUIA_RAPIDO           CHAR(1) DEFAULT 'N'     CHECK (INDI_GUIA_RAPIDO IN ('S','N')),
  INDI_PUBLICADO             CHAR(1) DEFAULT 'N' CHECK (INDI_PUBLICADO IN ('S','N')),
  NUMR_ORDEM_EXIBICAO        NUMBER,
  INFO_TOPICO                VARCHAR2(200),

  CONSTRAINT FK_DOC_CATEGORIA  FOREIGN KEY (ID_DOCUMENTACAO_CATEGORIA) 
   REFERENCES CIA_DOCUMENTACAO_CATEGORIA (ID_DOCUMENTACAO_CATEGORIA)
);

-- 📰 CIA_NOTICIA

CREATE TABLE CIA_NOTICIA (
  ID_NOTICIA     NUMBER DEFAULT SEQ_SUA_TABELA_ID.NEXTVAL PRIMARY KEY,
  NOME_TITULO    VARCHAR2(300) NOT NULL,
  DESC_CONTEUDO  CLOB NOT NULL,
  INDI_PUBLICADO CHAR(1) DEFAULT 'N' CHECK (INDI_PUBLICADO IN ('S','N')),
  DATA_CRIACAO   TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 🏷️ CIA_CATEGORIA

CREATE TABLE CIA_CATEGORIA (
  ID_CATEGORIA   NUMBER DEFAULT SEQ_SUA_TABELA_ID.NEXTVAL PRIMARY KEY,
  NOME_CATEGORIA VARCHAR2(200) NOT NULL,
  CODG_COR       VARCHAR2(20)
);
