@startuml
' DER gerado a partir de docs/migrations_oracle
' Validacao: CIA_MODELO duplicada em 002_modelos.sql e 029_modelo.sql; usada 002_modelos.sql por manter FK para tabela existente CIA_FORNECEDOR.
hide circle
skinparam linetype ortho
skinparam class {
  BackgroundColor White
  BorderColor Black
  ArrowColor Black
}
entity "CIA_CATEGORIA_MODELO" as CIA_CATEGORIA_MODELO {
  * ID_CATEGORIA_MODELO : PK
  * NOME_CATEGORIA_MODELO : 
}
entity "CIA_MODELO" as CIA_MODELO {
  * ID_MODELO : PK
  * NOME_MODELO : 
  * SLUG_MODELO : 
  * ID_CATEGORIA_MODELO : FK
  * DESC_MODELO : 
  o INFO_CAPABILIDADE : 
  * STAT_MODELO : 
  o QTDE_JANELA_CONTEXTO : 
  o INFO_LIMITE_USO : 
  o TAG : 
  * INDI_NOVO : 
  * INDI_DESTAQUE : 
  * INDI_ATIVO : 
  * NUMR_ORDEM : 
  * DATA_CRIACAO : 
  * DATA_ATUALIZACAO : 
  * INDI_APROVACAO_ACESSO : 
  * DESC_RESUMO_ACESSO : 
  * DESC_DOCUMENTACAO_ACESSO : 
  o INFO_ENDPOINT_PADRAO : 
  * TIPO_AUTENTICACAO_PADRAO : 
  o ID_FORNECEDOR : FK
}
entity "CIA_FUNCIONALIDADE" as CIA_FUNCIONALIDADE {
  * CHAVE_FUNCIONALIDADE : PK
  * NOME_FUNCIONALIDADE : 
  o DESC_FUNCIONALIDADE : 
  * AREA_FUNCIONALIDADE : 
  o NOME_MENU : 
  o CAMINHO_MENU : 
  * NUMR_ORDEM : 
  * INDI_ATIVO : 
  * INDI_SISTEMA : 
  * DATA_CRIACAO : 
  * DATA_ATUALIZACAO : 
}
entity "CIA_LOG_AUDITORIA" as CIA_LOG_AUDITORIA {
  * ID_LOG_AUDITORIA : PK
  o ID_USUARIO : FK
  * ACAO_AUDITORIA : 
  * NOME_ENTIDADE : 
  o ID_ENTIDADE : 
  o INFO_METADADO : 
  o INFO_ENDERECO_IP : 
  * DATA_CRIACAO : 
  o INFO_USER_AGENT : 
}
entity "CIA_BANCO_QUESTAO" as CIA_BANCO_QUESTAO {
  * ID_BANCO_QUESTAO : PK
  o ID_METRICA : FK
  * INFO_PERGUNTA : 
  * INFO_GABARITO : 
}
entity "CIA_CARTA_SERVICO" as CIA_CARTA_SERVICO {
  * ID_CARTA_SERVICO : PK
  * DESC_CONTEUDO : 
  * INFO_METADADO : 
  o INFO_EMBEDDING : 
}
entity "CIA_ARTIGO_DOCUMENTACAO" as CIA_ARTIGO_DOCUMENTACAO {
  * ID_ARTIGO_DOCUMENTACAO : PK
  o ID_SECAO_DOCUMENTACAO : FK
  * NOME_ARTIGO : 
  * SLUG_ARTIGO : 
  * DESC_CONTEUDO : 
  * QTDE_TEMPO_LEITURA : 
  * NUMR_ORDEM : 
  o ID_USUARIO_AUTOR : FK
  * INDI_PUBLICADO : 
  * INDI_ATIVO : 
  * DATA_CRIACAO : 
  * DATA_ATUALIZACAO : 
}
entity "CIA_SECAO_DOCUMENTACAO" as CIA_SECAO_DOCUMENTACAO {
  * ID_SECAO_DOCUMENTACAO : PK
  * NOME_SECAO : 
  * SLUG_SECAO : 
  * NUMR_ORDEM : 
  o ID_SECAO_PAI : FK
  * INDI_ATIVO : 
}
entity "CIA_REACAO_COMENTARIO_IDEIA" as CIA_REACAO_COMENTARIO_IDEIA {
  * ID_COMENTARIO_IDEIA : PK FK
  * ID_USUARIO : PK FK
  * TIPO_REACAO : 
  * DATA_CRIACAO : 
}
entity "CIA_COMENTARIO_IDEIA" as CIA_COMENTARIO_IDEIA {
  * ID_COMENTARIO_IDEIA : PK
  * ID_IDEIA : FK
  o ID_COMENTARIO_PAI : FK
  * ID_USUARIO_AUTOR : FK
  * DESC_CONTEUDO : 
  * STAT_MODERACAO : 
  o DESC_MOTIVO_MODERACAO : 
  o ID_USUARIO_MODERADOR : FK
  o DATA_MODERACAO : 
  * DATA_CRIACAO : 
  * DATA_ATUALIZACAO : 
}
entity "CIA_VINCULO_IDEIA_TOPICO" as CIA_VINCULO_IDEIA_TOPICO {
  * ID_IDEIA : PK FK
  * ID_TOPICO_IDEIA : PK FK
}
entity "CIA_TOPICO_IDEIA" as CIA_TOPICO_IDEIA {
  * ID_TOPICO_IDEIA : PK
  * NOME_TOPICO : 
  * SLUG_TOPICO : 
  * COR_TOPICO : 
  o NOME_ICONE : 
  o DESC_TOPICO : 
  * NUMR_ORDEM : 
  * INDI_ATIVO : 
  * DATA_CRIACAO : 
  * DATA_ATUALIZACAO : 
}
entity "CIA_VERSAO_IDEIA" as CIA_VERSAO_IDEIA {
  * ID_VERSAO_IDEIA : PK
  * NOME_VERSAO : 
  o DESC_VERSAO : 
  o INFO_PREVISAO : 
  * NUMR_ORDEM : 
  * INDI_ATIVO : 
  o ID_USUARIO_CRIACAO : FK
  * DATA_CRIACAO : 
  * DATA_ATUALIZACAO : 
}
entity "CIA_VOTO_IDEIA" as CIA_VOTO_IDEIA {
  * ID_IDEIA : PK FK
  * ID_USUARIO : PK FK
  * DATA_CRIACAO : 
}
entity "CIA_IDEIA" as CIA_IDEIA {
  * ID_IDEIA : PK
  * NOME_IDEIA : 
  * DESC_IDEIA : 
  * ID_USUARIO_AUTOR : FK
  * STAT_MODERACAO : 
  o STAT_IDEIA : 
  o ID_VERSAO_IDEIA : FK
  o DESC_CURADORIA : 
  o DESC_MOTIVO_REJEICAO : 
  o DATA_SOLICITACAO_EXCLUSAO : 
  o DESC_MOTIVO_SOLIC_EXCLUSAO : 
  o DATA_EXCLUSAO : 
  o DATA_PUBLICACAO : 
  o ID_USUARIO_REVISAO : FK
  o DATA_REVISAO : 
  * DATA_CRIACAO : 
  * DATA_ATUALIZACAO : 
}
entity "CIA_INDICADOR" as CIA_INDICADOR {
  * ID_INDICADOR : PK
  * DATA_CRIACAO : 
  * VALR_INDICADOR : 
  o ID_MODELO : FK
  o ID_METRICA : FK
}
entity "CIA_AGENTE_MCP" as CIA_AGENTE_MCP {
  * ID_AGENTE_MCP : PK
  * ID_SERVIDOR_MCP : FK
  * NOME_AGENTE : 
  * DESC_AGENTE : 
  * INFO_CAPACIDADE : 
  o NOME_MODELO_BASE : 
  o DESC_PROMPT_SISTEMA : 
  * NUMR_ORDEM : 
}
entity "CIA_CATEGORIA_MCP" as CIA_CATEGORIA_MCP {
  * ID_CATEGORIA_MCP : PK
  * NOME_CATEGORIA : 
  * SLUG_CATEGORIA : 
  * DESC_CATEGORIA : 
  * NOME_ICONE : 
  * CODG_COR : 
  * NUMR_ORDEM : 
  * INDI_ATIVO : 
}
entity "CIA_CONFIGURACAO_MCP" as CIA_CONFIGURACAO_MCP {
  * ID_CONFIGURACAO_MCP : PK
  * ID_SERVIDOR_MCP : FK
  * TIPO_CLIENTE : 
  * NOME_CONFIGURACAO : 
  * INFO_CONFIGURACAO : 
  o DESC_OBSERVACAO : 
  * NUMR_ORDEM : 
}
entity "CIA_FAVORITO_MCP" as CIA_FAVORITO_MCP {
  * ID_USUARIO : PK FK
  * ID_SERVIDOR_MCP : PK FK
  * DATA_CRIACAO : 
}
entity "CIA_INSTALACAO_MCP" as CIA_INSTALACAO_MCP {
  * ID_INSTALACAO_MCP : PK
  * ID_SERVIDOR_MCP : FK
  * ID_USUARIO : FK
  o TIPO_CLIENTE : 
  * DATA_INSTALACAO : 
}
entity "CIA_RECURSO_MCP" as CIA_RECURSO_MCP {
  * ID_RECURSO_MCP : PK
  * ID_SERVIDOR_MCP : FK
  * NOME_RECURSO : 
  * URI_TEMPLATE : 
  * DESC_RECURSO : 
  o TIPO_MIME : 
  * NUMR_ORDEM : 
}
entity "CIA_AVALIACAO_MCP" as CIA_AVALIACAO_MCP {
  * ID_AVALIACAO_MCP : PK
  * ID_SERVIDOR_MCP : FK
  * ID_USUARIO : FK
  * NUMR_AVALIACAO : 
  o DESC_COMENTARIO : 
  * INDI_APROVADO : 
  * DATA_CRIACAO : 
}
entity "CIA_SERVIDOR_MCP" as CIA_SERVIDOR_MCP {
  * ID_SERVIDOR_MCP : PK
  * NOME_SERVIDOR : 
  * SLUG_SERVIDOR : 
  * DESC_RESUMIDA : 
  * DESC_SERVIDOR : 
  o ID_CATEGORIA_MCP : FK
  * STAT_SERVIDOR : 
  * INDI_VERIFICADO : 
  * INDI_DESTAQUE : 
  * INDI_OFICIAL : 
  o URL_REPOSITORIO : 
  o URL_DOCUMENTACAO : 
  o URL_HOMEPAGE : 
  o NUMR_VERSAO : 
  o NOME_LICENCA : 
  * INFO_MODELOS_COMPATIVEIS : 
  * VALR_MEDIA_AVALIACAO : 
  * QTDE_AVALIACAO : 
  * QTDE_INSTALACAO : 
  o NOME_AUTOR : 
  o NOME_ORGANIZACAO_AUTOR : 
  o ID_USUARIO_SUBMISSAO : FK
  * TAG : 
  * NUMR_ORDEM : 
  * INDI_ATIVO : 
  * DATA_CRIACAO : 
  * DATA_ATUALIZACAO : 
}
entity "CIA_FERRAMENTA_MCP" as CIA_FERRAMENTA_MCP {
  * ID_FERRAMENTA_MCP : PK
  * ID_SERVIDOR_MCP : FK
  * NOME_FERRAMENTA : 
  * DESC_FERRAMENTA : 
  * INFO_PARAMETRO : 
  o TIPO_RETORNO : 
  o DESC_EXEMPLO_CHAMADA : 
  * NUMR_ORDEM : 
}
entity "CIA_METRICA" as CIA_METRICA {
  * ID_METRICA : PK
  * DESC_METRICA : 
  * TIPO_METRICA : 
}
entity "CIA_CREDENCIAL_ACESSO_MODELO" as CIA_CREDENCIAL_ACESSO_MODELO {
  * ID_CREDENCIAL_ACESSO : PK
  * ID_SOLICITACAO_ACESSO : FK
  * URL_ENDPOINT_BASE : 
  * CHAVE_ACESSO_CRIPTO : 
  * SEGREDO_ACESSO_CRIPTO : 
  * INFO_CABECALHO_PUBLICO : 
  * DESC_OBSERVACAO_USO : 
  * INDI_ATIVO : 
  * ID_USUARIO_CRIACAO : FK
  o ID_USUARIO_ATUALIZACAO : FK
  * DATA_CRIACAO : 
  * DATA_ATUALIZACAO : 
}
entity "CIA_SOLICITACAO_ACESSO_MODELO" as CIA_SOLICITACAO_ACESSO_MODELO {
  * ID_SOLICITACAO_ACESSO : PK
  * ID_MODELO : FK
  * ID_USUARIO : FK
  * NOME_APLICACAO : 
  * STAT_SOLICITACAO : 
  * DESC_JUSTIFICATIVA : 
  o DESC_USO_PRETENDIDO : 
  * INFO_CONTEXTO_SOLICITACAO : 
  o ID_USUARIO_REVISAO : FK
  o DATA_REVISAO : 
  o DESC_OBSERVACAO_REVISAO : 
  * DATA_CRIACAO : 
  * DATA_ATUALIZACAO : 
}
entity "CIA_MODELO" as CIA_MODELO {
  * ID_MODELO : PK
  * NOME_MODELO : 
  * SLUG_MODELO : 
  * ID_CATEGORIA_MODELO : FK
  * DESC_MODELO : 
  o INFO_CAPABILIDADE : 
  * STAT_MODELO : 
  o QTDE_JANELA_CONTEXTO : 
  o INFO_LIMITE_USO : 
  o TAG : 
  * INDI_NOVO : 
  * INDI_DESTAQUE : 
  * INDI_ATIVO : 
  * NUMR_ORDEM : 
  * DATA_CRIACAO : 
  * DATA_ATUALIZACAO : 
  * INDI_APROVACAO_ACESSO : 
  * DESC_RESUMO_ACESSO : 
  * DESC_DOCUMENTACAO_ACESSO : 
  o INFO_ENDPOINT_PADRAO : 
  * TIPO_AUTENTICACAO_PADRAO : 
  o ID_FORNECEDOR : FK
}
entity "CIA_NOTICIA" as CIA_NOTICIA {
  * ID_NOTICIA : PK
  * CATEGORIA_NOTICIA : 
  * TITULO_NOTICIA : 
  * DESC_RESUMO : 
  * DESC_CONTEUDO : 
  o URL_LINK : 
  * QTDE_TEMPO_LEITURA : 
  * INDI_PUBLICADO : 
  o DATA_PUBLICACAO : 
  * DATA_CRIACAO : 
  * DATA_ATUALIZACAO : 
}
entity "CIA_LEITURA_NOTIFICACAO" as CIA_LEITURA_NOTIFICACAO {
  * ID_USUARIO : PK FK
  * ID_NOTIFICACAO : PK FK
  * DATA_LEITURA : 
}
entity "CIA_DESTINATARIO_NOTIFICACAO" as CIA_DESTINATARIO_NOTIFICACAO {
  * ID_NOTIFICACAO : PK FK
  * ID_USUARIO : PK FK
  * DATA_CRIACAO : 
}
entity "CIA_NOTIFICACAO" as CIA_NOTIFICACAO {
  * ID_NOTIFICACAO : PK
  * TIPO_NOTIFICACAO : 
  * TITULO_NOTIFICACAO : 
  * DESC_MENSAGEM : 
  o URL_LINK : 
  * INDI_GLOBAL : 
  * DATA_CRIACAO : 
  o DATA_EXPIRACAO : 
}
entity "CIA_CATEGORIA_PROMPT" as CIA_CATEGORIA_PROMPT {
  * ID_CATEGORIA_PROMPT : PK
  * NOME_CATEGORIA : 
  * SLUG_CATEGORIA : 
  * CODG_COR : 
  * NUMR_ORDEM : 
  * NOME_ICONE : 
  * DESC_CATEGORIA : 
  * INDI_ATIVO : 
}
entity "CIA_FAVORITO_PROMPT" as CIA_FAVORITO_PROMPT {
  * ID_USUARIO : PK FK
  * ID_PROMPT : PK FK
  * DATA_CRIACAO : 
}
entity "CIA_FORK_PROMPT" as CIA_FORK_PROMPT {
  * ID_FORK_PROMPT : PK
  * ID_PROMPT_ORIGINAL : FK
  * ID_PROMPT_FORK : FK
  o DESC_MENSAGEM_FORK : 
  * DATA_CRIACAO : 
}
entity "CIA_DENUNCIA_PROMPT" as CIA_DENUNCIA_PROMPT {
  * ID_DENUNCIA_PROMPT : PK
  * ID_PROMPT : FK
  * ID_USUARIO_DENUNCIANTE : FK
  * TIPO_MOTIVO_DENUNCIA : 
  o DESC_DENUNCIA : 
  * STAT_DENUNCIA : 
  o ID_USUARIO_RESOLUCAO : FK
  o DATA_RESOLUCAO : 
  o DESC_OBSERVACAO_RESOLUCAO : 
  * DATA_CRIACAO : 
}
entity "CIA_AVALIACAO_PROMPT" as CIA_AVALIACAO_PROMPT {
  * ID_AVALIACAO_PROMPT : PK
  * ID_PROMPT : FK
  * ID_USUARIO : FK
  * NUMR_AVALIACAO : 
  o DESC_COMENTARIO : 
  * INDI_UTILIZADO_ANTES : 
  * INDI_APROVADO : 
  * DATA_CRIACAO : 
  * DATA_ATUALIZACAO : 
}
entity "CIA_USO_PROMPT" as CIA_USO_PROMPT {
  * ID_USO_PROMPT : PK
  * ID_PROMPT : FK
  * ID_USUARIO : FK
  * DATA_UTILIZACAO : 
}
entity "CIA_VERSAO_PROMPT" as CIA_VERSAO_PROMPT {
  * ID_VERSAO_PROMPT : PK
  * ID_PROMPT : FK
  * NUMR_VERSAO : 
  * TITULO_PROMPT : 
  * DESC_PROMPT : 
  * DESC_CONTEUDO : 
  * INFO_VARIAVEL : 
  * TAG : 
  o ID_USUARIO_APROVACAO : FK
  * DATA_APROVACAO : 
}
entity "CIA_PROMPT" as CIA_PROMPT {
  * ID_PROMPT : PK
  * TITULO_PROMPT : 
  * DESC_PROMPT : 
  * DESC_CONTEUDO : 
  o ID_CATEGORIA_PROMPT : FK
  o ID_MODELO : FK
  * TAG : 
  * NIVEL_DIFICULDADE : 
  * QTDE_USO : 
  * INFO_VARIAVEL : 
  o ID_USUARIO_AUTOR : FK
  * INDI_PUBLICO : 
  * INDI_ATIVO : 
  * DATA_CRIACAO : 
  * DATA_ATUALIZACAO : 
  * VALR_MEDIA_AVALIACAO : 
  * QTDE_AVALIACAO : 
  * STAT_PUBLICACAO : 
  * TIPO_ORIGEM : 
  o DATA_SUBMISSAO : 
  o ID_USUARIO_REVISAO : FK
  o DATA_REVISAO : 
  o DESC_OBSERVACAO_REVISAO : 
  o NOME_AUTOR_ORIGINAL : 
  * QTDE_DENUNCIA : 
  * NUMR_VERSAO : 
  o DESC_OBSERVACAO_SUBMISSAO : 
}
entity "CIA_FORNECEDOR" as CIA_FORNECEDOR {
  * ID_FORNECEDOR : PK
  * NOME_FORNECEDOR : 
}
entity "CIA_RESULTADO" as CIA_RESULTADO {
  * ID_RESULTADO : PK
  * DATA_CRIACAO : 
  * INFO_RESULTADO : 
  o ID_BANCO_QUESTAO : FK
  o ID_MODELO : FK
  * TIPO_RESULTADO : 
  * INDI_ERRO : 
  o INFO_ERRO : 
  * QTDE_TOTAL_TOKEN : 
  * QTDE_TOKEN_INPUT : 
  * QTDE_TOKEN_OUTPUT : 
}
entity "CIA_PERMISSAO_FUNCIONALIDADE" as CIA_PERMISSAO_FUNCIONALIDADE {
  * TIPO_PERFIL : PK
  * CHAVE_FUNCIONALIDADE : PK FK
  * INDI_HABILITADO : 
  * DATA_CRIACAO : 
  * DATA_ATUALIZACAO : 
}
entity "CIA_USUARIO" as CIA_USUARIO {
  * ID_USUARIO : PK
  * NOME_USUARIO : 
  * DESC_EMAIL : 
  o CODG_USUARIO : 
  * TIPO_PERFIL : 
  * NOME_ORGAO : 
  o URL_AVATAR : 
  * INDI_ATIVO : 
  * DATA_CRIACAO : 
  * DATA_ATUALIZACAO : 
  o HASH_SENHA : 
}
CIA_CATEGORIA_MODELO ||--}| CIA_MODELO : possui / pertence
CIA_FORNECEDOR ||--}o CIA_MODELO : possui / pertence
CIA_USUARIO ||--}o CIA_LOG_AUDITORIA : usuarioSistema
CIA_METRICA ||--}o CIA_BANCO_QUESTAO : possui / pertence
CIA_USUARIO ||--}o CIA_ARTIGO_DOCUMENTACAO : usuarioSistema
CIA_SECAO_DOCUMENTACAO ||--}o CIA_ARTIGO_DOCUMENTACAO : possui / pertence
CIA_SECAO_DOCUMENTACAO ||--}o CIA_SECAO_DOCUMENTACAO : possui / pertence
CIA_COMENTARIO_IDEIA ||--}| CIA_REACAO_COMENTARIO_IDEIA : possui / pertence
CIA_USUARIO ||--}| CIA_REACAO_COMENTARIO_IDEIA : usuarioSistema
CIA_IDEIA ||--}| CIA_COMENTARIO_IDEIA : possui / pertence
CIA_USUARIO ||--}| CIA_COMENTARIO_IDEIA : usuarioSistema
CIA_USUARIO ||--}o CIA_COMENTARIO_IDEIA : usuarioSistema
CIA_COMENTARIO_IDEIA ||--}o CIA_COMENTARIO_IDEIA : possui / pertence
CIA_IDEIA ||--}| CIA_VINCULO_IDEIA_TOPICO : possui / pertence
CIA_TOPICO_IDEIA ||--}| CIA_VINCULO_IDEIA_TOPICO : possui / pertence
CIA_USUARIO ||--}o CIA_VERSAO_IDEIA : usuarioSistema
CIA_IDEIA ||--}| CIA_VOTO_IDEIA : possui / pertence
CIA_USUARIO ||--}| CIA_VOTO_IDEIA : usuarioSistema
CIA_USUARIO ||--}| CIA_IDEIA : usuarioSistema
CIA_USUARIO ||--}o CIA_IDEIA : usuarioSistema
CIA_VERSAO_IDEIA ||--}o CIA_IDEIA : possui / pertence
CIA_MODELO ||--}o CIA_INDICADOR : possui / pertence
CIA_METRICA ||--}o CIA_INDICADOR : possui / pertence
CIA_SERVIDOR_MCP ||--}| CIA_AGENTE_MCP : possui / pertence
CIA_SERVIDOR_MCP ||--}| CIA_CONFIGURACAO_MCP : possui / pertence
CIA_USUARIO ||--}| CIA_FAVORITO_MCP : usuarioSistema
CIA_SERVIDOR_MCP ||--}| CIA_FAVORITO_MCP : possui / pertence
CIA_SERVIDOR_MCP ||--}| CIA_INSTALACAO_MCP : possui / pertence
CIA_USUARIO ||--}| CIA_INSTALACAO_MCP : usuarioSistema
CIA_SERVIDOR_MCP ||--}| CIA_RECURSO_MCP : possui / pertence
CIA_SERVIDOR_MCP ||--}| CIA_AVALIACAO_MCP : possui / pertence
CIA_USUARIO ||--}| CIA_AVALIACAO_MCP : usuarioSistema
CIA_CATEGORIA_MCP ||--}o CIA_SERVIDOR_MCP : possui / pertence
CIA_USUARIO ||--}o CIA_SERVIDOR_MCP : usuarioSistema
CIA_SERVIDOR_MCP ||--}| CIA_FERRAMENTA_MCP : possui / pertence
CIA_SOLICITACAO_ACESSO_MODELO ||--|| CIA_CREDENCIAL_ACESSO_MODELO : possui / pertence
CIA_USUARIO ||--}| CIA_CREDENCIAL_ACESSO_MODELO : usuarioSistema
CIA_USUARIO ||--}o CIA_CREDENCIAL_ACESSO_MODELO : usuarioSistema
CIA_MODELO ||--}| CIA_SOLICITACAO_ACESSO_MODELO : possui / pertence
CIA_USUARIO ||--}| CIA_SOLICITACAO_ACESSO_MODELO : usuarioSistema
CIA_USUARIO ||--}o CIA_SOLICITACAO_ACESSO_MODELO : usuarioSistema
CIA_USUARIO ||--}| CIA_LEITURA_NOTIFICACAO : usuarioSistema
CIA_NOTIFICACAO ||--}| CIA_LEITURA_NOTIFICACAO : possui / pertence
CIA_NOTIFICACAO ||--}| CIA_DESTINATARIO_NOTIFICACAO : possui / pertence
CIA_USUARIO ||--}| CIA_DESTINATARIO_NOTIFICACAO : usuarioSistema
CIA_USUARIO ||--}| CIA_FAVORITO_PROMPT : usuarioSistema
CIA_PROMPT ||--}| CIA_FAVORITO_PROMPT : possui / pertence
CIA_PROMPT ||--}| CIA_FORK_PROMPT : possui / pertence
CIA_PROMPT ||--}| CIA_FORK_PROMPT : possui / pertence
CIA_PROMPT ||--}| CIA_DENUNCIA_PROMPT : possui / pertence
CIA_USUARIO ||--}| CIA_DENUNCIA_PROMPT : usuarioSistema
CIA_USUARIO ||--}o CIA_DENUNCIA_PROMPT : usuarioSistema
CIA_PROMPT ||--}| CIA_AVALIACAO_PROMPT : possui / pertence
CIA_USUARIO ||--}| CIA_AVALIACAO_PROMPT : usuarioSistema
CIA_PROMPT ||--}| CIA_USO_PROMPT : possui / pertence
CIA_USUARIO ||--}| CIA_USO_PROMPT : usuarioSistema
CIA_PROMPT ||--}| CIA_VERSAO_PROMPT : possui / pertence
CIA_USUARIO ||--}o CIA_VERSAO_PROMPT : usuarioSistema
CIA_USUARIO ||--}o CIA_PROMPT : usuarioSistema
CIA_CATEGORIA_PROMPT ||--}o CIA_PROMPT : possui / pertence
CIA_MODELO ||--}o CIA_PROMPT : possui / pertence
CIA_USUARIO ||--}o CIA_PROMPT : usuarioSistema
CIA_BANCO_QUESTAO ||--}o CIA_RESULTADO : possui / pertence
CIA_MODELO ||--}o CIA_RESULTADO : possui / pertence
CIA_FUNCIONALIDADE ||--}| CIA_PERMISSAO_FUNCIONALIDADE : possui / pertence
@enduml
