@startuml
' DER gerado a partir de docs/migrations_oracle
hide circle
skinparam linetype ortho
skinparam class {
  BackgroundColor White
  BorderColor Black
  ArrowColor Black
}

entity "CIA_USUARIO" as CIA_USUARIO {
  * ID_USUARIO : PK
  * NOME_USUARIO : 
  * DESC_EMAIL : 
  o CODG_USUARIO : 
  * TIPO_PERFIL : 
  * NOME_ORGAO : 
  o URL_AVATAR : 
  * INDI_ATIVO : 
  * DATA_CRIACAO : 
  * DATA_ATUALIZACAO : 
  o HASH_SENHA : 
}

entity "CIA_REACAO_COMENTARIO_IDEIA" as CIA_REACAO_COMENTARIO_IDEIA {
  * ID_COMENTARIO_IDEIA : PK FK
  * ID_USUARIO : PK FK
  * TIPO_REACAO : 
  * DATA_CRIACAO : 
}

entity "CIA_COMENTARIO_IDEIA" as CIA_COMENTARIO_IDEIA {
  * ID_COMENTARIO_IDEIA : PK
  * ID_IDEIA : FK
  o ID_COMENTARIO_PAI : FK
  * ID_USUARIO_AUTOR : FK
  * DESC_CONTEUDO : 
  * STAT_MODERACAO : 
  o DESC_MOTIVO_MODERACAO : 
  o ID_USUARIO_MODERADOR : FK
  o DATA_MODERACAO : 
  * DATA_CRIACAO : 
  * DATA_ATUALIZACAO : 
}

entity "CIA_VINCULO_IDEIA_TOPICO" as CIA_VINCULO_IDEIA_TOPICO {
  * ID_IDEIA : PK FK
  * ID_TOPICO_IDEIA : PK FK
}

entity "CIA_TOPICO_IDEIA" as CIA_TOPICO_IDEIA {
  * ID_TOPICO_IDEIA : PK
  * NOME_TOPICO : 
  * SLUG_TOPICO : 
  * COR_TOPICO : 
  o NOME_ICONE : 
  o DESC_TOPICO : 
  * NUMR_ORDEM : 
  * INDI_ATIVO : 
  * DATA_CRIACAO : 
  * DATA_ATUALIZACAO : 
}

entity "CIA_VERSAO_IDEIA" as CIA_VERSAO_IDEIA {
  * ID_VERSAO_IDEIA : PK
  * NOME_VERSAO : 
  o DESC_VERSAO : 
  o INFO_PREVISAO : 
  * NUMR_ORDEM : 
  * INDI_ATIVO : 
  o ID_USUARIO_CRIACAO : FK
  * DATA_CRIACAO : 
  * DATA_ATUALIZACAO : 
}

entity "CIA_VOTO_IDEIA" as CIA_VOTO_IDEIA {
  * ID_IDEIA : PK FK
  * ID_USUARIO : PK FK
  * DATA_CRIACAO : 
}

entity "CIA_IDEIA" as CIA_IDEIA {
  * ID_IDEIA : PK
  * NOME_IDEIA : 
  * DESC_IDEIA : 
  * ID_USUARIO_AUTOR : FK
  * STAT_MODERACAO : 
  o STAT_IDEIA : 
  o ID_VERSAO_IDEIA : FK
  o DESC_CURADORIA : 
  o DESC_MOTIVO_REJEICAO : 
  o DATA_SOLICITACAO_EXCLUSAO : 
  o DESC_MOTIVO_SOLIC_EXCLUSAO : 
  o DATA_EXCLUSAO : 
  o DATA_PUBLICACAO : 
  o ID_USUARIO_REVISAO : FK
  o DATA_REVISAO : 
  * DATA_CRIACAO : 
  * DATA_ATUALIZACAO : 
}

CIA_COMENTARIO_IDEIA ||--|{ CIA_REACAO_COMENTARIO_IDEIA : "possui \n pertence"
CIA_USUARIO ||--|{ CIA_REACAO_COMENTARIO_IDEIA : "usuarioSistema"
CIA_IDEIA ||--|{ CIA_COMENTARIO_IDEIA : "possui \n pertence"
CIA_USUARIO ||--|{ CIA_COMENTARIO_IDEIA : "usuarioSistema"
CIA_USUARIO ||--o{ CIA_COMENTARIO_IDEIA : "usuarioSistema"
CIA_COMENTARIO_IDEIA ||--o{ CIA_COMENTARIO_IDEIA : "possui \n pertence"
CIA_IDEIA ||--|{ CIA_VINCULO_IDEIA_TOPICO : "possui \n pertence"
CIA_TOPICO_IDEIA ||--|{ CIA_VINCULO_IDEIA_TOPICO : "possui \n pertence"
CIA_USUARIO ||--o{ CIA_VERSAO_IDEIA : "usuarioSistema"
CIA_IDEIA ||--|{ CIA_VOTO_IDEIA : "possui \n pertence"
CIA_USUARIO ||--|{ CIA_VOTO_IDEIA : "usuarioSistema"
CIA_USUARIO ||--|{ CIA_IDEIA : "usuarioSistema"
CIA_USUARIO ||--o{ CIA_IDEIA : "usuarioSistema"
CIA_VERSAO_IDEIA ||--o{ CIA_IDEIA : "possui \n pertence"
@enduml
